module Rice
  class Buffer≺vector≺unsigned char≻≻
    def initialize: (value: Integer) -> NilClass
               | (value: Integer, size: Integer) -> NilClass
    def []: (index: Integer) -> Std::Vector≺unsigned char≻
    def []=: (arg_0: Integer, arg_1: Std::Vector≺unsigned char≻) -> NilClass
    def bytes: () -> Integer
          | (arg_0: Integer) -> Integer
    def data: () -> Rice::Pointer≺vector≺unsigned char≻≻
    def release: () -> Rice::Pointer≺vector≺unsigned char≻≻
    def size: () -> Integer
    def to_ary: () -> Array
           | (arg_0: Integer) -> Array
    def to_s: () -> Integer
  end
end
