module Rice
  class Buffer≺cv꞉꞉Vec≺double‚ 4≻≻
    def initialize: (value: Integer) -> NilClass
               | (value: Integer, size: Integer) -> NilClass
    def []: (index: Integer) -> Cv::Vec4d
    def []=: (arg_0: Integer, arg_1: Cv::Vec4d) -> NilClass
    def bytes: () -> Integer
          | (arg_0: Integer) -> Integer
    def data: () -> Rice::Pointer≺cv꞉꞉Vec≺double‚ 4≻≻
    def release: () -> Rice::Pointer≺cv꞉꞉Vec≺double‚ 4≻≻
    def size: () -> Integer
    def to_ary: () -> Array
           | (arg_0: Integer) -> Array
    def to_s: () -> Integer
  end
end
