module Cv::Stereo
  class StereoBinarySGBM
    def get_binary_kernel_type: () -> Integer
    def get_mode: () -> Integer
    def get_p1: () -> Integer
    def get_p2: () -> Integer
    def get_pre_filter_cap: () -> Integer
    def get_spekle_removal_technique: () -> Integer
    def get_sub_pixel_interpolation_method: () -> Integer
    def get_uniqueness_ratio: () -> Integer
    def set_binary_kernel_type: (value: Integer) -> NilClass
    def set_mode: (mode: Integer) -> NilClass
    def set_p1: (p1: Integer) -> NilClass
    def set_p2: (p2: Integer) -> NilClass
    def set_pre_filter_cap: (pre_filter_cap: Integer) -> NilClass
    def set_spekle_removal_technique: (factor: Integer) -> NilClass
    def set_sub_pixel_interpolation_method: (value: Integer) -> NilClass
    def set_uniqueness_ratio: (uniqueness_ratio: Integer) -> NilClass
  end
end
