// Generated by ruby-bindgen (1.0.0)

#include <opencv2/imgproc/detail/legacy.hpp>
#include "legacy-rb.hpp"

using namespace Rice;

void Init_Imgproc_Detail_Legacy()
{
  Module rb_mCv = define_module("Cv");
}
