// Generated by ruby-bindgen (1.0.0)

#include <opencv2/core/fast_math.hpp>
#include "fast_math-rb.hpp"

using namespace Rice;

void Init_Core_FastMath()
{
  Class(rb_cObject).define_constant("OPENCV_USE_FASTMATH_BUILTINS", OPENCV_USE_FASTMATH_BUILTINS);

  define_global_function<int(*)(double)>("cv_round", static_cast<int(*)(double)>(&cvRound),
    Arg("value"));

  define_global_function<int(*)(double)>("cv_floor", static_cast<int(*)(double)>(&cvFloor),
    Arg("value"));

  define_global_function<int(*)(double)>("cv_ceil", static_cast<int(*)(double)>(&cvCeil),
    Arg("value"));

  define_global_function<int(*)(double)>("cv_is_na_n", static_cast<int(*)(double)>(&cvIsNaN),
    Arg("value"));

  define_global_function<int(*)(double)>("cv_is_inf", static_cast<int(*)(double)>(&cvIsInf),
    Arg("value"));

  define_global_function<int(*)(float)>("cv_round", static_cast<int(*)(float)>(&cvRound),
    Arg("value"));

  define_global_function<int(*)(int)>("cv_round", static_cast<int(*)(int)>(&cvRound),
    Arg("value"));

  define_global_function<int(*)(float)>("cv_floor", static_cast<int(*)(float)>(&cvFloor),
    Arg("value"));

  define_global_function<int(*)(int)>("cv_floor", static_cast<int(*)(int)>(&cvFloor),
    Arg("value"));

  define_global_function<int(*)(float)>("cv_ceil", static_cast<int(*)(float)>(&cvCeil),
    Arg("value"));

  define_global_function<int(*)(int)>("cv_ceil", static_cast<int(*)(int)>(&cvCeil),
    Arg("value"));

  define_global_function<int(*)(float)>("cv_is_na_n", static_cast<int(*)(float)>(&cvIsNaN),
    Arg("value"));

  define_global_function<int(*)(float)>("cv_is_inf", static_cast<int(*)(float)>(&cvIsInf),
    Arg("value"));
}
