// Generated by ruby-bindgen (1.0.0)

#include <opencv2/core/saturate.hpp>
#include "saturate-rb.hpp"

using namespace Rice;

void Init_Core_Saturate()
{
  Module rb_mCv = define_module("Cv");

  rb_mCv.define_module_function<uchar(*)(schar)>("saturate_cast", static_cast<uchar(*)(schar)>(&cv::saturate_cast),
    Arg("v"));

  rb_mCv.define_module_function<uchar(*)(ushort)>("saturate_cast", static_cast<uchar(*)(ushort)>(&cv::saturate_cast),
    Arg("v"));

  rb_mCv.define_module_function<uchar(*)(int)>("saturate_cast", static_cast<uchar(*)(int)>(&cv::saturate_cast),
    Arg("v"));

  rb_mCv.define_module_function<uchar(*)(short)>("saturate_cast", static_cast<uchar(*)(short)>(&cv::saturate_cast),
    Arg("v"));

  rb_mCv.define_module_function<uchar(*)(unsigned int)>("saturate_cast", static_cast<uchar(*)(unsigned int)>(&cv::saturate_cast),
    Arg("v"));

  rb_mCv.define_module_function<uchar(*)(float)>("saturate_cast", static_cast<uchar(*)(float)>(&cv::saturate_cast),
    Arg("v"));

  rb_mCv.define_module_function<uchar(*)(double)>("saturate_cast", static_cast<uchar(*)(double)>(&cv::saturate_cast),
    Arg("v"));

  rb_mCv.define_module_function<uchar(*)(int64)>("saturate_cast", static_cast<uchar(*)(int64)>(&cv::saturate_cast),
    Arg("v"));

  rb_mCv.define_module_function<uchar(*)(uint64)>("saturate_cast", static_cast<uchar(*)(uint64)>(&cv::saturate_cast),
    Arg("v"));

  rb_mCv.define_module_function<schar(*)(uchar)>("saturate_cast", static_cast<schar(*)(uchar)>(&cv::saturate_cast),
    Arg("v"));

  rb_mCv.define_module_function<schar(*)(ushort)>("saturate_cast", static_cast<schar(*)(ushort)>(&cv::saturate_cast),
    Arg("v"));

  rb_mCv.define_module_function<schar(*)(int)>("saturate_cast", static_cast<schar(*)(int)>(&cv::saturate_cast),
    Arg("v"));

  rb_mCv.define_module_function<schar(*)(short)>("saturate_cast", static_cast<schar(*)(short)>(&cv::saturate_cast),
    Arg("v"));

  rb_mCv.define_module_function<schar(*)(unsigned int)>("saturate_cast", static_cast<schar(*)(unsigned int)>(&cv::saturate_cast),
    Arg("v"));

  rb_mCv.define_module_function<schar(*)(float)>("saturate_cast", static_cast<schar(*)(float)>(&cv::saturate_cast),
    Arg("v"));

  rb_mCv.define_module_function<schar(*)(double)>("saturate_cast", static_cast<schar(*)(double)>(&cv::saturate_cast),
    Arg("v"));

  rb_mCv.define_module_function<schar(*)(int64)>("saturate_cast", static_cast<schar(*)(int64)>(&cv::saturate_cast),
    Arg("v"));

  rb_mCv.define_module_function<schar(*)(uint64)>("saturate_cast", static_cast<schar(*)(uint64)>(&cv::saturate_cast),
    Arg("v"));

  rb_mCv.define_module_function<ushort(*)(schar)>("saturate_cast", static_cast<ushort(*)(schar)>(&cv::saturate_cast),
    Arg("v"));

  rb_mCv.define_module_function<ushort(*)(short)>("saturate_cast", static_cast<ushort(*)(short)>(&cv::saturate_cast),
    Arg("v"));

  rb_mCv.define_module_function<ushort(*)(int)>("saturate_cast", static_cast<ushort(*)(int)>(&cv::saturate_cast),
    Arg("v"));

  rb_mCv.define_module_function<ushort(*)(unsigned int)>("saturate_cast", static_cast<ushort(*)(unsigned int)>(&cv::saturate_cast),
    Arg("v"));

  rb_mCv.define_module_function<ushort(*)(float)>("saturate_cast", static_cast<ushort(*)(float)>(&cv::saturate_cast),
    Arg("v"));

  rb_mCv.define_module_function<ushort(*)(double)>("saturate_cast", static_cast<ushort(*)(double)>(&cv::saturate_cast),
    Arg("v"));

  rb_mCv.define_module_function<ushort(*)(int64)>("saturate_cast", static_cast<ushort(*)(int64)>(&cv::saturate_cast),
    Arg("v"));

  rb_mCv.define_module_function<ushort(*)(uint64)>("saturate_cast", static_cast<ushort(*)(uint64)>(&cv::saturate_cast),
    Arg("v"));

  rb_mCv.define_module_function<short(*)(ushort)>("saturate_cast", static_cast<short(*)(ushort)>(&cv::saturate_cast),
    Arg("v"));

  rb_mCv.define_module_function<short(*)(int)>("saturate_cast", static_cast<short(*)(int)>(&cv::saturate_cast),
    Arg("v"));

  rb_mCv.define_module_function<short(*)(unsigned int)>("saturate_cast", static_cast<short(*)(unsigned int)>(&cv::saturate_cast),
    Arg("v"));

  rb_mCv.define_module_function<short(*)(float)>("saturate_cast", static_cast<short(*)(float)>(&cv::saturate_cast),
    Arg("v"));

  rb_mCv.define_module_function<short(*)(double)>("saturate_cast", static_cast<short(*)(double)>(&cv::saturate_cast),
    Arg("v"));

  rb_mCv.define_module_function<short(*)(int64)>("saturate_cast", static_cast<short(*)(int64)>(&cv::saturate_cast),
    Arg("v"));

  rb_mCv.define_module_function<short(*)(uint64)>("saturate_cast", static_cast<short(*)(uint64)>(&cv::saturate_cast),
    Arg("v"));

  rb_mCv.define_module_function<int(*)(unsigned int)>("saturate_cast", static_cast<int(*)(unsigned int)>(&cv::saturate_cast),
    Arg("v"));

  rb_mCv.define_module_function<int(*)(int64)>("saturate_cast", static_cast<int(*)(int64)>(&cv::saturate_cast),
    Arg("v"));

  rb_mCv.define_module_function<int(*)(uint64)>("saturate_cast", static_cast<int(*)(uint64)>(&cv::saturate_cast),
    Arg("v"));

  rb_mCv.define_module_function<int(*)(float)>("saturate_cast", static_cast<int(*)(float)>(&cv::saturate_cast),
    Arg("v"));

  rb_mCv.define_module_function<int(*)(double)>("saturate_cast", static_cast<int(*)(double)>(&cv::saturate_cast),
    Arg("v"));

  rb_mCv.define_module_function<unsigned int(*)(schar)>("saturate_cast", static_cast<unsigned int(*)(schar)>(&cv::saturate_cast),
    Arg("v"));

  rb_mCv.define_module_function<unsigned int(*)(short)>("saturate_cast", static_cast<unsigned int(*)(short)>(&cv::saturate_cast),
    Arg("v"));

  rb_mCv.define_module_function<unsigned int(*)(int)>("saturate_cast", static_cast<unsigned int(*)(int)>(&cv::saturate_cast),
    Arg("v"));

  rb_mCv.define_module_function<unsigned int(*)(int64)>("saturate_cast", static_cast<unsigned int(*)(int64)>(&cv::saturate_cast),
    Arg("v"));

  rb_mCv.define_module_function<unsigned int(*)(uint64)>("saturate_cast", static_cast<unsigned int(*)(uint64)>(&cv::saturate_cast),
    Arg("v"));

  rb_mCv.define_module_function<unsigned int(*)(float)>("saturate_cast", static_cast<unsigned int(*)(float)>(&cv::saturate_cast),
    Arg("v"));

  rb_mCv.define_module_function<unsigned int(*)(double)>("saturate_cast", static_cast<unsigned int(*)(double)>(&cv::saturate_cast),
    Arg("v"));

  rb_mCv.define_module_function<uint64(*)(schar)>("saturate_cast", static_cast<uint64(*)(schar)>(&cv::saturate_cast),
    Arg("v"));

  rb_mCv.define_module_function<uint64(*)(short)>("saturate_cast", static_cast<uint64(*)(short)>(&cv::saturate_cast),
    Arg("v"));

  rb_mCv.define_module_function<uint64(*)(int)>("saturate_cast", static_cast<uint64(*)(int)>(&cv::saturate_cast),
    Arg("v"));

  rb_mCv.define_module_function<uint64(*)(int64)>("saturate_cast", static_cast<uint64(*)(int64)>(&cv::saturate_cast),
    Arg("v"));

  rb_mCv.define_module_function<int64(*)(uint64)>("saturate_cast", static_cast<int64(*)(uint64)>(&cv::saturate_cast),
    Arg("v"));

  #if RUBY_CV_VERSION >= 410

  rb_mCv.define_module_function<cv::hfloat(*)(uchar)>("saturate_cast", static_cast<cv::hfloat(*)(uchar)>(&cv::saturate_cast),
    Arg("v"));

  rb_mCv.define_module_function<cv::hfloat(*)(schar)>("saturate_cast", static_cast<cv::hfloat(*)(schar)>(&cv::saturate_cast),
    Arg("v"));

  rb_mCv.define_module_function<cv::hfloat(*)(ushort)>("saturate_cast", static_cast<cv::hfloat(*)(ushort)>(&cv::saturate_cast),
    Arg("v"));

  rb_mCv.define_module_function<cv::hfloat(*)(short)>("saturate_cast", static_cast<cv::hfloat(*)(short)>(&cv::saturate_cast),
    Arg("v"));

  rb_mCv.define_module_function<cv::hfloat(*)(unsigned int)>("saturate_cast", static_cast<cv::hfloat(*)(unsigned int)>(&cv::saturate_cast),
    Arg("v"));

  rb_mCv.define_module_function<cv::hfloat(*)(int)>("saturate_cast", static_cast<cv::hfloat(*)(int)>(&cv::saturate_cast),
    Arg("v"));

  rb_mCv.define_module_function<cv::hfloat(*)(uint64)>("saturate_cast", static_cast<cv::hfloat(*)(uint64)>(&cv::saturate_cast),
    Arg("v"));

  rb_mCv.define_module_function<cv::hfloat(*)(int64)>("saturate_cast", static_cast<cv::hfloat(*)(int64)>(&cv::saturate_cast),
    Arg("v"));

  rb_mCv.define_module_function<cv::hfloat(*)(float)>("saturate_cast", static_cast<cv::hfloat(*)(float)>(&cv::saturate_cast),
    Arg("v"));

  rb_mCv.define_module_function<cv::hfloat(*)(double)>("saturate_cast", static_cast<cv::hfloat(*)(double)>(&cv::saturate_cast),
    Arg("v"));

  #endif
}
