module Cv::DetectionBasedTracker
  class ExtObject
    attr_accessor id: Integer
    attr_accessor location: Cv::Rect_≺int≻
    attr_accessor status: Enum cv::DetectionBasedTracker::ObjectStatus

    def initialize: (_id: Integer, _location: Cv::Rect_≺int≻, _status: Enum cv::DetectionBasedTracker::ObjectStatus) -> void
  end
end
