module Cv::Xfeatures2d
  class LATCH
    def get_bytes: () -> Integer
    def get_default_name: () -> String
    def get_half_ss_dsize: () -> Integer
    def get_rotation_invariance?: () -> TrueClass
    def get_sigma: () -> Float
    def set_bytes: (bytes: Integer) -> NilClass
    def set_half_ss_dsize: (half_ssd_size: Integer) -> NilClass
    def set_rotation_invariance: (rotation_invariance: TrueClass) -> NilClass
    def set_sigma: (sigma: Float) -> NilClass
  end
end
