module Cv::Cuda
  class BufferPool
    def get_allocator: () -> Cv::Ptr≺cv꞉꞉cuda꞉꞉GpuMat꞉꞉Allocator≻
    def get_buffer: (size: Cv::Size_≺int≻, type: Integer) -> Cv::cuda::GpuMat
               | (rows: Integer, cols: Integer, type: Integer) -> Cv::cuda::GpuMat
    def initialize: (stream: Cv::cuda::Stream) -> void
  end
end
