module Cv::Cuda
  class DeviceInfo
    def async_engine_count: () -> Integer
    def can_map_host_memory?: () -> TrueClass
    def clock_rate: () -> Integer
    def initialize: () -> NilClass
               | (device_id: Integer) -> NilClass
    def compatible?: () -> TrueClass
    def compute_mode: () -> Cv::Cuda::DeviceInfo::ComputeMode
    def concurrent_kernels?: () -> TrueClass
    def device_id: () -> Integer
    def ecc_enabled?: () -> TrueClass
    def free_memory: () -> Integer
    def integrated?: () -> TrueClass
    def kernel_exec_timeout_enabled?: () -> TrueClass
    def l2_cache_size: () -> Integer
    def major_version: () -> Integer
    def max_grid_size: () -> Cv::Vec3i
    def max_surface1_d: () -> Integer
    def max_surface1_d_layered: () -> Cv::Vec2i
    def max_surface2_d_layered: () -> Cv::Vec3i
    def max_surface3_d: () -> Cv::Vec3i
    def max_surface_2d: () -> Cv::Vec2i
    def max_surface_cubemap: () -> Integer
    def max_surface_cubemap_layered: () -> Cv::Vec2i
    def max_texture1_d: () -> Integer
    def max_texture1_d_layered: () -> Cv::Vec2i
    def max_texture1_d_linear: () -> Integer
    def max_texture1_d_mipmap: () -> Integer
    def max_texture2_d_gather: () -> Cv::Vec2i
    def max_texture2_d_layered: () -> Cv::Vec3i
    def max_texture2_d_linear: () -> Cv::Vec3i
    def max_texture2_d_mipmap: () -> Cv::Vec2i
    def max_texture3_d: () -> Cv::Vec3i
    def max_texture_2d: () -> Cv::Vec2i
    def max_texture_cubemap: () -> Integer
    def max_texture_cubemap_layered: () -> Cv::Vec2i
    def max_threads_dim: () -> Cv::Vec3i
    def max_threads_per_block: () -> Integer
    def max_threads_per_multi_processor: () -> Integer
    def mem_pitch: () -> Integer
    def memory_bus_width: () -> Integer
    def memory_clock_rate: () -> Integer
    def minor_version: () -> Integer
    def multi_processor_count: () -> Integer
    def name: () -> String
    def pci_bus_id: () -> Integer
    def pci_device_id: () -> Integer
    def pci_domain_id: () -> Integer
    def query_memory: (total_memory: Integer, free_memory: Integer) -> NilClass
    def regs_per_block: () -> Integer
    def shared_mem_per_block: () -> Integer
    def supports?: (feature_set: Cv::Cuda::FeatureSet) -> TrueClass
    def surface_alignment: () -> Integer
    def tcc_driver?: () -> TrueClass
    def texture_alignment: () -> Integer
    def texture_pitch_alignment: () -> Integer
    def total_const_mem: () -> Integer
    def total_global_mem: () -> Integer
    def total_memory: () -> Integer
    def unified_addressing?: () -> TrueClass
    def warp_size: () -> Integer
  end
end
