module Cv::Cuda
  class DevPtrUnsignedShort
    attr_accessor data: Rice::Pointer≺unsigned short≻

    def elem_size: () -> Integer
    def initialize: () -> NilClass
               | (data_: Rice::Pointer≺unsigned short≻) -> NilClass
    def to_const_ptr: () -> Rice::Pointer≺unsigned short≻
    def to_ptr: () -> Rice::Pointer≺unsigned short≻
  end
end
