module Cv::Cuda
  class GpuMat
    attr_accessor allocator: Cv::Cuda::GpuMat::Allocator
    attr_accessor cols: Integer
    attr_accessor data: Rice::Pointer≺unsigned char≻
    attr_accessor dataend: Rice::Pointer≺unsigned char≻
    attr_accessor datastart: Rice::Pointer≺unsigned char≻
    attr_accessor flags: Integer
    attr_accessor refcount: Rice::Pointer≺int≻
    attr_accessor rows: Integer
    attr_accessor step: Integer

    def adjust_roi: (dtop: Integer, dbottom: Integer, dleft: Integer, dright: Integer) -> Cv::Cuda::GpuMat
    def initialize: (allocator: Cv::Cuda::GpuMat::Allocator) -> NilClass
               | (arr: Cv::InputArray, allocator: Cv::Cuda::GpuMat::Allocator) -> NilClass
               | (size: Cv::Size, type: Integer, allocator: Cv::Cuda::GpuMat::Allocator) -> NilClass
               | (m: Cv::Cuda::GpuMat, row_range: Cv::Range, col_range: Cv::Range) -> NilClass
               | (m: Cv::Cuda::GpuMat, roi: Cv::Rect) -> NilClass
               | (size: Cv::Size, type: Integer, s: Cv::Scalar, allocator: Cv::Cuda::GpuMat::Allocator) -> NilClass
               | (rows: Integer, cols: Integer, type: Integer, allocator: Cv::Cuda::GpuMat::Allocator) -> NilClass
               | (size: Cv::Size, type: Integer, data: Rice::Pointer≺void≻, step: Integer) -> NilClass
               | (rows: Integer, cols: Integer, type: Integer, s: Cv::Scalar, allocator: Cv::Cuda::GpuMat::Allocator) -> NilClass
               | (rows: Integer, cols: Integer, type: Integer, data: Rice::Pointer≺void≻, step: Integer) -> NilClass
    def assign: (m: Cv::Cuda::GpuMat) -> Cv::Cuda::GpuMat
    def call: (roi: Cv::Rect) -> Cv::Cuda::GpuMat
         | (row_range: Cv::Range, col_range: Cv::Range) -> Cv::Cuda::GpuMat
    def channels: () -> Integer
    def clone: () -> Cv::Cuda::GpuMat
    def col: (x: Integer) -> Cv::Cuda::GpuMat
    def col_range: (r: Cv::Range) -> Cv::Cuda::GpuMat
              | (startcol: Integer, endcol: Integer) -> Cv::Cuda::GpuMat
    def assign_to: (m: Cv::Cuda::GpuMat, type: Integer) -> NilClass
    def continuous?: () -> TrueClass
    def convert_to: (dst: Cv::OutputArray, rtype: Integer) -> NilClass
               | (dst: Cv::Cuda::GpuMat, rtype: Integer, stream: Cv::Cuda::Stream) -> NilClass
               | (dst: Cv::OutputArray, rtype: Integer, stream: Cv::Cuda::Stream) -> NilClass
               | (dst: Cv::OutputArray, rtype: Integer, alpha: Float, beta: Float) -> NilClass
               | (dst: Cv::OutputArray, rtype: Integer, alpha: Float, stream: Cv::Cuda::Stream) -> NilClass
               | (dst: Cv::OutputArray, rtype: Integer, alpha: Float, beta: Float, stream: Cv::Cuda::Stream) -> NilClass
               | (dst: Cv::Cuda::GpuMat, rtype: Integer, alpha: Float, beta: Float, stream: Cv::Cuda::Stream) -> NilClass
    def copy_to: (dst: Cv::OutputArray) -> NilClass
            | (dst: Cv::Cuda::GpuMat) -> NilClass
            | (dst: Cv::OutputArray, stream: Cv::Cuda::Stream) -> NilClass
            | (dst: Cv::Cuda::GpuMat, mask: Cv::Cuda::GpuMat) -> NilClass
            | (dst: Cv::Cuda::GpuMat, stream: Cv::Cuda::Stream) -> NilClass
            | (dst: Cv::OutputArray, mask: Cv::InputArray) -> NilClass
            | (dst: Cv::OutputArray, mask: Cv::InputArray, stream: Cv::Cuda::Stream) -> NilClass
            | (dst: Cv::Cuda::GpuMat, mask: Cv::Cuda::GpuMat, stream: Cv::Cuda::Stream) -> NilClass
    def create: (size: Cv::Size, type: Integer) -> NilClass
           | (rows: Integer, cols: Integer, type: Integer) -> NilClass
    def cuda_ptr: () -> Rice::Pointer≺void≻
    def depth: () -> Integer
    def download: (dst: Cv::OutputArray) -> NilClass
             | (dst: Cv::OutputArray, stream: Cv::Cuda::Stream) -> NilClass
    def elem_size: () -> Integer
    def elem_size1: () -> Integer
    def empty?: () -> TrueClass
    def initialize_copy: (m: Cv::Cuda::GpuMat) -> NilClass
    def locate_roi: (whole_size: Cv::Size, ofs: Cv::Point) -> NilClass
    def ptr: (y: Integer) -> Rice::Pointer≺unsigned char≻
        | (y: Integer) -> Rice::Pointer≺unsigned char≻
    def release: () -> NilClass
    def reshape: (cn: Integer, rows: Integer) -> Cv::Cuda::GpuMat
    def row: (y: Integer) -> Cv::Cuda::GpuMat
    def row_range: (r: Cv::Range) -> Cv::Cuda::GpuMat
              | (startrow: Integer, endrow: Integer) -> Cv::Cuda::GpuMat
    def set_to: (s: Cv::Scalar) -> Cv::Cuda::GpuMat
           | (s: Cv::Scalar, mask: Cv::InputArray) -> Cv::Cuda::GpuMat
           | (s: Cv::Scalar, stream: Cv::Cuda::Stream) -> Cv::Cuda::GpuMat
           | (s: Cv::Scalar, mask: Cv::InputArray, stream: Cv::Cuda::Stream) -> Cv::Cuda::GpuMat
    def size: () -> Cv::Size
    def step1: () -> Integer
    def swap: (mat: Cv::Cuda::GpuMat) -> NilClass
    def type: () -> Integer
    def update_continuity_flag: () -> NilClass
    def upload: (arr: Cv::InputArray) -> NilClass
           | (arr: Cv::InputArray, stream: Cv::Cuda::Stream) -> NilClass
  end
end
