module Cv::Cuda
  class GpuMatND
    attr_accessor dims: Integer
    attr_accessor flags: Integer
    attr_accessor size: Std::Vector≺int≻
    attr_accessor step: Std::Vector≺unsigned Int64≻

    def initialize: () -> NilClass
               | (size: Std::Vector≺int≻, type: Integer) -> NilClass
               | (size: Std::Vector≺int≻, type: Integer, data: Rice::Pointer≺void≻, step: Std::Vector≺unsigned Int64≻) -> NilClass
    def assign: (: Cv::Cuda::GpuMatND) -> Cv::Cuda::GpuMatND
           | (: Cv::Cuda::GpuMatND) -> Cv::Cuda::GpuMatND
    def call: (ranges: Std::Vector≺cv꞉꞉Range≻) -> Cv::Cuda::GpuMatND
         | (idx: Std::Vector≺int≻, row_range: Cv::Range, col_range: Cv::Range) -> Cv::Cuda::GpuMat
    def clone: () -> Cv::Cuda::GpuMatND
          | (stream: Cv::Cuda::Stream) -> Cv::Cuda::GpuMatND
    def continuous?: () -> TrueClass
    def create: (size: Std::Vector≺int≻, type: Integer) -> NilClass
    def create_gpu_mat_header: () -> Cv::Cuda::GpuMat
                          | (idx: Std::Vector≺int≻, row_range: Cv::Range, col_range: Cv::Range) -> Cv::Cuda::GpuMat
    def download: (dst: Cv::OutputArray) -> NilClass
             | (dst: Cv::OutputArray, stream: Cv::Cuda::Stream) -> NilClass
    def elem_size: () -> Integer
    def elem_size1: () -> Integer
    def empty?: () -> TrueClass
    def external?: () -> TrueClass
    def initialize_copy: (: Cv::Cuda::GpuMatND) -> NilClass
    def release: () -> NilClass
    def submatrix?: () -> TrueClass
    def swap: (m: Cv::Cuda::GpuMatND) -> NilClass
    def to_gpu_mat: () -> Cv::Cuda::GpuMat
    def total: () -> Integer
    def total_mem_size: () -> Integer
    def type: () -> Integer
    def upload: (src: Cv::InputArray) -> NilClass
           | (src: Cv::InputArray, stream: Cv::Cuda::Stream) -> NilClass
  end
end
