module Cv::Dnn
  class BatchNormLayerInt8
    attr_accessor input_sc: Float
    attr_accessor input_zp: Integer
    attr_accessor output_sc: Float
    attr_accessor output_zp: Integer

    def initialize: () -> NilClass
  end
end
