module Cv::Dnn
  class PoolingLayer
    attr_accessor ave_pool_padded_area: TrueClass
    attr_accessor ceil_mode: TrueClass
    attr_accessor compute_max_idx: TrueClass
    attr_accessor global_pooling: TrueClass
    attr_accessor is_global_pooling: Std::Vector≺bool≻
    attr_accessor kernel_size: Std::Vector≺unsigned Int64≻
    attr_accessor pad_mode: String
    attr_accessor pads_begin: Std::Vector≺unsigned Int64≻
    attr_accessor pads_end: Std::Vector≺unsigned Int64≻
    attr_accessor pooled_size: Cv::Size2i
    attr_accessor ps_roi_out_channels: Integer
    attr_accessor spatial_scale: Float
    attr_accessor strides: Std::Vector≺unsigned Int64≻
    attr_accessor type: Integer

    def initialize: () -> NilClass
  end
end
