module Cvflann
  class CompositeIndexParams
    def initialize: (trees: Integer, branching: Integer, iterations: Integer, centers_init: Enum cvflann::FlannCentersInitT, cb_index: Float) -> void
  end
end
