module Cvflann
  class DynamicBitset
    def clear: () -> NilClass
    def initialize: () -> NilClass
               | (sz: Integer) -> NilClass
    def empty?: () -> TrueClass
    def reset: () -> NilClass
          | (index: Integer) -> NilClass
    def reset_block: (index: Integer) -> NilClass
    def resize: (sz: Integer) -> NilClass
    def set: (index: Integer) -> NilClass
    def size: () -> Integer
    def test: (index: Integer) -> TrueClass
  end
end
