module Cvflann
  class FlannZeroIteratorU
    def []: (: Integer) -> String
    def assign_plus: (: Integer) -> Cvflann::FlannZeroIteratorU
    def dereference: () -> String
    def increment: () -> Cvflann::FlannZeroIteratorU
              | (: Integer) -> Cvflann::FlannZeroIteratorU
  end
end
