module Cvflann
  class IndexHeader
    attr_accessor cols: Integer
    attr_accessor data_type: Enum cvflann::FlannDatatypeT
    attr_accessor index_type: Enum cvflann::FlannAlgorithmT
    attr_accessor rows: Integer

    def initialize: () -> void
  end
end
