module Cvflann
  class KMeansIndexParams
    def initialize: (branching: Integer, iterations: Integer, centers_init: Cvflann::FlannCentersInitT, cb_index: Float, trees: Integer) -> NilClass
  end
end
