module Cvflann
  class PooledAllocator
    attr_accessor used_memory: Integer
    attr_accessor wasted_memory: Integer

    def allocate_memory: (size: Integer) -> Rice::Pointer≺void≻
    def initialize: (block_size: Integer) -> NilClass
  end
end
