module Cvflann
  class StartStopTimer
    attr_accessor value: Float

    def initialize: () -> NilClass
    def reset: () -> NilClass
    def start: () -> NilClass
    def stop: () -> NilClass
  end
end
