module Cvflann
  class UntypedMatrix
    attr_accessor cols: Integer
    attr_accessor data: Rice::Pointer≺void≻
    attr_accessor rows: Integer
    attr_accessor type: Cvflann::FlannDatatypeT

    def initialize: (data_: Rice::Pointer≺void≻, rows_: Integer, cols_: Integer) -> NilClass
  end
end
