module Cv::Detail
  class CameraParams
    attr_accessor aspect: Float
    attr_accessor focal: Float
    attr_accessor ppx: Float
    attr_accessor ppy: Float
    attr_accessor r: Cv::Mat
    attr_accessor t: Cv::Mat

    def assign: (other: Cv::Detail::CameraParams) -> Cv::Detail::CameraParams
    def initialize: () -> NilClass
    def initialize_copy: (other: Cv::Detail::CameraParams) -> NilClass
    def k: () -> Cv::Mat
  end
end
