module Cv::Detail
  class ChannelsCompensator
    def apply: (index: Integer, corner: Cv::Point, image: Cv::InputOutputArray, mask: Cv::InputArray) -> NilClass
    def feed: (corners: Std::Vector≺cv꞉꞉Point_≺int≻≻, images: Std::Vector≺cv꞉꞉UMat≻, masks: Std::Vector≺pair≺cv꞉꞉UMat‚ unsigned char≻≻) -> NilClass
    def initialize: (nr_feeds: Integer) -> NilClass
    def gains: () -> Std::Vector≺cv꞉꞉Scalar_≺double≻≻
    def get_mat_gains: (umv: Std::Vector≺cv꞉꞉Mat≻) -> NilClass
    def get_nr_feeds: () -> Integer
    def get_similarity_threshold: () -> Float
    def set_mat_gains: (umv: Std::Vector≺cv꞉꞉Mat≻) -> NilClass
    def set_nr_feeds: (nr_feeds: Integer) -> NilClass
    def set_similarity_threshold: (similarity_threshold: Float) -> NilClass
  end
end
