module Cv::Detail
  class CheckContext
    attr_accessor file: String
    attr_accessor func: String
    attr_accessor line: Integer
    attr_accessor message: String
    attr_accessor p1_str: String
    attr_accessor p2_str: String
    attr_accessor test_op: Cv::Detail::TestOp

    def initialize: () -> NilClass
  end
end
