module Cv::Detail
  class CompressedRectilinearProjector
    attr_accessor a: Float
    attr_accessor b: Float

    def initialize: () -> NilClass
    def map_backward: (u: Float, v: Float, x: Float, y: Float) -> NilClass
    def map_forward: (x: Float, y: Float, u: Float, v: Float) -> NilClass
  end
end
