module Cv::Detail
  class CylindricalPortraitProjector
    def initialize: () -> void
    def map_backward: (u: Float, v: Float, x: Float, y: Float) -> void
    def map_forward: (x: Float, y: Float, u: Float, v: Float) -> void
  end
end
