module Cv::Detail
  class DpSeamFinder
    def initialize: (cost_func: Std::String) -> void
               | (cost_func: Enum cv::detail::DpSeamFinder::CostFunction) -> void
    def cost_function: () -> Enum cv::detail::DpSeamFinder::CostFunction
    def find: (src: Std::Vector≺cv꞉꞉UMat≻, corners: Std::Vector≺cv꞉꞉Point_≺int≻≻, masks: Std::Vector≺cv꞉꞉UMat≻) -> void
    def set_cost_function: (val: Std::String) -> void
                      | (val: Enum cv::detail::DpSeamFinder::CostFunction) -> void
  end
end
