module Cv::Detail
  class FeaturesMatcher
    def call: (features: Std::Vector≺cv꞉꞉detail꞉꞉ImageFeatures≻, pairwise_matches: Std::Vector≺cv꞉꞉detail꞉꞉MatchesInfo≻, mask: Cv::UMat) -> NilClass
         | (features1: Cv::Detail::ImageFeatures, features2: Cv::Detail::ImageFeatures, matches_info: Cv::Detail::MatchesInfo) -> NilClass
    def collect_garbage: () -> NilClass
    def thread_safe?: () -> TrueClass
  end
end
