module Cv::Detail
  class FeatherBlender
    def blend: (dst: Cv::InputOutputArray, dst_mask: Cv::InputOutputArray) -> NilClass
    def create_weight_maps: (masks: Std::Vector≺cv꞉꞉UMat≻, corners: Std::Vector≺cv꞉꞉Point_≺int≻≻, weight_maps: Std::Vector≺cv꞉꞉UMat≻) -> Cv::Rect
    def feed: (img: Cv::InputArray, mask: Cv::InputArray, tl: Cv::Point) -> NilClass
    def initialize: (sharpness: Float) -> NilClass
    def prepare: (dst_roi: Cv::Rect) -> NilClass
    def set_sharpness: (val: Float) -> NilClass
    def sharpness: () -> Float
  end
end
