module Cv::Detail
  class GraphCutSeamFinderGpu
    def find: (src: Std::Vector≺cv꞉꞉UMat≻, corners: Std::Vector≺cv꞉꞉Point_≺int≻≻, masks: Std::Vector≺cv꞉꞉UMat≻) -> NilClass
    def find_in_pair: (first: Integer, second: Integer, roi: Cv::Rect2i) -> NilClass
    def initialize: (cost_type: Integer, terminal_cost: Float, bad_region_penalty: Float) -> NilClass
  end
end
