module Cv::Detail
  class GraphEdge
    attr_accessor from: Integer
    attr_accessor to: Integer
    attr_accessor weight: Float

    def initialize: (from: Integer, to: Integer, weight: Float) -> NilClass
    def <: (other: Cv::Detail::GraphEdge) -> TrueClass
    def >: (other: Cv::Detail::GraphEdge) -> TrueClass
  end
end
