module Cv::Detail
  class MatchesInfo
    attr_accessor confidence: Float
    attr_accessor dst_img_idx: Integer
    attr_accessor h: Cv::Mat
    attr_accessor inliers_mask: Std::Vector≺unsigned char≻
    attr_accessor matches: Std::Vector≺cv꞉꞉DMatch≻
    attr_accessor num_inliers: Integer
    attr_accessor src_img_idx: Integer

    def assign: (other: Cv::Detail::MatchesInfo) -> Cv::Detail::MatchesInfo
    def get_inliers: () -> Std::Vector≺unsigned char≻
    def get_matches: () -> Std::Vector≺cv꞉꞉DMatch≻
    def initialize: () -> NilClass
    def initialize_copy: (other: Cv::Detail::MatchesInfo) -> NilClass
  end
end
