module Cv::Detail
  class MultiBandBlender
    def blend: (dst: Cv::InputOutputArray, dst_mask: Cv::InputOutputArray) -> NilClass
    def feed: (img: Cv::InputArray, mask: Cv::InputArray, tl: Cv::Point) -> NilClass
    def initialize: (try_gpu: Integer, num_bands: Integer, weight_type: Integer) -> NilClass
    def num_bands: () -> Integer
    def prepare: (dst_roi: Cv::Rect) -> NilClass
    def set_num_bands: (val: Integer) -> NilClass
  end
end
