module Cv::Detail
  class NoExposureCompensator
    def apply: (: Integer, : Cv::Point, : Cv::InputOutputArray, arg_3: Cv::InputArray) -> NilClass
    def feed: (: Std::Vector≺cv꞉꞉Point_≺int≻≻, : Std::Vector≺cv꞉꞉UMat≻, arg_2: Std::Vector≺pair≺cv꞉꞉UMat‚ unsigned char≻≻) -> NilClass
    def get_mat_gains: (umv: Std::Vector≺cv꞉꞉Mat≻) -> NilClass
    def initialize: () -> NilClass
    def set_mat_gains: (umv: Std::Vector≺cv꞉꞉Mat≻) -> NilClass
  end
end
