module Cv::Detail
  class ProjectorBase
    attr_accessor scale: Float

    def initialize: () -> NilClass
    def set_camera_params: (k: Cv::InputArray, r: Cv::InputArray, t: Cv::InputArray) -> NilClass
  end
end
