module Cv::Detail
  class VoronoiSeamFinder
    def find: (src: Std::Vector≺cv꞉꞉UMat≻, corners: Std::Vector≺cv꞉꞉Point_≺int≻≻, masks: Std::Vector≺cv꞉꞉UMat≻) -> void
         | (size: Std::Vector≺cv꞉꞉Size_≺int≻≻, corners: Std::Vector≺cv꞉꞉Point_≺int≻≻, masks: Std::Vector≺cv꞉꞉UMat≻) -> void
    def initialize: () -> void
  end
end
