module Cv::Cuda::DeviceInfo
  class ComputeMode
    def initialize: () -> NilClass
    def &: (arg_0: Cv::Cuda::DeviceInfo::ComputeMode) -> Integer
    def <<: (arg_0: Integer) -> Integer
    def <=>: (arg_0: Cv::Cuda::DeviceInfo::ComputeMode) -> Integer
        | (arg_0: Integer) -> Integer
    def >>: (arg_0: Integer) -> Integer
    def ^: (arg_0: Cv::Cuda::DeviceInfo::ComputeMode) -> Integer
    def coerce: (arg_0: Integer) -> Array
    def eql?: (arg_0: Integer) -> TrueClass
         | (arg_0: Cv::Cuda::DeviceInfo::ComputeMode) -> TrueClass
    def hash: () -> Integer
    def inspect: () -> String
    def to_int: () -> Integer
    def to_s: () -> String
    def |: (arg_0: Cv::Cuda::DeviceInfo::ComputeMode) -> Integer
    def ~: () -> Integer
  end
end
