module Cv::Ocl
  class Device
    def initialize: () -> NilClass
               | (d: Rice::Pointer≺void≻) -> NilClass
    def address_bits: () -> Integer
    def amd?: () -> TrueClass
    def assign: (d: Cv::Ocl::Device) -> Cv::Ocl::Device
           | (d: Cv::Ocl::Device) -> Cv::Ocl::Device
    def available?: () -> TrueClass
    def compiler_available?: () -> TrueClass
    def device_version_major: () -> Integer
    def device_version_minor: () -> Integer
    def double_fp_config: () -> Integer
    def driver_version: () -> String
    def empty?: () -> TrueClass
    def endian_little?: () -> TrueClass
    def error_correction_support?: () -> TrueClass
    def execution_capabilities: () -> Integer
    def extension_supported?: (extension_name: String) -> TrueClass
    def extensions: () -> String
    def get_impl: () -> Cv::Ocl::Device::Impl
    def global_mem_cache_line_size: () -> Integer
    def global_mem_cache_size: () -> Integer
    def global_mem_cache_type: () -> Integer
    def global_mem_size: () -> Integer
    def half_fp_config: () -> Integer
    def has_fp16?: () -> TrueClass
    def has_fp64?: () -> TrueClass
    def host_unified_memory?: () -> TrueClass
    def image_2d_max_height: () -> Integer
    def image_2d_max_width: () -> Integer
    def image_3d_max_depth: () -> Integer
    def image_3d_max_height: () -> Integer
    def image_3d_max_width: () -> Integer
    def image_base_address_alignment: () -> Integer
    def image_from_buffer_support?: () -> TrueClass
    def image_max_array_size: () -> Integer
    def image_max_buffer_size: () -> Integer
    def image_pitch_alignment: () -> Integer
    def image_support?: () -> TrueClass
    def initialize_copy: (d: Cv::Ocl::Device) -> NilClass
    def intel?: () -> TrueClass
    def intel_subgroups_support?: () -> TrueClass
    def linker_available?: () -> TrueClass
    def local_mem_size: () -> Integer
    def local_mem_type: () -> Integer
    def max_clock_frequency: () -> Integer
    def max_compute_units: () -> Integer
    def max_constant_args: () -> Integer
    def max_constant_buffer_size: () -> Integer
    def max_mem_alloc_size: () -> Integer
    def max_parameter_size: () -> Integer
    def max_read_image_args: () -> Integer
    def max_samplers: () -> Integer
    def max_work_group_size: () -> Integer
    def max_work_item_dims: () -> Integer
    def max_work_item_sizes: (arg_0: Rice::Pointer≺unsigned Int64≻) -> NilClass
    def max_write_image_args: () -> Integer
    def mem_base_addr_align: () -> Integer
    def n_vidia?: () -> TrueClass
    def name: () -> String
    def native_vector_width_char: () -> Integer
    def native_vector_width_double: () -> Integer
    def native_vector_width_float: () -> Integer
    def native_vector_width_half: () -> Integer
    def native_vector_width_int: () -> Integer
    def native_vector_width_long: () -> Integer
    def native_vector_width_short: () -> Integer
    def open_cl_c_version: () -> String
    def open_cl_version: () -> String
    def preferred_vector_width_char: () -> Integer
    def preferred_vector_width_double: () -> Integer
    def preferred_vector_width_float: () -> Integer
    def preferred_vector_width_half: () -> Integer
    def preferred_vector_width_int: () -> Integer
    def preferred_vector_width_long: () -> Integer
    def preferred_vector_width_short: () -> Integer
    def printf_buffer_size: () -> Integer
    def profiling_timer_resolution: () -> Integer
    def ptr: () -> Rice::Pointer≺void≻
    def set: (d: Rice::Pointer≺void≻) -> NilClass
    def single_fp_config: () -> Integer
    def type: () -> Integer
    def vendor_id: () -> Integer
    def vendor_name: () -> String
    def version: () -> String
  end
end
