module Cv::Ocl
  class Kernel
    def initialize: () -> NilClass
               | (kname: String, prog: Cv::Ocl::Program) -> NilClass
               | (kname: String, prog: Cv::Ocl::ProgramSource, buildopts: String, errmsg: Rice::Pointer≺string≻) -> NilClass
    def assign: (k: Cv::Ocl::Kernel) -> Cv::Ocl::Kernel
           | (k: Cv::Ocl::Kernel) -> Cv::Ocl::Kernel
    def compile_work_group_size: (wsz: Rice::Pointer≺unsigned Int64≻) -> TrueClass
    def create: (kname: String, prog: Cv::Ocl::Program) -> TrueClass
           | (kname: String, prog: Cv::Ocl::ProgramSource, buildopts: String, errmsg: Rice::Pointer≺string≻) -> TrueClass
    def empty?: () -> TrueClass
    def initialize_copy: (k: Cv::Ocl::Kernel) -> NilClass
    def local_mem_size: () -> Integer
    def prefered_work_group_size_multiple: () -> Integer
    def ptr: () -> Rice::Pointer≺void≻
    def run: (dims: Integer, globalsize: Rice::Pointer≺unsigned Int64≻, localsize: Rice::Pointer≺unsigned Int64≻, sync: TrueClass, q: Cv::Ocl::Queue) -> TrueClass
    def run_profiling: (dims: Integer, globalsize: Rice::Pointer≺unsigned Int64≻, localsize: Rice::Pointer≺unsigned Int64≻, q: Cv::Ocl::Queue) -> Integer
    def run_task: (sync: TrueClass, q: Cv::Ocl::Queue) -> TrueClass
    def set: (i: Integer, image_2d: Cv::Ocl::Image2D) -> Integer
        | (i: Integer, arg: Cv::Ocl::KernelArg) -> Integer
        | (i: Integer, m: Cv::UMat) -> Integer
        | (i: Integer, value: Rice::Pointer≺void≻, sz: Integer) -> Integer
    def work_group_size: () -> Integer
  end
end
