module Cv::Ocl
  class PlatformInfo
    def initialize: () -> NilClass
               | (id: Rice::Pointer≺void≻) -> NilClass
    def assign: (i: Cv::Ocl::PlatformInfo) -> Cv::Ocl::PlatformInfo
           | (i: Cv::Ocl::PlatformInfo) -> Cv::Ocl::PlatformInfo
    def device_number: () -> Integer
    def empty?: () -> TrueClass
    def get_device: (device: Cv::Ocl::Device, d: Integer) -> NilClass
    def initialize_copy: (i: Cv::Ocl::PlatformInfo) -> NilClass
    def name: () -> String
    def vendor: () -> String
    def version: () -> String
  end
end
