module Cv::Ocl
  class PlatformInfo
    def initialize: () -> void
               | (id: Rice::Buffer≺void∗≻) -> void
    def assign: (i: Cv::ocl::PlatformInfo) -> Cv::ocl::PlatformInfo
           | (i: Cv::ocl::PlatformInfo) -> Cv::ocl::PlatformInfo
    def device_number: () -> Integer
    def empty?: () -> bool
    def get_device: (device: Cv::ocl::Device, d: Integer) -> void
    def initialize_copy: (i: Cv::ocl::PlatformInfo) -> void
    def name: () -> Std::String
    def vendor: () -> Std::String
    def version: () -> Std::String
  end
end
