module Cv::Ocl
  class Platform
    def initialize: () -> NilClass
    def assign: (p: Cv::Ocl::Platform) -> Cv::Ocl::Platform
           | (p: Cv::Ocl::Platform) -> Cv::Ocl::Platform
    def empty?: () -> TrueClass
    def initialize_copy: (p: Cv::Ocl::Platform) -> NilClass
    def ptr: () -> Rice::Pointer≺void≻
  end
end
