module Cv::Ocl
  class Program
    def initialize: () -> void
               | (src: Cv::ocl::ProgramSource, buildflags: Std::String, errmsg: Std::String) -> void
    def create?: (src: Cv::ocl::ProgramSource, buildflags: Std::String, errmsg: Std::String) -> bool
    def empty?: () -> bool
    def get_binary: (binary: Std::Vector≺char≻) -> void
    def initialize_copy: (prog: Cv::ocl::Program) -> void
    def ptr: () -> Rice::Buffer≺void∗≻
  end
end
