module Cv::Ocl
  class ProgramSource
    def assign: (prog: Cv::Ocl::ProgramSource) -> Cv::Ocl::ProgramSource
           | (prog: Cv::Ocl::ProgramSource) -> Cv::Ocl::ProgramSource
    def initialize: () -> NilClass
               | (prog: String) -> NilClass
               | (prog: String) -> NilClass
               | (module: String, name: String, code_str: String, code_hash: String) -> NilClass
    def hash: () -> Integer
    def empty?: () -> TrueClass
    def initialize_copy: (prog: Cv::Ocl::ProgramSource) -> NilClass
    def source: () -> String
  end
end
