module Cv::Utils
  class FunctionParams
    attr_accessor lambda: Integer
    attr_accessor sigma: Float

    def initialize: () -> NilClass
    def set_lambda: (value: Integer) -> Cv::Utils::FunctionParams
    def set_sigma: (value: Float) -> Cv::Utils::FunctionParams
  end
end
