// Generated by ruby-bindgen (1.0.0)

#include <opencv2/flann/simplex_downhill.h>
#include "simplex_downhill-rb.hpp"

using namespace Rice;

void Init_Flann_SimplexDownhill()
{
  Module rb_mCvflann = define_module("Cvflann");
}
