module Cv::Flann
  class CompositeIndexParams
    def initialize: (trees: Integer, branching: Integer, iterations: Integer, centers_init: Cvflann::FlannCentersInitT, cb_index: Float) -> NilClass
  end
end
