module Cv::Flann
  class HierarchicalClusteringIndexParams
    def initialize: (branching: Integer, centers_init: Cvflann::FlannCentersInitT, trees: Integer, leaf_size: Integer) -> NilClass
  end
end
