module Cv::Flann
  class Index
    def build: (features: Cv::InputArray, params: Cv::Flann::IndexParams, dist_type: Cvflann::FlannDistanceT) -> NilClass
    def get_algorithm: () -> Cvflann::FlannAlgorithmT
    def get_distance: () -> Cvflann::FlannDistanceT
    def initialize: () -> NilClass
               | (features: Cv::InputArray, params: Cv::Flann::IndexParams, dist_type: Cvflann::FlannDistanceT) -> NilClass
    def load?: (features: Cv::InputArray, filename: String) -> TrueClass
    def release: () -> NilClass
    def save: (filename: String) -> NilClass
  end
end
