module Cv::Flann
  class SearchParams
    def initialize: (checks: Integer, eps: Float, sorted: TrueClass) -> NilClass
               | (checks: Integer, eps: Float, sorted: TrueClass, explore_all_trees: TrueClass) -> NilClass
  end
end
