module Cv::QRCodeEncoder
  class Params
    attr_accessor correction_level: Cv::QRCodeEncoder::CorrectionLevel
    attr_accessor mode: Cv::QRCodeEncoder::EncodeMode
    attr_accessor structure_number: Integer
    attr_accessor version: Integer

    def initialize: () -> NilClass
  end
end
