module Cv::QuatEnum
  class EulerAnglesType
    def initialize: () -> NilClass
    def &: (arg_0: Cv::QuatEnum::EulerAnglesType) -> Integer
    def <<: (arg_0: Integer) -> Integer
    def <=>: (arg_0: Cv::QuatEnum::EulerAnglesType) -> Integer
        | (arg_0: Integer) -> Integer
    def >>: (arg_0: Integer) -> Integer
    def ^: (arg_0: Cv::QuatEnum::EulerAnglesType) -> Integer
    def coerce: (arg_0: Integer) -> Array
    def eql?: (arg_0: Integer) -> TrueClass
         | (arg_0: Cv::QuatEnum::EulerAnglesType) -> TrueClass
    def hash: () -> Integer
    def inspect: () -> String
    def to_int: () -> Integer
    def to_s: () -> String
    def |: (arg_0: Cv::QuatEnum::EulerAnglesType) -> Integer
    def ~: () -> Integer
  end
end
