module Cv::Ocl::Internal
  class ProgramEntry
    attr_accessor module: String
    attr_accessor name: String
    attr_accessor p_program_source: Cv::Ocl::ProgramSource
    attr_accessor program_code: String
    attr_accessor program_hash: String

    def initialize: () -> NilClass
    def to_program_source: () -> Cv::Ocl::ProgramSource
  end
end
