module Cv
  class Affine3f
    attr_accessor matrix: Cv::Matx44f

    def *: (arg_0: Cv::Vec3f) -> Cv::Vec3f
      | (arg_0: Cv::Vec3f) -> Cv::Vec3f
    def initialize: () -> NilClass
               | (affine: Cv::Matx44f) -> NilClass
               | (vals: Rice::Pointer≺float≻) -> NilClass
               | (rvec: Cv::Vec3f, t: Cv::Vec3f) -> NilClass
               | (data: Cv::Mat, t: Cv::Vec3f) -> NilClass
               | (r: Cv::Matx33f, t: Cv::Vec3f) -> NilClass
    def concatenate: (affine: Cv::Affine3f) -> Cv::Affine3f
    def inv: (method: Integer) -> Cv::Affine3f
    def linear: () -> Cv::Matx33f
           | (l: Cv::Matx33f) -> NilClass
    def rotate: (r: Cv::Matx33f) -> Cv::Affine3f
           | (rvec: Cv::Vec3f) -> Cv::Affine3f
    def rotation: () -> Cv::Matx33f
             | (rvec: Cv::Vec3f) -> NilClass
             | (r: Cv::Matx33f) -> NilClass
             | (data: Cv::Mat) -> NilClass
    def rvec: () -> Cv::Vec3f
    def translate: (t: Cv::Vec3f) -> Cv::Affine3f
    def translation: () -> Cv::Vec3f
                | (t: Cv::Vec3f) -> NilClass
  end
end
