module Cv
  class Affine3d
    attr_accessor matrix: Cv::Matx44d

    def *: (arg_0: Cv::Vec3d) -> Cv::Vec3d
      | (arg_0: Cv::Vec3d) -> Cv::Vec3d
    def initialize: () -> NilClass
               | (affine: Cv::Matx44d) -> NilClass
               | (vals: Rice::Pointer≺double≻) -> NilClass
               | (rvec: Cv::Vec3d, t: Cv::Vec3d) -> NilClass
               | (data: Cv::Mat, t: Cv::Vec3d) -> NilClass
               | (r: Cv::Matx33d, t: Cv::Vec3d) -> NilClass
    def concatenate: (affine: Cv::Affine3d) -> Cv::Affine3d
    def inv: (method: Integer) -> Cv::Affine3d
    def linear: () -> Cv::Matx33d
           | (l: Cv::Matx33d) -> NilClass
    def rotate: (r: Cv::Matx33d) -> Cv::Affine3d
           | (rvec: Cv::Vec3d) -> Cv::Affine3d
    def rotation: () -> Cv::Matx33d
             | (rvec: Cv::Vec3d) -> NilClass
             | (r: Cv::Matx33d) -> NilClass
             | (data: Cv::Mat) -> NilClass
    def rvec: () -> Cv::Vec3d
    def translate: (t: Cv::Vec3d) -> Cv::Affine3d
    def translation: () -> Cv::Vec3d
                | (t: Cv::Vec3d) -> NilClass
  end
end
