module Cv
  class AffineFeature
    def get_default_name: () -> String
    def get_view_params: (tilts: Std::Vector≺float≻, rolls: Std::Vector≺float≻) -> NilClass
    def set_view_params: (tilts: Std::Vector≺float≻, rolls: Std::Vector≺float≻) -> NilClass
  end
end
