module Cv
  class AgastFeatureDetector
    def get_default_name: () -> String
    def get_nonmax_suppression?: () -> TrueClass
    def get_threshold: () -> Integer
    def get_type: () -> Cv::AgastFeatureDetector::DetectorType
    def set_nonmax_suppression: (f: TrueClass) -> NilClass
    def set_threshold: (threshold: Integer) -> NilClass
    def set_type: (type: Cv::AgastFeatureDetector::DetectorType) -> NilClass
  end
end
