module Cv
  class AKAZE
    def get_default_name: () -> String
    def get_descriptor_channels: () -> Integer
    def get_descriptor_size: () -> Integer
    def get_descriptor_type: () -> Cv::AKAZE::DescriptorType
    def get_diffusivity: () -> Cv::KAZE::DiffusivityType
    def get_max_points: () -> Integer
    def get_n_octave_layers: () -> Integer
    def get_n_octaves: () -> Integer
    def get_threshold: () -> Float
    def set_descriptor_channels: (dch: Integer) -> NilClass
    def set_descriptor_size: (dsize: Integer) -> NilClass
    def set_descriptor_type: (dtype: Cv::AKAZE::DescriptorType) -> NilClass
    def set_diffusivity: (diff: Cv::KAZE::DiffusivityType) -> NilClass
    def set_max_points: (max_points: Integer) -> NilClass
    def set_n_octave_layers: (octave_layers: Integer) -> NilClass
    def set_n_octaves: (octaves: Integer) -> NilClass
    def set_threshold: (threshold: Float) -> NilClass
  end
end
