module Cv
  class Algorithm
    def initialize: () -> NilClass
    def clear: () -> NilClass
    def empty?: () -> TrueClass
    def get_default_name: () -> String
    def read: (fn: Cv::FileNode) -> NilClass
    def save: (filename: String) -> NilClass
    def write: (fs: Cv::FileStorage) -> NilClass
          | (fs: Cv::FileStorage, name: String) -> NilClass
          | (fs: Cv::Ptr≺cv꞉꞉FileStorage≻, name: String) -> NilClass
  end
end
