module Cv
  class Algorithm
    def initialize: () -> void
    def clear: () -> void
    def empty?: () -> bool
    def get_default_name: () -> Std::String
    def read: (fn: Cv::FileNode) -> void
    def save: (filename: Std::String) -> void
    def write: (fs: Cv::FileStorage) -> void
          | (fs: Cv::Ptr≺cv꞉꞉FileStorage≻, name: Std::String) -> void
          | (fs: Cv::FileStorage, name: Std::String) -> void
  end
end
