module Cv
  class AlignMTB
    def calculate_shift: (img0: Cv::InputArray, img1: Cv::InputArray) -> Cv::Point
    def compute_bitmaps: (img: Cv::InputArray, tb: Cv::OutputArray, eb: Cv::OutputArray) -> NilClass
    def get_cut?: () -> TrueClass
    def get_exclude_range: () -> Integer
    def get_max_bits: () -> Integer
    def process: (src: Cv::InputArray, dst: Std::Vector≺cv꞉꞉Mat≻) -> NilClass
            | (src: Cv::InputArray, dst: Std::Vector≺cv꞉꞉Mat≻, times: Cv::InputArray, response: Cv::InputArray) -> NilClass
    def set_cut: (value: TrueClass) -> NilClass
    def set_exclude_range: (exclude_range: Integer) -> NilClass
    def set_max_bits: (max_bits: Integer) -> NilClass
    def shift_mat: (src: Cv::InputArray, dst: Cv::OutputArray, shift: Cv::Point) -> NilClass
  end
end
