module Cv
  class AsyncArray
    def _get_impl: () -> Rice::Pointer≺void≻
    def assign: (o: Cv::AsyncArray) -> Cv::AsyncArray
           | (o: Cv::AsyncArray) -> Cv::AsyncArray
    def get: (dst: Cv::OutputArray) -> NilClass
        | (dst: Cv::OutputArray, timeout_ns: Integer) -> TrueClass
        | (dst: Cv::OutputArray, timeout_ns: Float) -> TrueClass
    def initialize: () -> NilClass
    def initialize_copy: (o: Cv::AsyncArray) -> NilClass
    def release: () -> NilClass
    def valid?: () -> TrueClass
    def wait_for: (timeout_ns: Float) -> TrueClass
             | (timeout_ns: Integer) -> TrueClass
  end
end
