module Cv
  class BOWImgDescriptorExtractor
    def initialize: (dmatcher: Cv::Ptr≺cv꞉꞉DescriptorMatcher≻) -> NilClass
               | (dextractor: Cv::Ptr≺cv꞉꞉Feature2D≻, dmatcher: Cv::Ptr≺cv꞉꞉DescriptorMatcher≻) -> NilClass
    def compute: (keypoint_descriptors: Cv::InputArray, img_descriptor: Cv::OutputArray, point_idxs_of_clusters: Std::Vector≺vector≺int≻≻) -> NilClass
            | (image: Cv::InputArray, keypoints: Std::Vector≺cv꞉꞉KeyPoint≻, img_descriptor: Cv::OutputArray, point_idxs_of_clusters: Std::Vector≺vector≺int≻≻, descriptors: Cv::Mat) -> NilClass
    def compute2: (image: Cv::Mat, keypoints: Std::Vector≺cv꞉꞉KeyPoint≻, img_descriptor: Cv::Mat) -> NilClass
    def descriptor_size: () -> Integer
    def descriptor_type: () -> Integer
    def get_vocabulary: () -> Cv::Mat
    def set_vocabulary: (vocabulary: Cv::Mat) -> NilClass
  end
end
