module Cv
  class BRISK
    def get_default_name: () -> Std::String
    def get_octaves: () -> Integer
    def get_pattern_scale: () -> Float
    def get_threshold: () -> Integer
    def set_octaves: (octaves: Integer) -> void
    def set_pattern_scale: (pattern_scale: Float) -> void
    def set_threshold: (threshold: Integer) -> void
  end
end
