module Cv
  class CalibrateDebevec
    def get_lambda: () -> Float
    def get_random?: () -> bool
    def get_samples: () -> Integer
    def set_lambda: (lambda: Float) -> void
    def set_random: (random: bool) -> void
    def set_samples: (samples: Integer) -> void
  end
end
