module Cv
  class CLAHE
    def apply: (src: Cv::debug_build_guard::InputArray, dst: Cv::debug_build_guard::OutputArray) -> void
    def collect_garbage: () -> void
    def get_clip_limit: () -> Float
    def get_tiles_grid_size: () -> Cv::Size_≺int≻
    def set_clip_limit: (clip_limit: Float) -> void
    def set_tiles_grid_size: (tile_grid_size: Cv::Size_≺int≻) -> void
  end
end
