module Cv
  class CommandLineParser
    def about: (message: String) -> NilClass
    def assign: (parser: Cv::CommandLineParser) -> Cv::CommandLineParser
    def check?: () -> TrueClass
    def initialize: (argc: Integer, argv: Rice::Pointer≺char∗≻, keys: String) -> NilClass
    def get_path_to_application: () -> String
    def has: (name: String) -> TrueClass
    def initialize_copy: (parser: Cv::CommandLineParser) -> NilClass
    def print_errors: () -> NilClass
    def print_message: () -> NilClass
  end
end
