module Cv
  class Complexf
    attr_accessor im: Float
    attr_accessor re: Float

    def conj: () -> Cv::Complexf
    def initialize: () -> NilClass
               | (_re: Float, _im: Float) -> NilClass
  end
end
