module Cv
  class DenseOpticalFlow
    def calc: (i0: Cv::debug_build_guard::InputArray, i1: Cv::debug_build_guard::InputArray, flow: Cv::debug_build_guard::InputOutputArray) -> void
    def collect_garbage: () -> void
  end
end
