module Cv
  class DetectionBasedTracker
    def initialize: (main_detector: Cv::Ptr≺cv꞉꞉DetectionBasedTracker꞉꞉IDetector≻, tracking_detector: Cv::Ptr≺cv꞉꞉DetectionBasedTracker꞉꞉IDetector≻, params: Cv::DetectionBasedTracker::Parameters) -> void
    def add_object: (location: Cv::Rect_≺int≻) -> Integer
    def get_objects: (result: Std::Vector≺cv꞉꞉Rect_≺int≻≻) -> void
                | (result: Std::Vector≺pair≺cv꞉꞉Rect_≺int≻‚ int≻≻) -> void
                | (result: Std::Vector≺cv꞉꞉DetectionBasedTracker꞉꞉ExtObject≻) -> void
    def get_parameters: () -> Cv::DetectionBasedTracker::Parameters
    def process: (image_gray: Cv::Mat) -> void
    def reset_tracking: () -> void
    def run?: () -> bool
    def set_parameters?: (params: Cv::DetectionBasedTracker::Parameters) -> bool
    def stop: () -> void
  end
end
