module Cv
  class DMatch
    attr_accessor distance: Float
    attr_accessor img_idx: Integer
    attr_accessor query_idx: Integer
    attr_accessor train_idx: Integer

    def initialize: () -> NilClass
               | (_query_idx: Integer, _train_idx: Integer, _distance: Float) -> NilClass
               | (_query_idx: Integer, _train_idx: Integer, _img_idx: Integer, _distance: Float) -> NilClass
    def <: (m: Cv::DMatch) -> TrueClass
  end
end
