module Cv
  class Exception
    attr_accessor code: Integer
    attr_accessor err: String
    attr_accessor file: String
    attr_accessor func: String
    attr_accessor line: Integer
    attr_accessor msg: String

    def _dump_data: () -> Hash
    def format_message: () -> NilClass
    def initialize: () -> NilClass
               | (_code: Integer, _err: String, _func: String, _file: String, _line: Integer) -> NilClass
    def message: () -> String
  end
end
