module Cv
  class FaceRecognizerSF
    def align_crop: (src_img: Cv::InputArray, face_box: Cv::InputArray, aligned_img: Cv::OutputArray) -> NilClass
    def feature: (aligned_img: Cv::InputArray, face_feature: Cv::OutputArray) -> NilClass
    def match: (face_feature1: Cv::InputArray, face_feature2: Cv::InputArray, dis_type: Integer) -> Float
  end
end
