module Cv
  class Feature2D
    def initialize: () -> NilClass
    def compute: (images: Cv::InputArray, keypoints: Std::Vector≺vector≺cv꞉꞉KeyPoint≻≻, descriptors: Cv::OutputArray) -> NilClass
            | (image: Cv::InputArray, keypoints: Std::Vector≺cv꞉꞉KeyPoint≻, descriptors: Cv::OutputArray) -> NilClass
    def default_norm: () -> Integer
    def descriptor_size: () -> Integer
    def descriptor_type: () -> Integer
    def detect: (image: Cv::InputArray, keypoints: Std::Vector≺cv꞉꞉KeyPoint≻, mask: Cv::InputArray) -> NilClass
           | (images: Cv::InputArray, keypoints: Std::Vector≺vector≺cv꞉꞉KeyPoint≻≻, masks: Cv::InputArray) -> NilClass
    def detect_and_compute: (image: Cv::InputArray, mask: Cv::InputArray, keypoints: Std::Vector≺cv꞉꞉KeyPoint≻, descriptors: Cv::OutputArray, use_provided_keypoints: TrueClass) -> NilClass
    def empty?: () -> TrueClass
    def get_default_name: () -> String
    def read: (file_name: String) -> NilClass
         | (arg_0: Cv::FileNode) -> NilClass
    def write: (arg_0: Cv::FileStorage) -> NilClass
          | (file_name: String) -> NilClass
          | (fs: Cv::FileStorage, name: String) -> NilClass
          | (fs: Cv::Ptr≺cv꞉꞉FileStorage≻, name: String) -> NilClass
  end
end
