module Cv
  class FileNodeIterator
    def !=: (arg_0: Cv::FileNodeIterator) -> TrueClass
    def initialize: () -> NilClass
               | (node: Cv::FileNode, seek_end: TrueClass) -> NilClass
    def -: (arg_0: Cv::FileNodeIterator) -> Integer
    def <: (arg_0: Cv::FileNodeIterator) -> TrueClass
    def ==: (arg_0: Cv::FileNodeIterator) -> TrueClass
    def assign_plus: (ofs: Integer) -> Cv::FileNodeIterator
    def dereference: () -> Cv::FileNode
    def assign: (it: Cv::FileNodeIterator) -> Cv::FileNodeIterator
    def equal_to?: (it: Cv::FileNodeIterator) -> TrueClass
    def increment: () -> Cv::FileNodeIterator
              | (: Integer) -> Cv::FileNodeIterator
    def initialize_copy: (it: Cv::FileNodeIterator) -> NilClass
    def read_raw: (fmt: String, vec: Rice::Pointer≺void≻, len: Integer) -> Cv::FileNodeIterator
    def remaining: () -> Integer
  end
end
