module Cv
  class FlannBasedMatcher
    def add: (descriptors: Cv::InputArray) -> NilClass
    def clear: () -> NilClass
    def clone: (empty_train_data: TrueClass) -> Cv::Ptr≺cv꞉꞉DescriptorMatcher≻
    def initialize: (index_params: Cv::Ptr≺cv꞉꞉flann꞉꞉IndexParams≻, search_params: Cv::Ptr≺cv꞉꞉flann꞉꞉SearchParams≻) -> NilClass
    def mask_supported?: () -> TrueClass
    def read: (arg_0: Cv::FileNode) -> NilClass
    def train: () -> NilClass
    def write: (arg_0: Cv::FileStorage) -> NilClass
  end
end
