module Cv
  class GeneralizedHoughBallard
    def get_levels: () -> Integer
    def get_votes_threshold: () -> Integer
    def set_levels: (levels: Integer) -> NilClass
    def set_votes_threshold: (votes_threshold: Integer) -> NilClass
  end
end
