module Cv
  class HOGDescriptor
    attr_accessor block_size: Cv::Size2i
    attr_accessor block_stride: Cv::Size2i
    attr_accessor cell_size: Cv::Size2i
    attr_accessor deriv_aperture: Integer
    attr_accessor free_coef: Float
    attr_accessor gamma_correction: TrueClass
    attr_accessor histogram_norm_type: Cv::HOGDescriptor::HistogramNormType
    attr_accessor l2_hys_threshold: Float
    attr_accessor nbins: Integer
    attr_accessor nlevels: Integer
    attr_accessor ocl_svm_detector: Cv::UMat
    attr_accessor signed_gradient: TrueClass
    attr_accessor svm_detector: Std::Vector≺float≻
    attr_accessor win_sigma: Float
    attr_accessor win_size: Cv::Size2i

    def check_detector_size?: () -> TrueClass
    def initialize: () -> NilClass
               | (filename: String) -> NilClass
               | (_win_size: Cv::Size2i, _block_size: Cv::Size2i, _block_stride: Cv::Size2i, _cell_size: Cv::Size2i, _nbins: Integer, _deriv_aperture: Integer, _win_sigma: Float, _histogram_norm_type: Cv::HOGDescriptor::HistogramNormType, _l2_hys_threshold: Float, _gamma_correction: TrueClass, _nlevels: Integer, _signed_gradient: TrueClass) -> NilClass
    def compute: (img: Cv::InputArray, descriptors: Std::Vector≺float≻, win_stride: Cv::Size2i, padding: Cv::Size2i, locations: Std::Vector≺cv꞉꞉Point_≺int≻≻) -> NilClass
    def compute_gradient: (img: Cv::InputArray, grad: Cv::InputOutputArray, angle_ofs: Cv::InputOutputArray, padding_tl: Cv::Size2i, padding_br: Cv::Size2i) -> NilClass
    def copy_to: (c: Cv::HOGDescriptor) -> NilClass
    def detect: (img: Cv::InputArray, found_locations: Std::Vector≺cv꞉꞉Point_≺int≻≻, hit_threshold: Float, win_stride: Cv::Size2i, padding: Cv::Size2i, search_locations: Std::Vector≺cv꞉꞉Point_≺int≻≻) -> NilClass
           | (img: Cv::InputArray, found_locations: Std::Vector≺cv꞉꞉Point_≺int≻≻, weights: Std::Vector≺double≻, hit_threshold: Float, win_stride: Cv::Size2i, padding: Cv::Size2i, search_locations: Std::Vector≺cv꞉꞉Point_≺int≻≻) -> NilClass
    def detect_multi_scale: (img: Cv::InputArray, found_locations: Std::Vector≺cv꞉꞉Rect_≺int≻≻, hit_threshold: Float, win_stride: Cv::Size2i, padding: Cv::Size2i, scale: Float, group_threshold: Float, use_meanshift_grouping: TrueClass) -> NilClass
                       | (img: Cv::InputArray, found_locations: Std::Vector≺cv꞉꞉Rect_≺int≻≻, found_weights: Std::Vector≺double≻, hit_threshold: Float, win_stride: Cv::Size2i, padding: Cv::Size2i, scale: Float, group_threshold: Float, use_meanshift_grouping: TrueClass) -> NilClass
    def detect_multi_scale_roi: (img: Cv::InputArray, found_locations: Std::Vector≺cv꞉꞉Rect_≺int≻≻, locations: Std::Vector≺cv꞉꞉DetectionROI≻, hit_threshold: Float, group_threshold: Integer) -> NilClass
    def detect_roi: (img: Cv::InputArray, locations: Std::Vector≺cv꞉꞉Point_≺int≻≻, found_locations: Std::Vector≺cv꞉꞉Point_≺int≻≻, confidences: Std::Vector≺double≻, hit_threshold: Float, win_stride: Cv::Size2i, padding: Cv::Size2i) -> NilClass
    def get_descriptor_size: () -> Integer
    def get_win_sigma: () -> Float
    def group_rectangles: (rect_list: Std::Vector≺cv꞉꞉Rect_≺int≻≻, weights: Std::Vector≺double≻, group_threshold: Integer, eps: Float) -> NilClass
    def initialize_copy: (d: Cv::HOGDescriptor) -> NilClass
    def load: (filename: String, objname: String) -> TrueClass
    def read: (fn: Cv::FileNode) -> TrueClass
    def save: (filename: String, objname: String) -> NilClass
    def set_svm_detector: (svmdetector: Cv::InputArray) -> NilClass
    def write: (fs: Cv::FileStorage, objname: String) -> NilClass
  end
end
