module Cv
  class InputOutputArray
    def initialize: () -> NilClass
               | (m: Cv::UMat) -> NilClass
               | (m: Cv::Mat) -> NilClass
               | (vec: Std::Vector≺cv꞉꞉Mat≻) -> NilClass
               | (d_mat: Cv::Cuda::GpuMat) -> NilClass
               | (buf: Cv::Ogl::Buffer) -> NilClass
               | (cuda_mem: Cv::Cuda::HostMem) -> NilClass
               | (m: Cv::UMat) -> NilClass
               | (vec: Std::Vector≺cv꞉꞉UMat≻) -> NilClass
               | (m: Cv::Mat) -> NilClass
               | (vec: Std::Vector≺cv꞉꞉Mat≻) -> NilClass
               | (d_mat: Cv::Cuda::GpuMat) -> NilClass
               | (d_mat: Std::Vector≺cv꞉꞉cuda꞉꞉GpuMat≻) -> NilClass
               | (buf: Cv::Ogl::Buffer) -> NilClass
               | (cuda_mem: Cv::Cuda::HostMem) -> NilClass
               | (vec: Std::Vector≺cv꞉꞉UMat≻) -> NilClass
               | (_flags: Integer, _obj: Rice::Pointer≺void≻) -> NilClass
  end
end
