module Cv
  class KeyPoint
    attr_accessor angle: Float
    attr_accessor class_id: Integer
    attr_accessor octave: Integer
    attr_accessor pt: Cv::Point2f
    attr_accessor response: Float
    attr_accessor size: Float

    def initialize: () -> NilClass
               | (pt: Cv::Point2f, size: Float, angle: Float, response: Float, octave: Integer, class_id: Integer) -> NilClass
               | (x: Float, y: Float, size: Float, angle: Float, response: Float, octave: Integer, class_id: Integer) -> NilClass
    def hash: () -> Integer
  end
end
