module Cv
  class LDA
    def compute: (src: Cv::debug_build_guard::InputArray, labels: Cv::debug_build_guard::InputArray) -> void
    def eigenvalues: () -> Cv::Mat
    def initialize: (num_components: Integer) -> void
               | (src: Cv::debug_build_guard::InputArray, labels: Cv::debug_build_guard::InputArray, num_components: Integer) -> void
    def eigenvectors: () -> Cv::Mat
    def load: (node: Cv::FileStorage) -> void
         | (filename: Std::String) -> void
    def project: (src: Cv::debug_build_guard::InputArray) -> Cv::Mat
    def reconstruct: (src: Cv::debug_build_guard::InputArray) -> Cv::Mat
    def save: (fs: Cv::FileStorage) -> void
         | (filename: Std::String) -> void
  end
end
