module Cv
  class LDA
    def compute: (src: Cv::InputArray, labels: Cv::InputArray) -> NilClass
    def eigenvalues: () -> Cv::Mat
    def initialize: (num_components: Integer) -> NilClass
               | (src: Cv::InputArray, labels: Cv::InputArray, num_components: Integer) -> NilClass
    def eigenvectors: () -> Cv::Mat
    def load: (node: Cv::FileStorage) -> NilClass
         | (filename: String) -> NilClass
    def project: (src: Cv::InputArray) -> Cv::Mat
    def reconstruct: (src: Cv::InputArray) -> Cv::Mat
    def save: (fs: Cv::FileStorage) -> NilClass
         | (filename: String) -> NilClass
  end
end
