module Cv
  class Mat1d
    def []: (roi: Cv::Rect_≺int≻) -> Cv::Mat_≺double≻
       | (ranges: Cv::Range) -> Cv::Mat_≺double≻
       | (ranges: Std::Vector≺cv꞉꞉Range≻) -> Cv::Mat_≺double≻
       | (idx0: Integer) -> Double
       | (pt: Cv::Point_≺int≻) -> Double
       | (row_range: Cv::Range, col_range: Cv::Range) -> Cv::Mat_≺double≻
       | (row: Integer, col: Integer) -> Double
       | (idx0: Integer, idx1: Integer, idx2: Integer) -> Double
    def initialize: (e: Cv::MatExpr) -> void
               | () -> void
               | (_size: Cv::Size_≺int≻) -> void
               | (m: Cv::Mat) -> void
               | (e: Cv::MatExpr) -> void
               | (m: Cv::Mat) -> void
               | (pt: Cv::Point3_≺double≻, copy_data: bool) -> void
               | (_size: Cv::Size_≺int≻, value: Double) -> void
               | (pt: Cv::Point_≺double≻, copy_data: bool) -> void
               | (vec: Std::Vector≺double≻, copy_data: bool) -> void
               | (_rows: Integer, _cols: Integer) -> void
               | (m: Cv::Mat_≺double≻, ranges: Std::Vector≺cv꞉꞉Range≻) -> void
               | (m: Cv::Mat_≺double≻, ranges: Cv::Range) -> void
               | (m: Cv::Mat_≺double≻, roi: Cv::Rect_≺int≻) -> void
               | (_ndims: Integer, _sizes: Rice::Buffer≺int const∗≻) -> void
               | (m: Cv::Mat_≺double≻, row_range: Cv::Range, col_range: Cv::Range) -> void
               | (_ndims: Integer, _sizes: Rice::Buffer≺int const∗≻, value: Double) -> void
               | (_rows: Integer, _cols: Integer, value: Double) -> void
               | (_rows: Integer, _cols: Integer, _data: Rice::Buffer≺double∗≻, _step: Integer) -> void
               | (_ndims: Integer, _sizes: Rice::Buffer≺int const∗≻, _data: Rice::Buffer≺double∗≻, _steps: Rice::Buffer≺unsigned Int64 const∗≻) -> void
    def []=: (arg_0: Integer, arg_1: Double) -> void
        | (arg_0: Cv::Point_≺int≻, arg_1: Double) -> void
        | (arg_0: Integer, arg_1: Integer, arg_2: Double) -> void
        | (arg_0: Integer, arg_1: Integer, arg_2: Integer, arg_3: Double) -> void
    def _dump_data: () -> Rice::Hash
    def adjust_roi: (dtop: Integer, dbottom: Integer, dleft: Integer, dright: Integer) -> Cv::Mat_≺double≻
    def channels: () -> Integer
    def clone: () -> Cv::Mat_≺double≻
    def col: (x: Integer) -> Cv::Mat_≺double≻
    def create: (_size: Cv::Size_≺int≻) -> void
           | (_ndims: Integer, _sizes: Rice::Buffer≺int const∗≻) -> void
           | (_rows: Integer, _cols: Integer) -> void
    def cross: (m: Cv::Mat_≺double≻) -> Cv::Mat_≺double≻
    def depth: () -> Integer
    def diag: (d: Integer) -> Cv::Mat_≺double≻
    def elem_size: () -> Integer
    def elem_size1: () -> Integer
    def initialize_copy: (m: Cv::Mat_≺double≻) -> void
    def release: () -> void
    def row: (y: Integer) -> Cv::Mat_≺double≻
    def step1: (i: Integer) -> Integer
    def step_t: (i: Integer) -> Integer
    def to_vector: () -> Std::Vector≺double≻
    def type: () -> Integer
  end
end
