module Cv
  class Mat3d
    def []: (roi: Cv::Rect) -> Cv::Mat3d
       | (ranges: Cv::Range) -> Cv::Mat3d
       | (ranges: Std::Vector≺cv꞉꞉Range≻) -> Cv::Mat3d
       | (idx0: Integer) -> Cv::Vec3d
       | (pt: Cv::Point) -> Cv::Vec3d
       | (row_range: Cv::Range, col_range: Cv::Range) -> Cv::Mat3d
       | (row: Integer, col: Integer) -> Cv::Vec3d
       | (idx0: Integer, idx1: Integer, idx2: Integer) -> Cv::Vec3d
    def initialize: (e: Cv::MatExpr) -> NilClass
               | () -> NilClass
               | (_size: Cv::Size) -> NilClass
               | (m: Cv::Mat) -> NilClass
               | (e: Cv::MatExpr) -> NilClass
               | (m: Cv::Mat) -> NilClass
               | (pt: Cv::Point3d, copy_data: TrueClass) -> NilClass
               | (_size: Cv::Size, value: Cv::Vec3d) -> NilClass
               | (pt: Cv::Point2d, copy_data: TrueClass) -> NilClass
               | (vec: Std::Vector≺cv꞉꞉Vec≺double‚ 3≻≻, copy_data: TrueClass) -> NilClass
               | (_rows: Integer, _cols: Integer) -> NilClass
               | (m: Cv::Mat3d, ranges: Std::Vector≺cv꞉꞉Range≻) -> NilClass
               | (m: Cv::Mat3d, ranges: Cv::Range) -> NilClass
               | (m: Cv::Mat3d, roi: Cv::Rect) -> NilClass
               | (_ndims: Integer, _sizes: Rice::Pointer≺int≻) -> NilClass
               | (m: Cv::Mat3d, row_range: Cv::Range, col_range: Cv::Range) -> NilClass
               | (_ndims: Integer, _sizes: Rice::Pointer≺int≻, value: Cv::Vec3d) -> NilClass
               | (_rows: Integer, _cols: Integer, value: Cv::Vec3d) -> NilClass
               | (_rows: Integer, _cols: Integer, _data: Cv::Vec3d, _step: Integer) -> NilClass
               | (_ndims: Integer, _sizes: Rice::Pointer≺int≻, _data: Cv::Vec3d, _steps: Rice::Pointer≺unsigned Int64≻) -> NilClass
    def []=: (arg_0: Integer, arg_1: Cv::Vec3d) -> NilClass
        | (arg_0: Cv::Point, arg_1: Cv::Vec3d) -> NilClass
        | (arg_0: Integer, arg_1: Integer, arg_2: Cv::Vec3d) -> NilClass
        | (arg_0: Integer, arg_1: Integer, arg_2: Integer, arg_3: Cv::Vec3d) -> NilClass
    def _dump_data: () -> Hash
    def adjust_roi: (dtop: Integer, dbottom: Integer, dleft: Integer, dright: Integer) -> Cv::Mat3d
    def channels: () -> Integer
    def clone: () -> Cv::Mat3d
    def col: (x: Integer) -> Cv::Mat3d
    def create: (_size: Cv::Size) -> NilClass
           | (_ndims: Integer, _sizes: Rice::Pointer≺int≻) -> NilClass
           | (_rows: Integer, _cols: Integer) -> NilClass
    def cross: (m: Cv::Mat3d) -> Cv::Mat3d
    def depth: () -> Integer
    def diag: (d: Integer) -> Cv::Mat3d
    def elem_size: () -> Integer
    def elem_size1: () -> Integer
    def initialize_copy: (m: Cv::Mat3d) -> NilClass
    def release: () -> NilClass
    def row: (y: Integer) -> Cv::Mat3d
    def step1: (i: Integer) -> Integer
    def step_t: (i: Integer) -> Integer
    def to_vector: () -> Std::Vector≺cv꞉꞉Vec≺double‚ 3≻≻
    def type: () -> Integer
  end
end
