module Cv
  class MatAllocator
    def allocate: (dims: Integer, sizes: Rice::Pointer≺int≻, type: Integer, data: Rice::Pointer≺void≻, step: Rice::Pointer≺unsigned Int64≻, flags: Cv::AccessFlag, usage_flags: Cv::UMatUsageFlags) -> Cv::UMatData
    def allocate?: (data: Cv::UMatData, accessflags: Cv::AccessFlag, usage_flags: Cv::UMatUsageFlags) -> TrueClass
    def copy: (srcdata: Cv::UMatData, dstdata: Cv::UMatData, dims: Integer, sz: Rice::Pointer≺unsigned Int64≻, srcofs: Rice::Pointer≺unsigned Int64≻, srcstep: Rice::Pointer≺unsigned Int64≻, dstofs: Rice::Pointer≺unsigned Int64≻, dststep: Rice::Pointer≺unsigned Int64≻, sync: TrueClass) -> NilClass
    def deallocate: (data: Cv::UMatData) -> NilClass
    def download: (data: Cv::UMatData, dst: Rice::Pointer≺void≻, dims: Integer, sz: Rice::Pointer≺unsigned Int64≻, srcofs: Rice::Pointer≺unsigned Int64≻, srcstep: Rice::Pointer≺unsigned Int64≻, dststep: Rice::Pointer≺unsigned Int64≻) -> NilClass
    def get_buffer_pool_controller: (id: String) -> Cv::BufferPoolController
    def map: (data: Cv::UMatData, accessflags: Cv::AccessFlag) -> NilClass
    def unmap: (data: Cv::UMatData) -> NilClass
    def upload: (data: Cv::UMatData, src: Rice::Pointer≺void≻, dims: Integer, sz: Rice::Pointer≺unsigned Int64≻, dstofs: Rice::Pointer≺unsigned Int64≻, dststep: Rice::Pointer≺unsigned Int64≻, srcstep: Rice::Pointer≺unsigned Int64≻) -> NilClass
  end
end
