module Cv
  class MatConstIterator
    attr_accessor elem_size: Integer
    attr_accessor m: Cv::Mat
    attr_accessor ptr: Rice::Buffer≺unsigned char const∗≻
    attr_accessor slice_end: Rice::Buffer≺unsigned char const∗≻
    attr_accessor slice_start: Rice::Buffer≺unsigned char const∗≻

    def assign_minus: (ofs: Integer) -> Cv::MatConstIterator
    def assign_plus: (ofs: Integer) -> Cv::MatConstIterator
    def initialize: () -> void
               | (_m: Cv::Mat) -> void
               | (_m: Cv::Mat, _pt: Cv::Point_≺int≻) -> void
               | (_m: Cv::Mat, _row: Integer, _col: Integer) -> void
    def decrement: () -> Cv::MatConstIterator
              | (: Integer) -> Cv::MatConstIterator
    def increment: () -> Cv::MatConstIterator
              | (: Integer) -> Cv::MatConstIterator
    def initialize_copy: (it: Cv::MatConstIterator) -> void
    def lpos: () -> Integer
    def pos: () -> Cv::Point_≺int≻
        | (_idx: Rice::Buffer≺int∗≻) -> void
    def seek: (ofs: Integer, relative: bool) -> void
         | (_idx: Rice::Buffer≺int const∗≻, relative: bool) -> void
  end
end
