module Cv
  class MatStep
    attr_reader buf: String
    attr_accessor p: Rice::Pointer≺unsigned Int64≻

    def []: (i: Integer) -> Integer
       | (i: Integer) -> Integer
    def initialize: () -> NilClass
               | (s: Integer) -> NilClass
    def []=: (arg_0: Integer, arg_1: Integer) -> NilClass
    def to_size_t: () -> Integer
  end
end
