module Cv
  class MatSize
    attr_accessor p: Rice::Pointer≺int≻

    def !=: (sz: Cv::MatSize) -> TrueClass
    def initialize: (_p: Rice::Pointer≺int≻) -> NilClass
    def ==: (sz: Cv::MatSize) -> TrueClass
    def []: (i: Integer) -> Integer
    def []=: (arg_0: Integer, arg_1: Integer) -> NilClass
    def dims: () -> Integer
    def inspect: () -> String
    def to_size: () -> Cv::Size
  end
end
