module Cv
  class Matx66f
    def !=: (arg_0: Cv::Matx≺float‚ 6‚ 6≻) -> bool
    def *: (arg_0: Float) -> Cv::Matx≺float‚ 6‚ 6≻
      | (arg_0: Cv::Vec≺float‚ 6≻) -> Cv::Vec≺float‚ 6≻
      | (arg_0: Float) -> Cv::Matx≺float‚ 6‚ 6≻
      | (arg_0: Integer) -> Cv::Matx≺float‚ 6‚ 6≻
    def initialize: () -> void
               | (vals: Rice::Buffer≺float const∗≻) -> void
               | (a: Cv::Matx≺float‚ 6‚ 6≻, b: Cv::Matx≺float‚ 6‚ 6≻, : Cv::MatxAddOp) -> void
               | (a: Cv::Matx≺float‚ 6‚ 6≻, b: Cv::Matx≺float‚ 6‚ 6≻, : Cv::MatxMulOp) -> void
               | (a: Cv::Matx≺float‚ 6‚ 6≻, b: Cv::Matx≺float‚ 6‚ 6≻, : Cv::MatxSubOp) -> void
               | (a: Cv::Matx≺float‚ 6‚ 6≻, b: Cv::Matx≺float‚ 6‚ 6≻, : Cv::MatxDivOp) -> void
               | (a: Cv::Matx≺float‚ 6‚ 6≻, : Cv::MatxTOp) -> void
    def +: (arg_0: Cv::Matx≺float‚ 6‚ 6≻) -> Cv::Matx≺float‚ 6‚ 6≻
    def -: (arg_0: Cv::Matx≺float‚ 6‚ 6≻) -> Cv::Matx≺float‚ 6‚ 6≻
    def /: (arg_0: Float) -> Cv::Matx≺float‚ 6‚ 6≻
      | (arg_0: Float) -> Cv::Matx≺float‚ 6‚ 6≻
    def ==: (arg_0: Cv::Matx≺float‚ 6‚ 6≻) -> bool
    def _dump_data: () -> Rice::Hash
    def assign_divide: (arg_0: Float) -> Cv::Matx≺float‚ 6‚ 6≻
                  | (arg_0: Float) -> Cv::Matx≺float‚ 6‚ 6≻
    def assign_minus: (arg_0: Cv::Matx≺float‚ 6‚ 6≻) -> Cv::Matx≺float‚ 6‚ 6≻
    def assign_multiply: (arg_0: Float) -> Cv::Matx≺float‚ 6‚ 6≻
                    | (arg_0: Float) -> Cv::Matx≺float‚ 6‚ 6≻
                    | (arg_0: Integer) -> Cv::Matx≺float‚ 6‚ 6≻
    def assign_plus: (arg_0: Cv::Matx≺float‚ 6‚ 6≻) -> Cv::Matx≺float‚ 6‚ 6≻
    def call: (row: Integer, col: Integer) -> Float
         | (row: Integer, col: Integer) -> Float
    def channels: () -> Integer
    def col: (i: Integer) -> Cv::Matx≺float‚ 6‚ 1≻
    def cols: () -> Integer
    def ddot: (v: Cv::Matx≺float‚ 6‚ 6≻) -> Float
    def determinant: () -> Float
    def diag: () -> Cv::Matx≺float‚ 6‚ 1≻
    def div: (a: Cv::Matx≺float‚ 6‚ 6≻) -> Cv::Matx≺float‚ 6‚ 6≻
    def dot: (v: Cv::Matx≺float‚ 6‚ 6≻) -> Float
    def each: () -> Integer
    def eql?: (arg_0: Cv::Matx≺float‚ 6‚ 6≻) -> bool
    def input_array: () -> Cv::debug_build_guard::InputArray
    def inspect: () -> Std::String
    def inv: (method: Integer, p_is_ok: Rice::Buffer≺bool∗≻) -> Cv::Matx≺float‚ 6‚ 6≻
    def mul: (a: Cv::Matx≺float‚ 6‚ 6≻) -> Cv::Matx≺float‚ 6‚ 6≻
    def norm: () -> Float
         | (arg_0: Integer) -> Float
    def row: (i: Integer) -> Cv::Matx≺float‚ 1‚ 6≻
    def rows: () -> Integer
    def shortdim: () -> Integer
    def solve: (rhs: Cv::Vec≺float‚ 6≻, method: Integer) -> Cv::Vec≺float‚ 6≻
    def t: () -> Cv::Matx≺float‚ 6‚ 6≻
    def trace: () -> Float
  end
end
