module Cv
  class Matx21b
    attr_reader val: String

    def initialize: () -> NilClass
               | (v0: String) -> NilClass
               | (vals: Rice::Pointer≺unsigned char≻) -> NilClass
               | (a: Cv::Matx12b, arg_1: Cv::MatxTOp) -> NilClass
               | (v0: String, v1: String) -> NilClass
               | (a: Cv::Matx21b, b: Cv::Matx21b, arg_2: Cv::MatxDivOp) -> NilClass
               | (a: Cv::Matx21b, b: Cv::Matx21b, arg_2: Cv::MatxSubOp) -> NilClass
               | (a: Cv::Matx21b, b: Cv::Matx21b, arg_2: Cv::MatxMulOp) -> NilClass
               | (a: Cv::Matx21b, b: Cv::Matx21b, arg_2: Cv::MatxAddOp) -> NilClass
    def !=: (arg_0: Cv::Matx21b) -> TrueClass
    def *: (arg_0: Cv::Vec1b) -> Cv::Vec2b
      | (arg_0: Float) -> Cv::Matx21b
      | (arg_0: Float) -> Cv::Matx21b
      | (arg_0: Integer) -> Cv::Matx21b
    def +: (arg_0: Cv::Matx21b) -> Cv::Matx21b
    def -: (arg_0: Cv::Matx21b) -> Cv::Matx21b
    def /: (arg_0: Float) -> Cv::Matx21b
      | (arg_0: Float) -> Cv::Matx21b
    def ==: (arg_0: Cv::Matx21b) -> TrueClass
    def []: (i: Integer) -> String
       | (i: Integer) -> String
       | (row: Integer, col: Integer) -> String
       | (row: Integer, col: Integer) -> String
    def _dump_data: () -> Hash
    def assign_divide: (arg_0: Float) -> Cv::Matx21b
                  | (arg_0: Float) -> Cv::Matx21b
    def assign_minus: (arg_0: Cv::Matx21b) -> Cv::Matx21b
    def assign_multiply: (arg_0: Integer) -> Cv::Matx21b
                    | (arg_0: Float) -> Cv::Matx21b
                    | (arg_0: Float) -> Cv::Matx21b
    def assign_plus: (arg_0: Cv::Matx21b) -> Cv::Matx21b
    def channels: () -> Integer
    def col: (i: Integer) -> Cv::Matx21b
    def ddot: (v: Cv::Matx21b) -> Float
    def diag: () -> Cv::Matx11b
    def div: (a: Cv::Matx21b) -> Cv::Matx21b
    def dot: (v: Cv::Matx21b) -> String
    def each: (proc: Integer) -> Integer
    def eql?: (arg_0: Cv::Matx21b) -> TrueClass
    def cols: () -> Integer
    def input_array: () -> Cv::InputArray
    def inspect: () -> String
    def mul: (a: Cv::Matx21b) -> Cv::Matx21b
    def norm: () -> Float
         | (arg_0: Integer) -> Float
    def row: (i: Integer) -> Cv::Matx11b
    def rows: () -> Integer
    def shortdim: () -> Integer
    def t: () -> Cv::Matx12b
    def trace: () -> Float
  end
end
