module Cv
  class Matx21d
    def initialize: () -> void
               | (vals: Rice::Buffer≺double const∗≻) -> void
               | (a: Cv::Matx≺double‚ 1‚ 2≻, : Cv::MatxTOp) -> void
               | (v0: Float, v1: Float) -> void
               | (a: Cv::Matx≺double‚ 2‚ 1≻, b: Cv::Matx≺double‚ 2‚ 1≻, : Cv::MatxDivOp) -> void
               | (a: Cv::Matx≺double‚ 2‚ 1≻, b: Cv::Matx≺double‚ 2‚ 1≻, : Cv::MatxSubOp) -> void
               | (a: Cv::Matx≺double‚ 2‚ 1≻, b: Cv::Matx≺double‚ 2‚ 1≻, : Cv::MatxAddOp) -> void
               | (a: Cv::Matx≺double‚ 2‚ 1≻, b: Cv::Matx≺double‚ 2‚ 1≻, : Cv::MatxMulOp) -> void
    def !=: (arg_0: Cv::Matx≺double‚ 2‚ 1≻) -> bool
    def *: (arg_0: Cv::Vec≺double‚ 1≻) -> Cv::Vec≺double‚ 2≻
      | (arg_0: Integer) -> Cv::Matx≺double‚ 2‚ 1≻
      | (arg_0: Float) -> Cv::Matx≺double‚ 2‚ 1≻
      | (arg_0: Float) -> Cv::Matx≺double‚ 2‚ 1≻
    def +: (arg_0: Cv::Matx≺double‚ 2‚ 1≻) -> Cv::Matx≺double‚ 2‚ 1≻
    def -: (arg_0: Cv::Matx≺double‚ 2‚ 1≻) -> Cv::Matx≺double‚ 2‚ 1≻
    def /: (arg_0: Float) -> Cv::Matx≺double‚ 2‚ 1≻
      | (arg_0: Float) -> Cv::Matx≺double‚ 2‚ 1≻
    def ==: (arg_0: Cv::Matx≺double‚ 2‚ 1≻) -> bool
    def _dump_data: () -> Rice::Hash
    def assign_divide: (arg_0: Float) -> Cv::Matx≺double‚ 2‚ 1≻
                  | (arg_0: Float) -> Cv::Matx≺double‚ 2‚ 1≻
    def assign_minus: (arg_0: Cv::Matx≺double‚ 2‚ 1≻) -> Cv::Matx≺double‚ 2‚ 1≻
    def assign_multiply: (arg_0: Float) -> Cv::Matx≺double‚ 2‚ 1≻
                    | (arg_0: Float) -> Cv::Matx≺double‚ 2‚ 1≻
                    | (arg_0: Integer) -> Cv::Matx≺double‚ 2‚ 1≻
    def assign_plus: (arg_0: Cv::Matx≺double‚ 2‚ 1≻) -> Cv::Matx≺double‚ 2‚ 1≻
    def call: (i: Integer) -> Double
         | (i: Integer) -> Double
         | (row: Integer, col: Integer) -> Double
         | (row: Integer, col: Integer) -> Double
    def channels: () -> Integer
    def col: (i: Integer) -> Cv::Matx≺double‚ 2‚ 1≻
    def cols: () -> Integer
    def ddot: (v: Cv::Matx≺double‚ 2‚ 1≻) -> Float
    def determinant: () -> Float
    def diag: () -> Cv::Matx≺double‚ 1‚ 1≻
    def div: (a: Cv::Matx≺double‚ 2‚ 1≻) -> Cv::Matx≺double‚ 2‚ 1≻
    def dot: (v: Cv::Matx≺double‚ 2‚ 1≻) -> Float
    def each: () -> Integer
    def eql?: (arg_0: Cv::Matx≺double‚ 2‚ 1≻) -> bool
    def input_array: () -> Cv::debug_build_guard::InputArray
    def inspect: () -> Std::String
    def inv: (method: Integer, p_is_ok: Rice::Buffer≺bool∗≻) -> Cv::Matx≺double‚ 1‚ 2≻
    def mul: (a: Cv::Matx≺double‚ 2‚ 1≻) -> Cv::Matx≺double‚ 2‚ 1≻
    def norm: () -> Float
         | (arg_0: Integer) -> Float
    def row: (i: Integer) -> Cv::Matx≺double‚ 1‚ 1≻
    def rows: () -> Integer
    def shortdim: () -> Integer
    def solve: (rhs: Cv::Vec≺double‚ 2≻, method: Integer) -> Cv::Vec≺double‚ 1≻
    def t: () -> Cv::Matx≺double‚ 1‚ 2≻
    def trace: () -> Float
  end
end
