module Cv
  class Matx33f
    attr_reader val: String

    def !=: (arg_0: Cv::Matx33f) -> TrueClass
    def *: (arg_0: Float) -> Cv::Matx33f
      | (arg_0: Float) -> Cv::Matx33f
      | (arg_0: Cv::Vec3f) -> Cv::Vec3f
      | (arg_0: Integer) -> Cv::Matx33f
    def +: (arg_0: Cv::Matx33f) -> Cv::Matx33f
    def -: (arg_0: Cv::Matx33f) -> Cv::Matx33f
    def /: (arg_0: Float) -> Cv::Matx33f
      | (arg_0: Float) -> Cv::Matx33f
    def initialize: () -> NilClass
               | (vals: Rice::Pointer≺float≻) -> NilClass
               | (v0: Float) -> NilClass
               | (a: Cv::Matx33f, arg_1: Cv::MatxTOp) -> NilClass
               | (v0: Float, v1: Float) -> NilClass
               | (a: Cv::Matx33f, b: Cv::Matx33f, arg_2: Cv::MatxDivOp) -> NilClass
               | (a: Cv::Matx33f, b: Cv::Matx33f, arg_2: Cv::MatxSubOp) -> NilClass
               | (a: Cv::Matx33f, b: Cv::Matx33f, arg_2: Cv::MatxMulOp) -> NilClass
               | (v0: Float, v1: Float, v2: Float) -> NilClass
               | (a: Cv::Matx33f, b: Cv::Matx33f, arg_2: Cv::MatxAddOp) -> NilClass
               | (v0: Float, v1: Float, v2: Float, v3: Float) -> NilClass
               | (v0: Float, v1: Float, v2: Float, v3: Float, v4: Float) -> NilClass
               | (v0: Float, v1: Float, v2: Float, v3: Float, v4: Float, v5: Float) -> NilClass
               | (v0: Float, v1: Float, v2: Float, v3: Float, v4: Float, v5: Float, v6: Float) -> NilClass
               | (v0: Float, v1: Float, v2: Float, v3: Float, v4: Float, v5: Float, v6: Float, v7: Float) -> NilClass
               | (v0: Float, v1: Float, v2: Float, v3: Float, v4: Float, v5: Float, v6: Float, v7: Float, v8: Float) -> NilClass
    def ==: (arg_0: Cv::Matx33f) -> TrueClass
    def []: (row: Integer, col: Integer) -> Float
       | (row: Integer, col: Integer) -> Float
    def assign_divide: (arg_0: Float) -> Cv::Matx33f
                  | (arg_0: Float) -> Cv::Matx33f
    def assign_minus: (arg_0: Cv::Matx33f) -> Cv::Matx33f
    def assign_multiply: (arg_0: Float) -> Cv::Matx33f
                    | (arg_0: Float) -> Cv::Matx33f
                    | (arg_0: Integer) -> Cv::Matx33f
    def assign_plus: (arg_0: Cv::Matx33f) -> Cv::Matx33f
    def channels: () -> Integer
    def col: (i: Integer) -> Cv::Matx31f
    def ddot: (v: Cv::Matx33f) -> Float
    def diag: () -> Cv::Matx31f
    def div: (a: Cv::Matx33f) -> Cv::Matx33f
    def dot: (v: Cv::Matx33f) -> Float
    def each: (proc: Integer) -> Integer
    def eql?: (arg_0: Cv::Matx33f) -> TrueClass
    def _dump_data: () -> Hash
    def cols: () -> Integer
    def input_array: () -> Cv::InputArray
    def inspect: () -> String
    def inv: (method: Integer, p_is_ok: Rice::Pointer≺bool≻) -> Cv::Matx33f
    def mul: (a: Cv::Matx33f) -> Cv::Matx33f
    def norm: () -> Float
         | (arg_0: Integer) -> Float
    def row: (i: Integer) -> Cv::Matx13f
    def rows: () -> Integer
    def shortdim: () -> Integer
    def solve: (rhs: Cv::Vec3f, method: Integer) -> Cv::Vec3f
    def t: () -> Cv::Matx33f
    def trace: () -> Float
  end
end
