module Cv
  class Matx12d
    attr_reader val: String

    def !=: (arg_0: Cv::Matx12d) -> TrueClass
    def *: (arg_0: Float) -> Cv::Matx12d
      | (arg_0: Cv::Vec2d) -> Cv::Vec1d
      | (arg_0: Float) -> Cv::Matx12d
      | (arg_0: Integer) -> Cv::Matx12d
    def +: (arg_0: Cv::Matx12d) -> Cv::Matx12d
    def -: (arg_0: Cv::Matx12d) -> Cv::Matx12d
    def initialize: (vals: Rice::Pointer≺double≻) -> NilClass
               | () -> NilClass
               | (v0: Float) -> NilClass
               | (a: Cv::Matx21d, arg_1: Cv::MatxTOp) -> NilClass
               | (v0: Float, v1: Float) -> NilClass
               | (a: Cv::Matx12d, b: Cv::Matx12d, arg_2: Cv::MatxSubOp) -> NilClass
               | (a: Cv::Matx12d, b: Cv::Matx12d, arg_2: Cv::MatxAddOp) -> NilClass
               | (a: Cv::Matx12d, b: Cv::Matx12d, arg_2: Cv::MatxMulOp) -> NilClass
               | (a: Cv::Matx12d, b: Cv::Matx12d, arg_2: Cv::MatxDivOp) -> NilClass
    def /: (arg_0: Float) -> Cv::Matx12d
      | (arg_0: Float) -> Cv::Matx12d
    def ==: (arg_0: Cv::Matx12d) -> TrueClass
    def []: (i: Integer) -> Float
       | (i: Integer) -> Float
       | (row: Integer, col: Integer) -> Float
       | (row: Integer, col: Integer) -> Float
    def _dump_data: () -> Hash
    def assign_divide: (arg_0: Float) -> Cv::Matx12d
                  | (arg_0: Float) -> Cv::Matx12d
    def assign_minus: (arg_0: Cv::Matx12d) -> Cv::Matx12d
    def assign_multiply: (arg_0: Float) -> Cv::Matx12d
                    | (arg_0: Float) -> Cv::Matx12d
                    | (arg_0: Integer) -> Cv::Matx12d
    def assign_plus: (arg_0: Cv::Matx12d) -> Cv::Matx12d
    def col: (i: Integer) -> Cv::Matx11d
    def cols: () -> Integer
    def ddot: (v: Cv::Matx12d) -> Float
    def diag: () -> Cv::Matx11d
    def div: (a: Cv::Matx12d) -> Cv::Matx12d
    def channels: () -> Integer
    def dot: (v: Cv::Matx12d) -> Float
    def each: (proc: Integer) -> Integer
    def eql?: (arg_0: Cv::Matx12d) -> TrueClass
    def input_array: () -> Cv::InputArray
    def inspect: () -> String
    def inv: (method: Integer, p_is_ok: Rice::Pointer≺bool≻) -> Cv::Matx21d
    def mul: (a: Cv::Matx12d) -> Cv::Matx12d
    def norm: () -> Float
         | (arg_0: Integer) -> Float
    def row: (i: Integer) -> Cv::Matx12d
    def rows: () -> Integer
    def shortdim: () -> Integer
    def solve: (rhs: Cv::Vec1d, method: Integer) -> Cv::Vec2d
    def t: () -> Cv::Matx21d
    def trace: () -> Float
  end
end
