module Cv
  class Matx21l
    def !=: (arg_0: Cv::Matx21i) -> TrueClass
    def *: (arg_0: Float) -> Cv::Matx21i
      | (arg_0: Cv::Vec1i) -> Cv::Vec2i
      | (arg_0: Float) -> Cv::Matx21i
      | (arg_0: Integer) -> Cv::Matx21i
    def initialize: () -> NilClass
               | (vals: Rice::Pointer≺int≻) -> NilClass
               | (v0: Integer, v1: Integer) -> NilClass
               | (a: Cv::Matx21i, b: Cv::Matx21i, arg_2: Cv::MatxSubOp) -> NilClass
               | (a: Cv::Matx21i, b: Cv::Matx21i, arg_2: Cv::MatxAddOp) -> NilClass
               | (a: Cv::Matx21i, b: Cv::Matx21i, arg_2: Cv::MatxMulOp) -> NilClass
               | (a: Cv::Matx21i, b: Cv::Matx21i, arg_2: Cv::MatxDivOp) -> NilClass
               | (a: Cv::Matx12i, arg_1: Cv::MatxTOp) -> NilClass
    def +: (arg_0: Cv::Matx21i) -> Cv::Matx21i
    def -: (arg_0: Cv::Matx21i) -> Cv::Matx21i
    def /: (arg_0: Float) -> Cv::Matx21i
      | (arg_0: Float) -> Cv::Matx21i
    def ==: (arg_0: Cv::Matx21i) -> TrueClass
    def _dump_data: () -> Hash
    def assign_divide: (arg_0: Float) -> Cv::Matx21i
                  | (arg_0: Float) -> Cv::Matx21i
    def assign_minus: (arg_0: Cv::Matx21i) -> Cv::Matx21i
    def assign_multiply: (arg_0: Integer) -> Cv::Matx21i
                    | (arg_0: Float) -> Cv::Matx21i
                    | (arg_0: Float) -> Cv::Matx21i
    def assign_plus: (arg_0: Cv::Matx21i) -> Cv::Matx21i
    def call: (i: Integer) -> Integer
         | (i: Integer) -> Integer
         | (row: Integer, col: Integer) -> Integer
         | (row: Integer, col: Integer) -> Integer
    def channels: () -> Integer
    def col: (i: Integer) -> Cv::Matx21i
    def cols: () -> Integer
    def ddot: (v: Cv::Matx21i) -> Float
    def determinant: () -> Float
    def diag: () -> Cv::Matx11i
    def div: (a: Cv::Matx21i) -> Cv::Matx21i
    def dot: (v: Cv::Matx21i) -> Integer
    def each: () -> Integer
    def eql?: (arg_0: Cv::Matx21i) -> TrueClass
    def input_array: () -> Cv::InputArray
    def inspect: () -> String
    def mul: (a: Cv::Matx21i) -> Cv::Matx21i
    def norm: () -> Float
         | (arg_0: Integer) -> Float
    def row: (i: Integer) -> Cv::Matx11i
    def rows: () -> Integer
    def shortdim: () -> Integer
    def t: () -> Cv::Matx12i
    def trace: () -> Float
  end
end
