module Cv
  class MergeMertens
    def get_contrast_weight: () -> Float
    def get_exposure_weight: () -> Float
    def get_saturation_weight: () -> Float
    def process: (src: Cv::InputArray, dst: Cv::OutputArray) -> NilClass
            | (src: Cv::InputArray, dst: Cv::OutputArray, times: Cv::InputArray, response: Cv::InputArray) -> NilClass
    def set_contrast_weight: (contrast_weiht: Float) -> NilClass
    def set_exposure_weight: (exposure_weight: Float) -> NilClass
    def set_saturation_weight: (saturation_weight: Float) -> NilClass
  end
end
