module Cv
  class MergeRobertson
    def process: (src: Cv::InputArray, dst: Cv::OutputArray, times: Cv::InputArray) -> NilClass
            | (src: Cv::InputArray, dst: Cv::OutputArray, times: Cv::InputArray, response: Cv::InputArray) -> NilClass
  end
end
