module Cv
  class MinProblemSolver
    def get_function: () -> Cv::Ptr≺cv꞉꞉MinProblemSolver꞉꞉Function≻
    def get_term_criteria: () -> Cv::TermCriteria
    def minimize: (x: Cv::InputOutputArray) -> Float
    def set_function: (f: Cv::Ptr≺cv꞉꞉MinProblemSolver꞉꞉Function≻) -> NilClass
    def set_term_criteria: (termcrit: Cv::TermCriteria) -> NilClass
  end
end
