module Cv
  class OutputArray
    def get_host_mem_ref: () -> Cv::cuda::HostMem
    def initialize: () -> void
               | (m: Cv::Mat) -> void
               | (vec: Std::Vector≺cv꞉꞉Mat≻) -> void
               | (d_mat: Cv::cuda::GpuMat) -> void
               | (buf: Cv::ogl::Buffer) -> void
               | (cuda_mem: Cv::cuda::HostMem) -> void
               | (m: Cv::UMat) -> void
               | (vec: Std::Vector≺cv꞉꞉UMat≻) -> void
               | (m: Cv::Mat) -> void
               | (vec: Std::Vector≺cv꞉꞉Mat≻) -> void
               | (d_mat: Cv::cuda::GpuMat) -> void
               | (buf: Cv::ogl::Buffer) -> void
               | (cuda_mem: Cv::cuda::HostMem) -> void
               | (m: Cv::UMat) -> void
               | (vec: Std::Vector≺cv꞉꞉UMat≻) -> void
               | (arg_0: Std::Vector≺vector≺cv꞉꞉Point_≺int≻≻≻) -> void
               | (arg_0: Std::Vector≺cv꞉꞉Vec≺unsigned char‚ 1≻≻) -> void
               | (arg_0: Std::Vector≺cv꞉꞉Vec≺unsigned char‚ 2≻≻) -> void
               | (arg_0: Std::Vector≺cv꞉꞉Vec≺unsigned char‚ 3≻≻) -> void
               | (arg_0: Std::Vector≺cv꞉꞉Vec≺unsigned char‚ 4≻≻) -> void
               | (arg_0: Std::Vector≺cv꞉꞉Vec≺short‚ 1≻≻) -> void
               | (arg_0: Std::Vector≺cv꞉꞉Vec≺short‚ 2≻≻) -> void
               | (arg_0: Std::Vector≺cv꞉꞉Vec≺short‚ 3≻≻) -> void
               | (arg_0: Std::Vector≺cv꞉꞉Vec≺short‚ 4≻≻) -> void
               | (arg_0: Std::Vector≺cv꞉꞉Vec≺unsigned short‚ 1≻≻) -> void
               | (arg_0: Std::Vector≺cv꞉꞉Vec≺unsigned short‚ 2≻≻) -> void
               | (arg_0: Std::Vector≺cv꞉꞉Vec≺unsigned short‚ 3≻≻) -> void
               | (arg_0: Std::Vector≺cv꞉꞉Vec≺unsigned short‚ 4≻≻) -> void
               | (arg_0: Std::Vector≺cv꞉꞉Vec≺int‚ 1≻≻) -> void
               | (arg_0: Std::Vector≺cv꞉꞉Vec≺int‚ 2≻≻) -> void
               | (arg_0: Std::Vector≺cv꞉꞉Vec≺int‚ 3≻≻) -> void
               | (arg_0: Std::Vector≺cv꞉꞉Vec≺int‚ 4≻≻) -> void
               | (arg_0: Std::Vector≺cv꞉꞉Vec≺float‚ 1≻≻) -> void
               | (arg_0: Std::Vector≺cv꞉꞉Vec≺float‚ 2≻≻) -> void
               | (arg_0: Std::Vector≺cv꞉꞉Vec≺float‚ 3≻≻) -> void
               | (arg_0: Std::Vector≺cv꞉꞉Vec≺float‚ 4≻≻) -> void
               | (arg_0: Std::Vector≺cv꞉꞉Vec≺float‚ 6≻≻) -> void
               | (arg_0: Std::Vector≺cv꞉꞉Vec≺double‚ 1≻≻) -> void
               | (arg_0: Std::Vector≺cv꞉꞉Vec≺double‚ 2≻≻) -> void
               | (arg_0: Std::Vector≺cv꞉꞉Vec≺double‚ 3≻≻) -> void
               | (arg_0: Std::Vector≺cv꞉꞉Vec≺double‚ 4≻≻) -> void
               | (_flags: Integer, _obj: Rice::Buffer≺void∗≻) -> void
    def clear: () -> void
    def get_o_gl_buffer_ref: () -> Cv::ogl::Buffer
    def get_gpu_mat_vec_ref: () -> Std::Vector≺cv꞉꞉cuda꞉꞉GpuMat≻
    def create: (sz: Cv::Size_≺int≻, type: Integer, i: Integer, allow_transposed: bool, fixed_depth_mask: Enum cv::debug_build_guard::_OutputArray::DepthMask) -> void
           | (rows: Integer, cols: Integer, type: Integer, i: Integer, allow_transposed: bool, fixed_depth_mask: Enum cv::debug_build_guard::_OutputArray::DepthMask) -> void
           | (dims: Integer, size: Rice::Buffer≺int const∗≻, type: Integer, i: Integer, allow_transposed: bool, fixed_depth_mask: Enum cv::debug_build_guard::_OutputArray::DepthMask) -> void
    def get_gpu_mat_ref: () -> Cv::cuda::GpuMat
    def get_u_mat_ref: (i: Integer) -> Cv::UMat
    def assign: (u: Cv::UMat) -> void
           | (m: Cv::Mat) -> void
           | (v: Std::Vector≺cv꞉꞉UMat≻) -> void
           | (v: Std::Vector≺cv꞉꞉Mat≻) -> void
    def fixed_size?: () -> bool
    def fixed_type?: () -> bool
    def get_mat_ref: (i: Integer) -> Cv::Mat
    def create_same_size: (arr: Cv::debug_build_guard::InputArray, mtype: Integer) -> void
    def move: (m: Cv::Mat) -> void
         | (u: Cv::UMat) -> void
    def needed?: () -> bool
    def release: () -> void
    def set_to: (value: Cv::debug_build_guard::InputArray, mask: Cv::debug_build_guard::InputArray) -> void
  end
end
