module Cv
  class PCA
    attr_accessor eigenvalues: Cv::Mat
    attr_accessor eigenvectors: Cv::Mat
    attr_accessor mean: Cv::Mat

    def back_project: (vec: Cv::InputArray) -> Cv::Mat
                 | (vec: Cv::InputArray, result: Cv::OutputArray) -> NilClass
    def initialize: () -> NilClass
               | (data: Cv::InputArray, mean: Cv::InputArray, flags: Integer, retained_variance: Float) -> NilClass
               | (data: Cv::InputArray, mean: Cv::InputArray, flags: Integer, max_components: Integer) -> NilClass
    def call: (data: Cv::InputArray, mean: Cv::InputArray, flags: Integer, max_components: Integer) -> Cv::PCA
         | (data: Cv::InputArray, mean: Cv::InputArray, flags: Integer, retained_variance: Float) -> Cv::PCA
    def project: (vec: Cv::InputArray) -> Cv::Mat
            | (vec: Cv::InputArray, result: Cv::OutputArray) -> NilClass
    def read: (fn: Cv::FileNode) -> NilClass
    def write: (fs: Cv::FileStorage) -> NilClass
  end
end
