module Cv
  class Point3s
    attr_accessor x: Integer
    attr_accessor y: Integer
    attr_accessor z: Integer

    def !=: (arg_0: Cv::Point3_≺short≻) -> bool
       | (arg_0: Cv::Point3_≺short≻) -> bool
    def initialize: () -> void
               | (pt: Cv::Point_≺short≻) -> void
               | (v: Cv::Vec≺short‚ 3≻) -> void
               | (_x: Integer, _y: Integer, _z: Integer) -> void
    def *: (arg_0: Integer) -> Cv::Point3_≺short≻
      | (arg_0: Float) -> Cv::Point3_≺short≻
      | (arg_0: Integer) -> Cv::Point3_≺short≻
    def +: (arg_0: Cv::Point3_≺short≻) -> Cv::Point3_≺short≻
      | (arg_0: Cv::Point3_≺short≻) -> Cv::Point3_≺short≻
    def -: (arg_0: Cv::Point3_≺short≻) -> Cv::Point3_≺short≻
      | (arg_0: Cv::Point3_≺short≻) -> Cv::Point3_≺short≻
    def /: (arg_0: Integer) -> Cv::Point3_≺short≻
      | (arg_0: Integer) -> Cv::Point3_≺short≻
      | (arg_0: Float) -> Cv::Point3_≺short≻
      | (arg_0: Float) -> Cv::Point3_≺short≻
    def ==: (arg_0: Cv::Point3_≺short≻) -> bool
       | (arg_0: Cv::Point3_≺short≻) -> bool
    def assign_divide: (arg_0: Float) -> Cv::Point3_≺short≻
                  | (arg_0: Integer) -> Cv::Point3_≺short≻
                  | (arg_0: Integer) -> Cv::Point3_≺short≻
                  | (arg_0: Float) -> Cv::Point3_≺short≻
    def assign_minus: (arg_0: Cv::Point3_≺short≻) -> Cv::Point3_≺short≻
                 | (arg_0: Cv::Point3_≺short≻) -> Cv::Point3_≺short≻
    def assign_multiply: (arg_0: Float) -> Cv::Point3_≺short≻
                    | (arg_0: Float) -> Cv::Point3_≺short≻
    def assign_plus: (arg_0: Cv::Point3_≺short≻) -> Cv::Point3_≺short≻
                | (arg_0: Cv::Point3_≺short≻) -> Cv::Point3_≺short≻
    def cross: (pt: Cv::Point3_≺short≻) -> Cv::Point3_≺short≻
    def ddot: (pt: Cv::Point3_≺short≻) -> Float
    def dot: (pt: Cv::Point3_≺short≻) -> Integer
    def initialize_copy: (pt: Cv::Point3_≺short≻) -> void
    def inspect: () -> Std::String
    def to_vec: () -> Cv::Vec≺short‚ 3≻
  end
end
