module Cv
  class Point3b
    attr_accessor x: String
    attr_accessor y: String
    attr_accessor z: String

    def !=: (arg_0: Cv::Point3_≺unsigned char≻) -> bool
       | (arg_0: Cv::Point3_≺unsigned char≻) -> bool
    def initialize: () -> void
               | (pt: Cv::Point_≺unsigned char≻) -> void
               | (v: Cv::Vec≺unsigned char‚ 3≻) -> void
               | (_x: String, _y: String, _z: String) -> void
    def *: (arg_0: Integer) -> Cv::Point3_≺unsigned char≻
      | (arg_0: Float) -> Cv::Point3_≺unsigned char≻
      | (arg_0: Integer) -> Cv::Point3_≺unsigned char≻
    def +: (arg_0: Cv::Point3_≺unsigned char≻) -> Cv::Point3_≺unsigned char≻
      | (arg_0: Cv::Point3_≺unsigned char≻) -> Cv::Point3_≺unsigned char≻
    def -: (arg_0: Cv::Point3_≺unsigned char≻) -> Cv::Point3_≺unsigned char≻
      | (arg_0: Cv::Point3_≺unsigned char≻) -> Cv::Point3_≺unsigned char≻
    def /: (arg_0: Integer) -> Cv::Point3_≺unsigned char≻
      | (arg_0: Integer) -> Cv::Point3_≺unsigned char≻
      | (arg_0: Float) -> Cv::Point3_≺unsigned char≻
      | (arg_0: Float) -> Cv::Point3_≺unsigned char≻
    def ==: (arg_0: Cv::Point3_≺unsigned char≻) -> bool
       | (arg_0: Cv::Point3_≺unsigned char≻) -> bool
    def assign_divide: (arg_0: Float) -> Cv::Point3_≺unsigned char≻
                  | (arg_0: Integer) -> Cv::Point3_≺unsigned char≻
                  | (arg_0: Integer) -> Cv::Point3_≺unsigned char≻
                  | (arg_0: Float) -> Cv::Point3_≺unsigned char≻
    def assign_minus: (arg_0: Cv::Point3_≺unsigned char≻) -> Cv::Point3_≺unsigned char≻
                 | (arg_0: Cv::Point3_≺unsigned char≻) -> Cv::Point3_≺unsigned char≻
    def assign_multiply: (arg_0: Float) -> Cv::Point3_≺unsigned char≻
                    | (arg_0: Float) -> Cv::Point3_≺unsigned char≻
    def assign_plus: (arg_0: Cv::Point3_≺unsigned char≻) -> Cv::Point3_≺unsigned char≻
                | (arg_0: Cv::Point3_≺unsigned char≻) -> Cv::Point3_≺unsigned char≻
    def cross: (pt: Cv::Point3_≺unsigned char≻) -> Cv::Point3_≺unsigned char≻
    def ddot: (pt: Cv::Point3_≺unsigned char≻) -> Float
    def dot: (pt: Cv::Point3_≺unsigned char≻) -> String
    def initialize_copy: (pt: Cv::Point3_≺unsigned char≻) -> void
    def inspect: () -> Std::String
    def to_vec: () -> Cv::Vec≺unsigned char‚ 3≻
  end
end
