module Cv
  class Point3i
    attr_accessor x: Integer
    attr_accessor y: Integer
    attr_accessor z: Integer

    def !=: (arg_0: Cv::Point3i) -> TrueClass
       | (arg_0: Cv::Point3i) -> TrueClass
    def initialize: () -> NilClass
               | (pt: Cv::Point) -> NilClass
               | (v: Cv::Vec3i) -> NilClass
               | (_x: Integer, _y: Integer, _z: Integer) -> NilClass
    def *: (arg_0: Integer) -> Cv::Point3i
      | (arg_0: Float) -> Cv::Point3i
      | (arg_0: Integer) -> Cv::Point3i
    def +: (arg_0: Cv::Point3i) -> Cv::Point3i
      | (arg_0: Cv::Point3i) -> Cv::Point3i
    def -: (arg_0: Cv::Point3i) -> Cv::Point3i
      | (arg_0: Cv::Point3i) -> Cv::Point3i
    def /: (arg_0: Integer) -> Cv::Point3i
      | (arg_0: Integer) -> Cv::Point3i
      | (arg_0: Float) -> Cv::Point3i
      | (arg_0: Float) -> Cv::Point3i
    def ==: (arg_0: Cv::Point3i) -> TrueClass
       | (arg_0: Cv::Point3i) -> TrueClass
    def assign_divide: (arg_0: Float) -> Cv::Point3i
                  | (arg_0: Integer) -> Cv::Point3i
                  | (arg_0: Integer) -> Cv::Point3i
                  | (arg_0: Float) -> Cv::Point3i
    def assign_minus: (arg_0: Cv::Point3i) -> Cv::Point3i
                 | (arg_0: Cv::Point3i) -> Cv::Point3i
    def assign_multiply: (arg_0: Float) -> Cv::Point3i
                    | (arg_0: Float) -> Cv::Point3i
    def assign_plus: (arg_0: Cv::Point3i) -> Cv::Point3i
                | (arg_0: Cv::Point3i) -> Cv::Point3i
    def cross: (pt: Cv::Point3i) -> Cv::Point3i
    def ddot: (pt: Cv::Point3i) -> Float
    def dot: (pt: Cv::Point3i) -> Integer
    def initialize_copy: (pt: Cv::Point3i) -> NilClass
    def inspect: () -> String
    def to_vec: () -> Cv::Vec3i
  end
end
