module Cv
  class Point2b
    attr_accessor x: String
    attr_accessor y: String

    def initialize: () -> void
               | (sz: Cv::Size_≺unsigned char≻) -> void
               | (v: Cv::Vec≺unsigned char‚ 2≻) -> void
               | (_x: String, _y: String) -> void
    def !=: (arg_0: Cv::Point_≺unsigned char≻) -> bool
       | (arg_0: Cv::Point_≺unsigned char≻) -> bool
    def *: (arg_0: Float) -> Cv::Point_≺unsigned char≻
      | (arg_0: Integer) -> Cv::Point_≺unsigned char≻
      | (arg_0: Integer) -> Cv::Point_≺unsigned char≻
    def +: (arg_0: Cv::Point_≺unsigned char≻) -> Cv::Point_≺unsigned char≻
      | (arg_0: Cv::Point_≺unsigned char≻) -> Cv::Point_≺unsigned char≻
    def -: (arg_0: Cv::Point_≺unsigned char≻) -> Cv::Point_≺unsigned char≻
      | (arg_0: Cv::Point_≺unsigned char≻) -> Cv::Point_≺unsigned char≻
    def /: (arg_0: Float) -> Cv::Point_≺unsigned char≻
      | (arg_0: Integer) -> Cv::Point_≺unsigned char≻
      | (arg_0: Integer) -> Cv::Point_≺unsigned char≻
      | (arg_0: Float) -> Cv::Point_≺unsigned char≻
    def ==: (arg_0: Cv::Point_≺unsigned char≻) -> bool
       | (arg_0: Cv::Point_≺unsigned char≻) -> bool
    def assign_divide: (arg_0: Integer) -> Cv::Point_≺unsigned char≻
                  | (arg_0: Float) -> Cv::Point_≺unsigned char≻
                  | (arg_0: Float) -> Cv::Point_≺unsigned char≻
                  | (arg_0: Integer) -> Cv::Point_≺unsigned char≻
    def assign_minus: (arg_0: Cv::Point_≺unsigned char≻) -> Cv::Point_≺unsigned char≻
                 | (arg_0: Cv::Point_≺unsigned char≻) -> Cv::Point_≺unsigned char≻
    def assign_multiply: (arg_0: Float) -> Cv::Point_≺unsigned char≻
                    | (arg_0: Float) -> Cv::Point_≺unsigned char≻
    def assign_plus: (arg_0: Cv::Point_≺unsigned char≻) -> Cv::Point_≺unsigned char≻
                | (arg_0: Cv::Point_≺unsigned char≻) -> Cv::Point_≺unsigned char≻
    def cross: (pt: Cv::Point_≺unsigned char≻) -> Float
    def ddot: (pt: Cv::Point_≺unsigned char≻) -> Float
    def dot: (pt: Cv::Point_≺unsigned char≻) -> String
    def initialize_copy: (pt: Cv::Point_≺unsigned char≻) -> void
    def inside?: (r: Cv::Rect_≺unsigned char≻) -> bool
    def inspect: () -> Std::String
    def norm: () -> Float
    def to_s: () -> Std::String
    def to_vec: () -> Cv::Vec≺unsigned char‚ 2≻
  end
end
