module Cv
  class Point2w
    attr_accessor x: Integer
    attr_accessor y: Integer

    def initialize: () -> NilClass
               | (sz: Cv::Size2w) -> NilClass
               | (v: Cv::Vec2w) -> NilClass
               | (_x: Integer, _y: Integer) -> NilClass
    def !=: (arg_0: Cv::Point2w) -> TrueClass
       | (arg_0: Cv::Point2w) -> TrueClass
    def *: (arg_0: Float) -> Cv::Point2w
      | (arg_0: Integer) -> Cv::Point2w
      | (arg_0: Integer) -> Cv::Point2w
    def +: (arg_0: Cv::Point2w) -> Cv::Point2w
      | (arg_0: Cv::Point2w) -> Cv::Point2w
    def -: (arg_0: Cv::Point2w) -> Cv::Point2w
      | (arg_0: Cv::Point2w) -> Cv::Point2w
    def /: (arg_0: Float) -> Cv::Point2w
      | (arg_0: Integer) -> Cv::Point2w
      | (arg_0: Integer) -> Cv::Point2w
      | (arg_0: Float) -> Cv::Point2w
    def ==: (arg_0: Cv::Point2w) -> TrueClass
       | (arg_0: Cv::Point2w) -> TrueClass
    def assign_divide: (arg_0: Integer) -> Cv::Point2w
                  | (arg_0: Float) -> Cv::Point2w
                  | (arg_0: Float) -> Cv::Point2w
                  | (arg_0: Integer) -> Cv::Point2w
    def assign_minus: (arg_0: Cv::Point2w) -> Cv::Point2w
                 | (arg_0: Cv::Point2w) -> Cv::Point2w
    def assign_multiply: (arg_0: Float) -> Cv::Point2w
                    | (arg_0: Float) -> Cv::Point2w
    def assign_plus: (arg_0: Cv::Point2w) -> Cv::Point2w
                | (arg_0: Cv::Point2w) -> Cv::Point2w
    def cross: (pt: Cv::Point2w) -> Float
    def ddot: (pt: Cv::Point2w) -> Float
    def dot: (pt: Cv::Point2w) -> Integer
    def initialize_copy: (pt: Cv::Point2w) -> NilClass
    def inside?: (r: Cv::Rect2w) -> TrueClass
    def inspect: () -> String
    def norm: () -> Float
    def to_s: () -> String
    def to_vec: () -> Cv::Vec2w
  end
end
