module Cv
  class Point
    attr_accessor x: Integer
    attr_accessor y: Integer

    def initialize: () -> NilClass
               | (sz: Cv::Size) -> NilClass
               | (v: Cv::Vec2i) -> NilClass
               | (_x: Integer, _y: Integer) -> NilClass
    def !=: (arg_0: Cv::Point) -> TrueClass
       | (arg_0: Cv::Point) -> TrueClass
    def *: (arg_0: Float) -> Cv::Point
      | (arg_0: Integer) -> Cv::Point
      | (arg_0: Integer) -> Cv::Point
    def +: (arg_0: Cv::Point) -> Cv::Point
      | (arg_0: Cv::Point) -> Cv::Point
    def -: (arg_0: Cv::Point) -> Cv::Point
      | (arg_0: Cv::Point) -> Cv::Point
    def /: (arg_0: Float) -> Cv::Point
      | (arg_0: Integer) -> Cv::Point
      | (arg_0: Integer) -> Cv::Point
      | (arg_0: Float) -> Cv::Point
    def ==: (arg_0: Cv::Point) -> TrueClass
       | (arg_0: Cv::Point) -> TrueClass
    def assign_divide: (arg_0: Integer) -> Cv::Point
                  | (arg_0: Float) -> Cv::Point
                  | (arg_0: Float) -> Cv::Point
                  | (arg_0: Integer) -> Cv::Point
    def assign_minus: (arg_0: Cv::Point) -> Cv::Point
                 | (arg_0: Cv::Point) -> Cv::Point
    def assign_multiply: (arg_0: Float) -> Cv::Point
                    | (arg_0: Float) -> Cv::Point
    def assign_plus: (arg_0: Cv::Point) -> Cv::Point
                | (arg_0: Cv::Point) -> Cv::Point
    def cross: (pt: Cv::Point) -> Float
    def ddot: (pt: Cv::Point) -> Float
    def dot: (pt: Cv::Point) -> Integer
    def initialize_copy: (pt: Cv::Point) -> NilClass
    def inside?: (r: Cv::Rect) -> TrueClass
    def inspect: () -> String
    def norm: () -> Float
    def to_s: () -> String
    def to_vec: () -> Cv::Vec2i
  end
end
