module Cv
  class Point2f
    attr_accessor x: Float
    attr_accessor y: Float

    def initialize: () -> NilClass
               | (sz: Cv::Size2f) -> NilClass
               | (v: Cv::Vec2f) -> NilClass
               | (_x: Float, _y: Float) -> NilClass
    def !=: (arg_0: Cv::Point2f) -> TrueClass
       | (arg_0: Cv::Point2f) -> TrueClass
    def *: (arg_0: Float) -> Cv::Point2f
      | (arg_0: Integer) -> Cv::Point2f
      | (arg_0: Integer) -> Cv::Point2f
    def +: (arg_0: Cv::Point2f) -> Cv::Point2f
      | (arg_0: Cv::Point2f) -> Cv::Point2f
    def -: (arg_0: Cv::Point2f) -> Cv::Point2f
      | (arg_0: Cv::Point2f) -> Cv::Point2f
    def /: (arg_0: Float) -> Cv::Point2f
      | (arg_0: Integer) -> Cv::Point2f
      | (arg_0: Integer) -> Cv::Point2f
      | (arg_0: Float) -> Cv::Point2f
    def ==: (arg_0: Cv::Point2f) -> TrueClass
       | (arg_0: Cv::Point2f) -> TrueClass
    def assign_divide: (arg_0: Integer) -> Cv::Point2f
                  | (arg_0: Float) -> Cv::Point2f
                  | (arg_0: Float) -> Cv::Point2f
                  | (arg_0: Integer) -> Cv::Point2f
    def assign_minus: (arg_0: Cv::Point2f) -> Cv::Point2f
                 | (arg_0: Cv::Point2f) -> Cv::Point2f
    def assign_multiply: (arg_0: Float) -> Cv::Point2f
                    | (arg_0: Float) -> Cv::Point2f
    def assign_plus: (arg_0: Cv::Point2f) -> Cv::Point2f
                | (arg_0: Cv::Point2f) -> Cv::Point2f
    def cross: (pt: Cv::Point2f) -> Float
    def ddot: (pt: Cv::Point2f) -> Float
    def dot: (pt: Cv::Point2f) -> Float
    def initialize_copy: (pt: Cv::Point2f) -> NilClass
    def inside?: (r: Cv::Rect2f) -> TrueClass
    def inspect: () -> String
    def norm: () -> Float
    def to_s: () -> String
    def to_vec: () -> Cv::Vec2f
  end
end
