module Cv
  class Point3w
    attr_accessor x: Integer
    attr_accessor y: Integer
    attr_accessor z: Integer

    def initialize: () -> NilClass
               | (pt: Cv::Point2w) -> NilClass
               | (v: Cv::Vec3w) -> NilClass
               | (_x: Integer, _y: Integer, _z: Integer) -> NilClass
    def assign: (pt: Cv::Point3w) -> Cv::Point3w
           | (pt: Cv::Point3w) -> Cv::Point3w
    def cross: (pt: Cv::Point3w) -> Cv::Point3w
    def ddot: (pt: Cv::Point3w) -> Float
    def dot: (pt: Cv::Point3w) -> Integer
    def initialize_copy: (pt: Cv::Point3w) -> NilClass
  end
end
