module Cv
  class Ptr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉GRULayer≻
    def initialize: () -> NilClass
               | (o: Std::SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉GRULayer≻) -> NilClass
               | (o: Std::SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉GRULayer≻) -> NilClass
               | (ptr: Cv::Dnn::GRULayer) -> NilClass
               | (value: Cv::Dnn::GRULayer) -> NilClass
    def assign: (o: Cv::Ptr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉GRULayer≻) -> Cv::Ptr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉GRULayer≻
    def get: () -> Cv::Dnn::GRULayer
    def empty?: () -> TrueClass
    def initialize_copy: (o: Cv::Ptr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉GRULayer≻) -> NilClass
    def release: () -> NilClass
    def reset: () -> NilClass
  end
end
