module Cv
  class Ptr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉GeluApproximationLayer≻
    def initialize: () -> NilClass
               | (o: Std::SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉GeluApproximationLayer≻) -> NilClass
               | (o: Std::SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉GeluApproximationLayer≻) -> NilClass
               | (ptr: Cv::Dnn::GeluApproximationLayer) -> NilClass
               | (value: Cv::Dnn::GeluApproximationLayer) -> NilClass
    def assign: (o: Cv::Ptr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉GeluApproximationLayer≻) -> Cv::Ptr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉GeluApproximationLayer≻
    def get: () -> Cv::Dnn::GeluApproximationLayer
    def empty?: () -> TrueClass
    def initialize_copy: (o: Cv::Ptr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉GeluApproximationLayer≻) -> NilClass
    def release: () -> NilClass
    def reset: () -> NilClass
  end
end
