module Cv
  class QRCodeDetectorAruco
    def get_aruco_parameters: () -> Cv::Aruco::DetectorParameters
    def get_detector_parameters: () -> Cv::QRCodeDetectorAruco::Params
    def initialize: () -> NilClass
               | (params: Cv::QRCodeDetectorAruco::Params) -> NilClass
    def set_aruco_parameters: (params: Cv::Aruco::DetectorParameters) -> NilClass
    def set_detector_parameters: (params: Cv::QRCodeDetectorAruco::Params) -> Cv::QRCodeDetectorAruco
  end
end
