module Cv
  class QRCodeEncoder
    def encode: (encoded_info: Std::String, qrcode: Cv::debug_build_guard::OutputArray) -> void
    def encode_structured_append: (encoded_info: Std::String, qrcodes: Cv::debug_build_guard::OutputArray) -> void
  end
end
