module Cv
  class QRCodeEncoder
    def encode: (encoded_info: String, qrcode: Cv::OutputArray) -> NilClass
    def encode_structured_append: (encoded_info: String, qrcodes: Cv::OutputArray) -> NilClass
  end
end
