module Cv
  class Range
    attr_accessor end: Integer
    attr_accessor start: Integer

    def initialize: () -> NilClass
               | (_start: Integer, _end: Integer) -> NilClass
    def !=: (arg_0: Cv::Range) -> TrueClass
    def &: (arg_0: Cv::Range) -> Cv::Range
    def &=: (arg_0: Cv::Range) -> Cv::Range
    def +: (arg_0: Integer) -> Cv::Range
    def -: (arg_0: Integer) -> Cv::Range
    def ==: (arg_0: Cv::Range) -> TrueClass
    def empty?: () -> TrueClass
    def size: () -> Integer
  end
end
