module Cv
  class Rect2l
    attr_accessor height: Integer
    attr_accessor width: Integer
    attr_accessor x: Integer
    attr_accessor y: Integer

    def !=: (arg_0: Cv::Rect2l) -> TrueClass
    def +: (arg_0: Cv::Size2l) -> Cv::Rect2l
      | (arg_0: Cv::Point2l) -> Cv::Rect2l
    def initialize: (org: Cv::Point2l, sz: Cv::Size2l) -> NilClass
               | (pt1: Cv::Point2l, pt2: Cv::Point2l) -> NilClass
               | () -> NilClass
               | (_x: Integer, _y: Integer, _width: Integer, _height: Integer) -> NilClass
    def -: (arg_0: Cv::Size2l) -> Cv::Rect2l
      | (arg_0: Cv::Point2l) -> Cv::Rect2l
    def ==: (arg_0: Cv::Rect2l) -> TrueClass
    def area: () -> Integer
    def assign_minus: (arg_0: Cv::Point2l) -> Cv::Rect2l
                 | (arg_0: Cv::Size2l) -> Cv::Rect2l
    def assign_plus: (arg_0: Cv::Size2l) -> Cv::Rect2l
                | (arg_0: Cv::Point2l) -> Cv::Rect2l
    def br: () -> Cv::Point2l
    def contains?: (pt: Cv::Point2l) -> TrueClass
    def empty?: () -> TrueClass
    def initialize_copy: (r: Cv::Rect2l) -> NilClass
    def inspect: () -> String
    def size: () -> Cv::Size2l
    def tl: () -> Cv::Point2l
    def |: (arg_0: Cv::Rect2l) -> Cv::Rect2l
    def |=: (arg_0: Cv::Rect2l) -> Cv::Rect2l
  end
end
