module Cv
  class Rect2f
    attr_accessor height: Float
    attr_accessor width: Float
    attr_accessor x: Float
    attr_accessor y: Float

    def !=: (arg_0: Cv::Rect2f) -> TrueClass
    def +: (arg_0: Cv::Size2f) -> Cv::Rect2f
      | (arg_0: Cv::Point2f) -> Cv::Rect2f
    def initialize: (org: Cv::Point2f, sz: Cv::Size2f) -> NilClass
               | () -> NilClass
               | (pt1: Cv::Point2f, pt2: Cv::Point2f) -> NilClass
               | (_x: Float, _y: Float, _width: Float, _height: Float) -> NilClass
    def -: (arg_0: Cv::Size2f) -> Cv::Rect2f
      | (arg_0: Cv::Point2f) -> Cv::Rect2f
    def ==: (arg_0: Cv::Rect2f) -> TrueClass
    def area: () -> Float
    def assign: (r: Cv::Rect2f) -> Cv::Rect2f
           | (r: Cv::Rect2f) -> Cv::Rect2f
    def assign_minus: (arg_0: Cv::Point2f) -> Cv::Rect2f
                 | (arg_0: Cv::Size2f) -> Cv::Rect2f
    def assign_plus: (arg_0: Cv::Size2f) -> Cv::Rect2f
                | (arg_0: Cv::Point2f) -> Cv::Rect2f
    def br: () -> Cv::Point2f
    def contains?: (pt: Cv::Point2f) -> TrueClass
    def empty?: () -> TrueClass
    def initialize_copy: (r: Cv::Rect2f) -> NilClass
    def inspect: () -> String
    def size: () -> Cv::Size2f
    def tl: () -> Cv::Point2f
    def |: (arg_0: Cv::Rect2f) -> Cv::Rect2f
    def |=: (arg_0: Cv::Rect2f) -> Cv::Rect2f
  end
end
