module Cv
  class Rect2w
    attr_accessor height: Integer
    attr_accessor width: Integer
    attr_accessor x: Integer
    attr_accessor y: Integer

    def !=: (arg_0: Cv::Rect2w) -> TrueClass
    def +: (arg_0: Cv::Size2w) -> Cv::Rect2w
      | (arg_0: Cv::Point2w) -> Cv::Rect2w
    def initialize: (org: Cv::Point2w, sz: Cv::Size2w) -> NilClass
               | () -> NilClass
               | (pt1: Cv::Point2w, pt2: Cv::Point2w) -> NilClass
               | (_x: Integer, _y: Integer, _width: Integer, _height: Integer) -> NilClass
    def -: (arg_0: Cv::Size2w) -> Cv::Rect2w
      | (arg_0: Cv::Point2w) -> Cv::Rect2w
    def ==: (arg_0: Cv::Rect2w) -> TrueClass
    def area: () -> Integer
    def assign: (r: Cv::Rect2w) -> Cv::Rect2w
           | (r: Cv::Rect2w) -> Cv::Rect2w
    def assign_minus: (arg_0: Cv::Point2w) -> Cv::Rect2w
                 | (arg_0: Cv::Size2w) -> Cv::Rect2w
    def assign_plus: (arg_0: Cv::Size2w) -> Cv::Rect2w
                | (arg_0: Cv::Point2w) -> Cv::Rect2w
    def br: () -> Cv::Point2w
    def contains?: (pt: Cv::Point2w) -> TrueClass
    def empty?: () -> TrueClass
    def initialize_copy: (r: Cv::Rect2w) -> NilClass
    def inspect: () -> String
    def size: () -> Cv::Size2w
    def tl: () -> Cv::Point2w
    def |: (arg_0: Cv::Rect2w) -> Cv::Rect2w
    def |=: (arg_0: Cv::Rect2w) -> Cv::Rect2w
  end
end
