module Cv
  class Rect2b
    attr_accessor height: String
    attr_accessor width: String
    attr_accessor x: String
    attr_accessor y: String

    def !=: (arg_0: Cv::Rect2b) -> TrueClass
    def +: (arg_0: Cv::Size2b) -> Cv::Rect2b
      | (arg_0: Cv::Point2b) -> Cv::Rect2b
    def initialize: (org: Cv::Point2b, sz: Cv::Size2b) -> NilClass
               | (pt1: Cv::Point2b, pt2: Cv::Point2b) -> NilClass
               | () -> NilClass
               | (_x: String, _y: String, _width: String, _height: String) -> NilClass
    def -: (arg_0: Cv::Size2b) -> Cv::Rect2b
      | (arg_0: Cv::Point2b) -> Cv::Rect2b
    def ==: (arg_0: Cv::Rect2b) -> TrueClass
    def area: () -> String
    def assign_minus: (arg_0: Cv::Point2b) -> Cv::Rect2b
                 | (arg_0: Cv::Size2b) -> Cv::Rect2b
    def assign_plus: (arg_0: Cv::Size2b) -> Cv::Rect2b
                | (arg_0: Cv::Point2b) -> Cv::Rect2b
    def br: () -> Cv::Point2b
    def contains?: (pt: Cv::Point2b) -> TrueClass
    def empty?: () -> TrueClass
    def initialize_copy: (r: Cv::Rect2b) -> NilClass
    def inspect: () -> String
    def size: () -> Cv::Size2b
    def tl: () -> Cv::Point2b
    def |: (arg_0: Cv::Rect2b) -> Cv::Rect2b
    def |=: (arg_0: Cv::Rect2b) -> Cv::Rect2b
  end
end
