module Cv
  class Rect
    attr_accessor height: Integer
    attr_accessor width: Integer
    attr_accessor x: Integer
    attr_accessor y: Integer

    def !=: (arg_0: Cv::Rect) -> TrueClass
    def +: (arg_0: Cv::Size) -> Cv::Rect
      | (arg_0: Cv::Point) -> Cv::Rect
    def initialize: (org: Cv::Point, sz: Cv::Size) -> NilClass
               | (pt1: Cv::Point, pt2: Cv::Point) -> NilClass
               | () -> NilClass
               | (_x: Integer, _y: Integer, _width: Integer, _height: Integer) -> NilClass
    def -: (arg_0: Cv::Size) -> Cv::Rect
      | (arg_0: Cv::Point) -> Cv::Rect
    def ==: (arg_0: Cv::Rect) -> TrueClass
    def area: () -> Integer
    def assign_minus: (arg_0: Cv::Point) -> Cv::Rect
                 | (arg_0: Cv::Size) -> Cv::Rect
    def assign_plus: (arg_0: Cv::Size) -> Cv::Rect
                | (arg_0: Cv::Point) -> Cv::Rect
    def br: () -> Cv::Point
    def contains?: (pt: Cv::Point) -> TrueClass
    def empty?: () -> TrueClass
    def initialize_copy: (r: Cv::Rect) -> NilClass
    def inspect: () -> String
    def size: () -> Cv::Size
    def tl: () -> Cv::Point
    def |: (arg_0: Cv::Rect) -> Cv::Rect
    def |=: (arg_0: Cv::Rect) -> Cv::Rect
  end
end
