module Cv
  class RotatedRect
    attr_accessor angle: Float
    attr_accessor center: Cv::Point2f
    attr_accessor size: Cv::Size2f

    def bounding_rect: () -> Cv::Rect2i
    def bounding_rect2f: () -> Cv::Rect2f
    def initialize: () -> NilClass
               | (point1: Cv::Point2f, point2: Cv::Point2f, point3: Cv::Point2f) -> NilClass
               | (center: Cv::Point2f, size: Cv::Size2f, angle: Float) -> NilClass
    def points: (pts: Std::Vector≺cv꞉꞉Point_≺float≻≻) -> NilClass
           | (pts: Cv::Point2f) -> NilClass
  end
end
