module Cv
  class Scalar
    def conj: () -> Cv::Scalar
    def initialize: () -> NilClass
               | (v0: Float) -> NilClass
               | (v0: Float, v1: Float, v2: Float, v3: Float) -> NilClass
    def initialize_copy: (s: Cv::Scalar) -> NilClass
    def is_real?: () -> TrueClass
    def mul: (a: Cv::Scalar, scale: Float) -> Cv::Scalar
  end
end
