module Cv
  class Scalar
    def conj: () -> Cv::Scalar_≺double≻
    def initialize: () -> void
               | (v0: Float) -> void
               | (v0: Float, v1: Float, v2: Float, v3: Float) -> void
    def initialize_copy: (s: Cv::Scalar_≺double≻) -> void
    def is_real?: () -> bool
    def mul: (a: Cv::Scalar_≺double≻, scale: Float) -> Cv::Scalar_≺double≻
  end
end
