module Cv
  class Size2d
    attr_accessor height: Float
    attr_accessor width: Float

    def initialize: () -> NilClass
               | (pt: Cv::Point2d) -> NilClass
               | (_width: Float, _height: Float) -> NilClass
    def !=: (arg_0: Cv::Size2d) -> TrueClass
    def *: (arg_0: Float) -> Cv::Size2d
    def +: (arg_0: Cv::Size2d) -> Cv::Size2d
    def -: (arg_0: Cv::Size2d) -> Cv::Size2d
    def /: (arg_0: Float) -> Cv::Size2d
    def ==: (arg_0: Cv::Size2d) -> TrueClass
    def area: () -> Float
    def assign_divide: (arg_0: Float) -> Cv::Size2d
    def assign_minus: (arg_0: Cv::Size2d) -> Cv::Size2d
    def assign_multiply: (arg_0: Float) -> Cv::Size2d
    def assign_plus: (arg_0: Cv::Size2d) -> Cv::Size2d
    def empty?: () -> TrueClass
    def aspect_ratio: () -> Float
    def initialize_copy: (sz: Cv::Size2d) -> NilClass
    def inspect: () -> String
    def to_s: () -> String
  end
end
