module Cv
  class Size2f
    attr_accessor height: Float
    attr_accessor width: Float

    def initialize: () -> void
               | (pt: Cv::Point_≺float≻) -> void
               | (_width: Float, _height: Float) -> void
    def !=: (arg_0: Cv::Size_≺float≻) -> bool
    def *: (arg_0: Float) -> Cv::Size_≺float≻
    def +: (arg_0: Cv::Size_≺float≻) -> Cv::Size_≺float≻
    def -: (arg_0: Cv::Size_≺float≻) -> Cv::Size_≺float≻
    def /: (arg_0: Float) -> Cv::Size_≺float≻
    def ==: (arg_0: Cv::Size_≺float≻) -> bool
    def area: () -> Float
    def assign_divide: (arg_0: Float) -> Cv::Size_≺float≻
    def assign_minus: (arg_0: Cv::Size_≺float≻) -> Cv::Size_≺float≻
    def assign_multiply: (arg_0: Float) -> Cv::Size_≺float≻
    def assign_plus: (arg_0: Cv::Size_≺float≻) -> Cv::Size_≺float≻
    def empty?: () -> bool
    def aspect_ratio: () -> Float
    def initialize_copy: (sz: Cv::Size_≺float≻) -> void
    def inspect: () -> Std::String
    def to_s: () -> Std::String
  end
end
