module Cv
  class Size2w
    attr_accessor height: Integer
    attr_accessor width: Integer

    def initialize: () -> NilClass
               | (pt: Cv::Point2w) -> NilClass
               | (_width: Integer, _height: Integer) -> NilClass
    def !=: (arg_0: Cv::Size2w) -> TrueClass
    def *: (arg_0: Integer) -> Cv::Size2w
    def +: (arg_0: Cv::Size2w) -> Cv::Size2w
    def -: (arg_0: Cv::Size2w) -> Cv::Size2w
    def /: (arg_0: Integer) -> Cv::Size2w
    def ==: (arg_0: Cv::Size2w) -> TrueClass
    def area: () -> Integer
    def aspect_ratio: () -> Float
    def assign: (sz: Cv::Size2w) -> Cv::Size2w
           | (sz: Cv::Size2w) -> Cv::Size2w
    def assign_multiply: (arg_0: Integer) -> Cv::Size2w
    def assign_plus: (arg_0: Cv::Size2w) -> Cv::Size2w
    def empty?: () -> TrueClass
    def assign_minus: (arg_0: Cv::Size2w) -> Cv::Size2w
    def assign_divide: (arg_0: Integer) -> Cv::Size2w
    def initialize_copy: (sz: Cv::Size2w) -> NilClass
    def inspect: () -> String
    def to_s: () -> String
  end
end
