module Cv
  class SparseMatConstIterator4d
    def !=: (arg_0: Cv::SparseMatConstIterator4d) -> TrueClass
    def initialize: () -> NilClass
               | (_m: Cv::SparseMat4d) -> NilClass
               | (_m: Cv::SparseMat) -> NilClass
    def ==: (arg_0: Cv::SparseMatConstIterator4d) -> TrueClass
    def dereference: () -> Cv::Vec4d
    def increment: () -> Cv::SparseMatConstIterator4d
              | (: Integer) -> Cv::SparseMatConstIterator4d
    def initialize_copy: (it: Cv::SparseMatConstIterator4d) -> NilClass
  end
end
