module Cv
  class SparseMatConstIterator4d
    def assign: (it: Cv::SparseMatConstIterator4d) -> Cv::SparseMatConstIterator4d
    def dereference: () -> Cv::Vec4d
    def increment: () -> Cv::SparseMatConstIterator4d
    def increment_post: (arg_0: Integer) -> Cv::SparseMatConstIterator4d
    def initialize: () -> NilClass
               | (_m: Cv::SparseMat) -> NilClass
               | (_m: Cv::SparseMat4d) -> NilClass
    def initialize_copy: (it: Cv::SparseMatConstIterator4d) -> NilClass
  end
end
