module Cv
  class SparseMatConstIterator4s
    def !=: (arg_0: Cv::SparseMatConstIterator4s) -> TrueClass
    def initialize: () -> NilClass
               | (_m: Cv::SparseMat4s) -> NilClass
               | (_m: Cv::SparseMat) -> NilClass
    def ==: (arg_0: Cv::SparseMatConstIterator4s) -> TrueClass
    def dereference: () -> Cv::Vec4s
    def increment: () -> Cv::SparseMatConstIterator4s
              | (: Integer) -> Cv::SparseMatConstIterator4s
    def initialize_copy: (it: Cv::SparseMatConstIterator4s) -> NilClass
  end
end
