module Cv
  class SparsePyrLKOpticalFlow
    def get_flags: () -> Integer
    def get_max_level: () -> Integer
    def get_min_eig_threshold: () -> Float
    def get_term_criteria: () -> Cv::TermCriteria
    def get_win_size: () -> Cv::Size_≺int≻
    def set_flags: (flags: Integer) -> void
    def set_max_level: (max_level: Integer) -> void
    def set_min_eig_threshold: (min_eig_threshold: Float) -> void
    def set_term_criteria: (crit: Cv::TermCriteria) -> void
    def set_win_size: (win_size: Cv::Size_≺int≻) -> void
  end
end
