module Cv
  class SparseMatConstIterator2f
    def !=: (arg_0: Cv::SparseMatConstIterator_≺cv꞉꞉Vec≺float‚ 2≻≻) -> bool
    def initialize: () -> void
               | (_m: Cv::SparseMat_≺cv꞉꞉Vec≺float‚ 2≻≻) -> void
               | (_m: Cv::SparseMat) -> void
    def ==: (arg_0: Cv::SparseMatConstIterator_≺cv꞉꞉Vec≺float‚ 2≻≻) -> bool
    def dereference: () -> Cv::Vec≺float‚ 2≻
    def increment: () -> Cv::SparseMatConstIterator_≺cv꞉꞉Vec≺float‚ 2≻≻
              | (: Integer) -> Cv::SparseMatConstIterator_≺cv꞉꞉Vec≺float‚ 2≻≻
    def initialize_copy: (it: Cv::SparseMatConstIterator_≺cv꞉꞉Vec≺float‚ 2≻≻) -> void
  end
end
