module Cv
  class SparseMatConstIterator
    attr_accessor hashidx: Integer
    attr_accessor m: Cv::SparseMat
    attr_accessor ptr: Rice::Buffer≺unsigned char∗≻

    def increment: () -> Cv::SparseMatConstIterator
              | (: Integer) -> Cv::SparseMatConstIterator
    def initialize: () -> void
               | (_m: Cv::SparseMat) -> void
    def initialize_copy: (it: Cv::SparseMatConstIterator) -> void
    def node: () -> Cv::SparseMat::Node
    def seek_end: () -> void
  end
end
