module Cv
  class SparseMatConstIterator1i
    def !=: (arg_0: Cv::SparseMatConstIterator_≺int≻) -> bool
    def initialize: () -> void
               | (_m: Cv::SparseMat_≺int≻) -> void
               | (_m: Cv::SparseMat) -> void
    def ==: (arg_0: Cv::SparseMatConstIterator_≺int≻) -> bool
    def dereference: () -> Int
    def increment: () -> Cv::SparseMatConstIterator_≺int≻
              | (: Integer) -> Cv::SparseMatConstIterator_≺int≻
    def initialize_copy: (it: Cv::SparseMatConstIterator_≺int≻) -> void
  end
end
