module Cv
  class SparseMatIterator2i
    def dereference: () -> Cv::Vec≺int‚ 2≻
    def increment: () -> Cv::SparseMatIterator_≺cv꞉꞉Vec≺int‚ 2≻≻
              | (: Integer) -> Cv::SparseMatIterator_≺cv꞉꞉Vec≺int‚ 2≻≻
    def initialize: () -> void
               | (_m: Cv::SparseMat) -> void
               | (_m: Cv::SparseMat_≺cv꞉꞉Vec≺int‚ 2≻≻) -> void
    def initialize_copy: (it: Cv::SparseMatIterator_≺cv꞉꞉Vec≺int‚ 2≻≻) -> void
  end
end
