module Cv
  class SparseMatConstIterator3d
    def !=: (arg_0: Cv::SparseMatConstIterator3d) -> TrueClass
    def initialize: () -> NilClass
               | (_m: Cv::SparseMat3d) -> NilClass
               | (_m: Cv::SparseMat) -> NilClass
    def ==: (arg_0: Cv::SparseMatConstIterator3d) -> TrueClass
    def dereference: () -> Cv::Vec3d
    def increment: () -> Cv::SparseMatConstIterator3d
              | (: Integer) -> Cv::SparseMatConstIterator3d
    def initialize_copy: (it: Cv::SparseMatConstIterator3d) -> NilClass
  end
end
