module Cv
  class SparseMat1b
    def []: (arg_0: Rice::Pointer≺int≻) -> String
       | (arg_0: Integer) -> String
       | (arg_0: Integer, arg_1: Integer) -> String
       | (arg_0: Integer, arg_1: Integer, arg_2: Integer) -> String
    def []=: (arg_0: Integer, arg_1: String) -> String
        | (arg_0: Rice::Pointer≺int≻, arg_1: String) -> String
        | (arg_0: Integer, arg_1: Integer, arg_2: String) -> String
        | (arg_0: Integer, arg_1: Integer, arg_2: Integer, arg_3: String) -> String
    def initialize: () -> NilClass
               | (m: Cv::SparseMat) -> NilClass
               | (m: Cv::Mat) -> NilClass
               | (dims: Integer, _sizes: Rice::Pointer≺int≻) -> NilClass
    def begin: () -> Cv::SparseMatIterator1b
    def clone: () -> Cv::SparseMat1b
    def create: (dims: Integer, _sizes: Rice::Pointer≺int≻) -> NilClass
    def depth: () -> Integer
    def end: () -> Cv::SparseMatIterator1b
    def channels: () -> Integer
    def initialize_copy: (m: Cv::SparseMat1b) -> NilClass
    def type: () -> Integer
  end
end
