module Cv
  class SparseMatIterator4d
    def dereference: () -> Cv::Vec4d
    def increment: () -> Cv::SparseMatIterator4d
              | (: Integer) -> Cv::SparseMatIterator4d
    def initialize: () -> NilClass
               | (_m: Cv::SparseMat) -> NilClass
               | (_m: Cv::SparseMat4d) -> NilClass
    def initialize_copy: (it: Cv::SparseMatIterator4d) -> NilClass
  end
end
