module Cv
  class SparseMatConstIterator1s
    def !=: (arg_0: Cv::SparseMatConstIterator1s) -> TrueClass
    def initialize: () -> NilClass
               | (_m: Cv::SparseMat1s) -> NilClass
               | (_m: Cv::SparseMat) -> NilClass
    def ==: (arg_0: Cv::SparseMatConstIterator1s) -> TrueClass
    def dereference: () -> Integer
    def increment: () -> Cv::SparseMatConstIterator1s
              | (: Integer) -> Cv::SparseMatConstIterator1s
    def initialize_copy: (it: Cv::SparseMatConstIterator1s) -> NilClass
  end
end
