module Cv
  class SparseMatIterator6f
    def dereference: () -> Cv::Vec6f
    def increment: () -> Cv::SparseMatIterator6f
              | (: Integer) -> Cv::SparseMatIterator6f
    def initialize: () -> NilClass
               | (_m: Cv::SparseMat) -> NilClass
               | (_m: Cv::SparseMat6f) -> NilClass
    def initialize_copy: (it: Cv::SparseMatIterator6f) -> NilClass
  end
end
