module Cv
  class SparseMatConstIterator1i
    def !=: (arg_0: Cv::SparseMatConstIterator1i) -> TrueClass
    def initialize: () -> NilClass
               | (_m: Cv::SparseMat1i) -> NilClass
               | (_m: Cv::SparseMat) -> NilClass
    def ==: (arg_0: Cv::SparseMatConstIterator1i) -> TrueClass
    def dereference: () -> Integer
    def increment: () -> Cv::SparseMatConstIterator1i
              | (: Integer) -> Cv::SparseMatConstIterator1i
    def initialize_copy: (it: Cv::SparseMatConstIterator1i) -> NilClass
  end
end
