module Cv
  class SparseMatConstIterator
    attr_accessor hashidx: Integer
    attr_accessor m: Cv::SparseMat
    attr_accessor ptr: Rice::Pointer≺unsigned char≻

    def increment: () -> Cv::SparseMatConstIterator
              | (: Integer) -> Cv::SparseMatConstIterator
    def initialize: () -> NilClass
               | (_m: Cv::SparseMat) -> NilClass
    def initialize_copy: (it: Cv::SparseMatConstIterator) -> NilClass
    def node: () -> Cv::SparseMat::Node
    def seek_end: () -> NilClass
  end
end
