module Cv
  class SparseMat1d
    def []: (arg_0: Rice::Pointer≺int≻) -> Float
       | (arg_0: Integer) -> Float
       | (arg_0: Integer, arg_1: Integer) -> Float
       | (arg_0: Integer, arg_1: Integer, arg_2: Integer) -> Float
    def []=: (arg_0: Integer, arg_1: Float) -> Float
        | (arg_0: Rice::Pointer≺int≻, arg_1: Float) -> Float
        | (arg_0: Integer, arg_1: Integer, arg_2: Float) -> Float
        | (arg_0: Integer, arg_1: Integer, arg_2: Integer, arg_3: Float) -> Float
    def initialize: () -> NilClass
               | (m: Cv::SparseMat) -> NilClass
               | (m: Cv::Mat) -> NilClass
               | (dims: Integer, _sizes: Rice::Pointer≺int≻) -> NilClass
    def begin: () -> Cv::SparseMatIterator1d
    def clone: () -> Cv::SparseMat1d
    def create: (dims: Integer, _sizes: Rice::Pointer≺int≻) -> NilClass
    def depth: () -> Integer
    def end: () -> Cv::SparseMatIterator1d
    def channels: () -> Integer
    def initialize_copy: (m: Cv::SparseMat1d) -> NilClass
    def type: () -> Integer
  end
end
