module Cv
  class SparseMatConstIterator2d
    def !=: (arg_0: Cv::SparseMatConstIterator2d) -> TrueClass
    def initialize: () -> NilClass
               | (_m: Cv::SparseMat2d) -> NilClass
               | (_m: Cv::SparseMat) -> NilClass
    def ==: (arg_0: Cv::SparseMatConstIterator2d) -> TrueClass
    def dereference: () -> Cv::Vec2d
    def increment: () -> Cv::SparseMatConstIterator2d
              | (: Integer) -> Cv::SparseMatConstIterator2d
    def initialize_copy: (it: Cv::SparseMatConstIterator2d) -> NilClass
  end
end
