module Cv
  class SparseMatConstIterator2w
    def !=: (arg_0: Cv::SparseMatConstIterator2w) -> TrueClass
    def initialize: () -> NilClass
               | (_m: Cv::SparseMat2w) -> NilClass
               | (_m: Cv::SparseMat) -> NilClass
    def ==: (arg_0: Cv::SparseMatConstIterator2w) -> TrueClass
    def dereference: () -> Cv::Vec2w
    def increment: () -> Cv::SparseMatConstIterator2w
              | (: Integer) -> Cv::SparseMatConstIterator2w
    def initialize_copy: (it: Cv::SparseMatConstIterator2w) -> NilClass
  end
end
