module Cv
  class SparseMatIterator2b
    def dereference: () -> Cv::Vec2b
    def increment: () -> Cv::SparseMatIterator2b
              | (: Integer) -> Cv::SparseMatIterator2b
    def initialize: () -> NilClass
               | (_m: Cv::SparseMat) -> NilClass
               | (_m: Cv::SparseMat2b) -> NilClass
    def initialize_copy: (it: Cv::SparseMatIterator2b) -> NilClass
  end
end
