module Cv
  class SparseMatConstIterator4w
    def assign: (it: Cv::SparseMatConstIterator4w) -> Cv::SparseMatConstIterator4w
    def dereference: () -> Cv::Vec4w
    def increment: () -> Cv::SparseMatConstIterator4w
    def increment_post: (arg_0: Integer) -> Cv::SparseMatConstIterator4w
    def initialize: () -> NilClass
               | (_m: Cv::SparseMat) -> NilClass
               | (_m: Cv::SparseMat4w) -> NilClass
    def initialize_copy: (it: Cv::SparseMatConstIterator4w) -> NilClass
  end
end
