module Cv
  class SparseMat4w
    def []: (arg_0: Rice::Buffer≺int const∗≻) -> Cv::Vec≺unsigned short‚ 4≻
       | (arg_0: Integer) -> Cv::Vec≺unsigned short‚ 4≻
       | (arg_0: Integer, arg_1: Integer) -> Cv::Vec≺unsigned short‚ 4≻
       | (arg_0: Integer, arg_1: Integer, arg_2: Integer) -> Cv::Vec≺unsigned short‚ 4≻
    def []=: (arg_0: Integer, arg_1: Cv::Vec≺unsigned short‚ 4≻) -> Cv::Vec≺unsigned short‚ 4≻
        | (arg_0: Rice::Buffer≺int const∗≻, arg_1: Cv::Vec≺unsigned short‚ 4≻) -> Cv::Vec≺unsigned short‚ 4≻
        | (arg_0: Integer, arg_1: Integer, arg_2: Cv::Vec≺unsigned short‚ 4≻) -> Cv::Vec≺unsigned short‚ 4≻
        | (arg_0: Integer, arg_1: Integer, arg_2: Integer, arg_3: Cv::Vec≺unsigned short‚ 4≻) -> Cv::Vec≺unsigned short‚ 4≻
    def initialize: () -> void
               | (m: Cv::SparseMat) -> void
               | (m: Cv::Mat) -> void
               | (dims: Integer, _sizes: Rice::Buffer≺int const∗≻) -> void
    def begin: () -> Cv::SparseMatIterator_≺cv꞉꞉Vec≺unsigned short‚ 4≻≻
    def clone: () -> Cv::SparseMat_≺cv꞉꞉Vec≺unsigned short‚ 4≻≻
    def create: (dims: Integer, _sizes: Rice::Buffer≺int const∗≻) -> void
    def depth: () -> Integer
    def end: () -> Cv::SparseMatIterator_≺cv꞉꞉Vec≺unsigned short‚ 4≻≻
    def channels: () -> Integer
    def initialize_copy: (m: Cv::SparseMat_≺cv꞉꞉Vec≺unsigned short‚ 4≻≻) -> void
    def type: () -> Integer
  end
end
