module Cv
  class SparseMat1d
    def []: (arg_0: Rice::Buffer≺int const∗≻) -> Double
       | (arg_0: Integer) -> Double
       | (arg_0: Integer, arg_1: Integer) -> Double
       | (arg_0: Integer, arg_1: Integer, arg_2: Integer) -> Double
    def []=: (arg_0: Integer, arg_1: Double) -> Double
        | (arg_0: Rice::Buffer≺int const∗≻, arg_1: Double) -> Double
        | (arg_0: Integer, arg_1: Integer, arg_2: Double) -> Double
        | (arg_0: Integer, arg_1: Integer, arg_2: Integer, arg_3: Double) -> Double
    def initialize: () -> void
               | (m: Cv::SparseMat) -> void
               | (m: Cv::Mat) -> void
               | (dims: Integer, _sizes: Rice::Buffer≺int const∗≻) -> void
    def begin: () -> Cv::SparseMatIterator_≺double≻
    def clone: () -> Cv::SparseMat_≺double≻
    def create: (dims: Integer, _sizes: Rice::Buffer≺int const∗≻) -> void
    def depth: () -> Integer
    def end: () -> Cv::SparseMatIterator_≺double≻
    def channels: () -> Integer
    def initialize_copy: (m: Cv::SparseMat_≺double≻) -> void
    def type: () -> Integer
  end
end
