module Cv
  class SparseMatConstIterator3s
    def !=: (arg_0: Cv::SparseMatConstIterator3s) -> TrueClass
    def initialize: () -> NilClass
               | (_m: Cv::SparseMat3s) -> NilClass
               | (_m: Cv::SparseMat) -> NilClass
    def ==: (arg_0: Cv::SparseMatConstIterator3s) -> TrueClass
    def dereference: () -> Cv::Vec3s
    def increment: () -> Cv::SparseMatConstIterator3s
              | (: Integer) -> Cv::SparseMatConstIterator3s
    def initialize_copy: (it: Cv::SparseMatConstIterator3s) -> NilClass
  end
end
