module Cv
  class SparseMatIterator4s
    def dereference: () -> Cv::Vec≺short‚ 4≻
    def increment: () -> Cv::SparseMatIterator_≺cv꞉꞉Vec≺short‚ 4≻≻
              | (: Integer) -> Cv::SparseMatIterator_≺cv꞉꞉Vec≺short‚ 4≻≻
    def initialize: () -> void
               | (_m: Cv::SparseMat) -> void
               | (_m: Cv::SparseMat_≺cv꞉꞉Vec≺short‚ 4≻≻) -> void
    def initialize_copy: (it: Cv::SparseMatIterator_≺cv꞉꞉Vec≺short‚ 4≻≻) -> void
  end
end
