module Cv
  class SparseMatIterator4i
    def dereference: () -> Cv::Vec4i
    def increment: () -> Cv::SparseMatIterator4i
              | (: Integer) -> Cv::SparseMatIterator4i
    def initialize: () -> NilClass
               | (_m: Cv::SparseMat) -> NilClass
               | (_m: Cv::SparseMat4i) -> NilClass
    def initialize_copy: (it: Cv::SparseMatIterator4i) -> NilClass
  end
end
