module Cv
  class SparseMatConstIterator2d
    def assign: (it: Cv::SparseMatConstIterator2d) -> Cv::SparseMatConstIterator2d
    def dereference: () -> Cv::Vec2d
    def increment: () -> Cv::SparseMatConstIterator2d
    def increment_post: (arg_0: Integer) -> Cv::SparseMatConstIterator2d
    def initialize: () -> NilClass
               | (_m: Cv::SparseMat) -> NilClass
               | (_m: Cv::SparseMat2d) -> NilClass
    def initialize_copy: (it: Cv::SparseMatConstIterator2d) -> NilClass
  end
end
