module Cv
  class SparseMat1i
    def []: (arg_0: Rice::Pointer≺int≻) -> Integer
       | (arg_0: Integer) -> Integer
       | (idx: Rice::Pointer≺int≻, hashval: Rice::Pointer≺unsigned Int64≻) -> Integer
       | (i0: Integer, hashval: Rice::Pointer≺unsigned Int64≻) -> Integer
       | (arg_0: Integer, arg_1: Integer) -> Integer
       | (i0: Integer, i1: Integer, hashval: Rice::Pointer≺unsigned Int64≻) -> Integer
       | (arg_0: Integer, arg_1: Integer, arg_2: Integer) -> Integer
       | (i0: Integer, i1: Integer, i2: Integer, hashval: Rice::Pointer≺unsigned Int64≻) -> Integer
    def initialize: (m: Cv::SparseMat) -> NilClass
               | (m: Cv::Mat) -> NilClass
               | () -> NilClass
               | (dims: Integer, _sizes: Rice::Pointer≺int≻) -> NilClass
    def []=: (arg_0: Rice::Pointer≺int≻, arg_1: Integer) -> Integer
        | (arg_0: Integer, arg_1: Integer) -> Integer
        | (arg_0: Integer, arg_1: Integer, arg_2: Integer) -> Integer
        | (arg_0: Integer, arg_1: Integer, arg_2: Integer, arg_3: Integer) -> Integer
    def assign: (m: Cv::SparseMat1i) -> Cv::SparseMat1i
           | (m: Cv::SparseMat) -> Cv::SparseMat1i
           | (m: Cv::Mat) -> Cv::SparseMat1i
    def begin: () -> Cv::SparseMatIterator1i
    def clone: () -> Cv::SparseMat1i
    def create: (dims: Integer, _sizes: Rice::Pointer≺int≻) -> NilClass
    def depth: () -> Integer
    def end: () -> Cv::SparseMatIterator1i
    def channels: () -> Integer
    def initialize_copy: (m: Cv::SparseMat1i) -> NilClass
    def ref: (idx: Rice::Pointer≺int≻, hashval: Rice::Pointer≺unsigned Int64≻) -> Integer
        | (i0: Integer, hashval: Rice::Pointer≺unsigned Int64≻) -> Integer
        | (i0: Integer, i1: Integer, hashval: Rice::Pointer≺unsigned Int64≻) -> Integer
        | (i0: Integer, i1: Integer, i2: Integer, hashval: Rice::Pointer≺unsigned Int64≻) -> Integer
    def type: () -> Integer
  end
end
