module Cv
  class SparseMatIterator1i
    def dereference: () -> Int
    def increment: () -> Cv::SparseMatIterator_≺int≻
              | (: Integer) -> Cv::SparseMatIterator_≺int≻
    def initialize: () -> void
               | (_m: Cv::SparseMat) -> void
               | (_m: Cv::SparseMat_≺int≻) -> void
    def initialize_copy: (it: Cv::SparseMatIterator_≺int≻) -> void
  end
end
