module Cv
  class SparseMatIterator4b
    def dereference: () -> Cv::Vec4b
    def increment: () -> Cv::SparseMatIterator4b
              | (: Integer) -> Cv::SparseMatIterator4b
    def initialize: () -> NilClass
               | (_m: Cv::SparseMat) -> NilClass
               | (_m: Cv::SparseMat4b) -> NilClass
    def initialize_copy: (it: Cv::SparseMatIterator4b) -> NilClass
  end
end
