module Cv
  class SparseMatConstIterator1w
    def !=: (arg_0: Cv::SparseMatConstIterator1w) -> TrueClass
    def initialize: () -> NilClass
               | (_m: Cv::SparseMat1w) -> NilClass
               | (_m: Cv::SparseMat) -> NilClass
    def ==: (arg_0: Cv::SparseMatConstIterator1w) -> TrueClass
    def dereference: () -> Integer
    def increment: () -> Cv::SparseMatConstIterator1w
              | (: Integer) -> Cv::SparseMatConstIterator1w
    def initialize_copy: (it: Cv::SparseMatConstIterator1w) -> NilClass
  end
end
