module Cv
  class SparseMatConstIterator2i
    def !=: (arg_0: Cv::SparseMatConstIterator2i) -> TrueClass
    def initialize: () -> NilClass
               | (_m: Cv::SparseMat2i) -> NilClass
               | (_m: Cv::SparseMat) -> NilClass
    def ==: (arg_0: Cv::SparseMatConstIterator2i) -> TrueClass
    def dereference: () -> Cv::Vec2i
    def increment: () -> Cv::SparseMatConstIterator2i
              | (: Integer) -> Cv::SparseMatConstIterator2i
    def initialize_copy: (it: Cv::SparseMatConstIterator2i) -> NilClass
  end
end
