module Cv
  class SparseMatIterator1b
    def dereference: () -> String
    def increment: () -> Cv::SparseMatIterator1b
              | (: Integer) -> Cv::SparseMatIterator1b
    def initialize: () -> NilClass
               | (_m: Cv::SparseMat) -> NilClass
               | (_m: Cv::SparseMat1b) -> NilClass
    def initialize_copy: (it: Cv::SparseMatIterator1b) -> NilClass
  end
end
