module Cv
  class SparseMat
    attr_accessor flags: Integer
    attr_accessor hdr: Cv::SparseMat::Hdr

    def initialize: () -> NilClass
               | (m: Cv::Mat) -> NilClass
               | (dims: Integer, _sizes: Rice::Pointer≺int≻, _type: Integer) -> NilClass
    def addref: () -> NilClass
    def assign: (m: Cv::Mat) -> Cv::SparseMat
           | (m: Cv::SparseMat) -> Cv::SparseMat
    def assign_to: (m: Cv::SparseMat, type: Integer) -> NilClass
    def channels: () -> Integer
    def clear: () -> NilClass
    def clone: () -> Cv::SparseMat
    def convert_to: (m: Cv::SparseMat, rtype: Integer, alpha: Float) -> NilClass
               | (m: Cv::Mat, rtype: Integer, alpha: Float, beta: Float) -> NilClass
    def copy_to: (m: Cv::Mat) -> NilClass
            | (m: Cv::SparseMat) -> NilClass
    def create: (dims: Integer, _sizes: Rice::Pointer≺int≻, _type: Integer) -> NilClass
    def depth: () -> Integer
    def dims: () -> Integer
    def elem_size: () -> Integer
    def elem_size1: () -> Integer
    def erase: (idx: Rice::Pointer≺int≻, hashval: Rice::Pointer≺unsigned Int64≻) -> NilClass
          | (i0: Integer, i1: Integer, hashval: Rice::Pointer≺unsigned Int64≻) -> NilClass
          | (i0: Integer, i1: Integer, i2: Integer, hashval: Rice::Pointer≺unsigned Int64≻) -> NilClass
    def hash: (idx: Rice::Pointer≺int≻) -> Integer
         | (i0: Integer) -> Integer
         | (i0: Integer, i1: Integer) -> Integer
         | (i0: Integer, i1: Integer, i2: Integer) -> Integer
    def initialize_copy: (m: Cv::SparseMat) -> NilClass
    def new_node: (idx: Rice::Pointer≺int≻, hashval: Integer) -> Rice::Pointer≺unsigned char≻
    def node: (nidx: Integer) -> Cv::SparseMat::Node
         | (nidx: Integer) -> Cv::SparseMat::Node
    def nzcount: () -> Integer
    def ptr: (idx: Rice::Pointer≺int≻, create_missing: TrueClass, hashval: Rice::Pointer≺unsigned Int64≻) -> Rice::Pointer≺unsigned char≻
        | (i0: Integer, create_missing: TrueClass, hashval: Rice::Pointer≺unsigned Int64≻) -> Rice::Pointer≺unsigned char≻
        | (i0: Integer, i1: Integer, create_missing: TrueClass, hashval: Rice::Pointer≺unsigned Int64≻) -> Rice::Pointer≺unsigned char≻
        | (i0: Integer, i1: Integer, i2: Integer, create_missing: TrueClass, hashval: Rice::Pointer≺unsigned Int64≻) -> Rice::Pointer≺unsigned char≻
    def release: () -> NilClass
    def remove_node: (hidx: Integer, nidx: Integer, previdx: Integer) -> NilClass
    def resize_hash_tab: (newsize: Integer) -> NilClass
    def size: () -> Rice::Pointer≺int≻
         | (i: Integer) -> Integer
    def type: () -> Integer
  end
end
