module Cv
  class SparseMatConstIterator4w
    def !=: (arg_0: Cv::SparseMatConstIterator4w) -> TrueClass
    def initialize: () -> NilClass
               | (_m: Cv::SparseMat4w) -> NilClass
               | (_m: Cv::SparseMat) -> NilClass
    def ==: (arg_0: Cv::SparseMatConstIterator4w) -> TrueClass
    def dereference: () -> Cv::Vec4w
    def increment: () -> Cv::SparseMatConstIterator4w
              | (: Integer) -> Cv::SparseMatConstIterator4w
    def initialize_copy: (it: Cv::SparseMatConstIterator4w) -> NilClass
  end
end
