module Cv
  class SparseMatConstIterator4b
    def !=: (arg_0: Cv::SparseMatConstIterator4b) -> TrueClass
    def initialize: () -> NilClass
               | (_m: Cv::SparseMat4b) -> NilClass
               | (_m: Cv::SparseMat) -> NilClass
    def ==: (arg_0: Cv::SparseMatConstIterator4b) -> TrueClass
    def dereference: () -> Cv::Vec4b
    def increment: () -> Cv::SparseMatConstIterator4b
              | (: Integer) -> Cv::SparseMatConstIterator4b
    def initialize_copy: (it: Cv::SparseMatConstIterator4b) -> NilClass
  end
end
