module Cv
  class SparseMatIterator3b
    def dereference: () -> Cv::Vec3b
    def increment: () -> Cv::SparseMatIterator3b
              | (: Integer) -> Cv::SparseMatIterator3b
    def initialize: () -> NilClass
               | (_m: Cv::SparseMat) -> NilClass
               | (_m: Cv::SparseMat3b) -> NilClass
    def initialize_copy: (it: Cv::SparseMatIterator3b) -> NilClass
  end
end
