module Cv
  class SparseMat1i
    def []: (arg_0: Rice::Pointer≺int≻) -> Integer
       | (arg_0: Integer) -> Integer
       | (arg_0: Integer, arg_1: Integer) -> Integer
       | (arg_0: Integer, arg_1: Integer, arg_2: Integer) -> Integer
    def []=: (arg_0: Integer, arg_1: Integer) -> Integer
        | (arg_0: Rice::Pointer≺int≻, arg_1: Integer) -> Integer
        | (arg_0: Integer, arg_1: Integer, arg_2: Integer) -> Integer
        | (arg_0: Integer, arg_1: Integer, arg_2: Integer, arg_3: Integer) -> Integer
    def initialize: () -> NilClass
               | (m: Cv::SparseMat) -> NilClass
               | (m: Cv::Mat) -> NilClass
               | (dims: Integer, _sizes: Rice::Pointer≺int≻) -> NilClass
    def begin: () -> Cv::SparseMatIterator1i
    def clone: () -> Cv::SparseMat1i
    def create: (dims: Integer, _sizes: Rice::Pointer≺int≻) -> NilClass
    def depth: () -> Integer
    def end: () -> Cv::SparseMatIterator1i
    def channels: () -> Integer
    def initialize_copy: (m: Cv::SparseMat1i) -> NilClass
    def type: () -> Integer
  end
end
