module Cv
  class SparseMatConstIterator3b
    def assign: (it: Cv::SparseMatConstIterator3b) -> Cv::SparseMatConstIterator3b
    def dereference: () -> Cv::Vec3b
    def increment: () -> Cv::SparseMatConstIterator3b
    def increment_post: (arg_0: Integer) -> Cv::SparseMatConstIterator3b
    def initialize: () -> NilClass
               | (_m: Cv::SparseMat) -> NilClass
               | (_m: Cv::SparseMat3b) -> NilClass
    def initialize_copy: (it: Cv::SparseMatConstIterator3b) -> NilClass
  end
end
