module Cv
  class SparseMatConstIterator1d
    def !=: (arg_0: Cv::SparseMatConstIterator1d) -> TrueClass
    def initialize: () -> NilClass
               | (_m: Cv::SparseMat1d) -> NilClass
               | (_m: Cv::SparseMat) -> NilClass
    def ==: (arg_0: Cv::SparseMatConstIterator1d) -> TrueClass
    def dereference: () -> Float
    def increment: () -> Cv::SparseMatConstIterator1d
              | (: Integer) -> Cv::SparseMatConstIterator1d
    def initialize_copy: (it: Cv::SparseMatConstIterator1d) -> NilClass
  end
end
