module Cv
  class SparseMatIterator2d
    def dereference: () -> Cv::Vec2d
    def increment: () -> Cv::SparseMatIterator2d
              | (: Integer) -> Cv::SparseMatIterator2d
    def initialize: () -> NilClass
               | (_m: Cv::SparseMat) -> NilClass
               | (_m: Cv::SparseMat2d) -> NilClass
    def initialize_copy: (it: Cv::SparseMatIterator2d) -> NilClass
  end
end
