module Cv
  class SparseMatIterator3s
    def dereference: () -> Cv::Vec3s
    def increment: () -> Cv::SparseMatIterator3s
              | (: Integer) -> Cv::SparseMatIterator3s
    def initialize: () -> NilClass
               | (_m: Cv::SparseMat) -> NilClass
               | (_m: Cv::SparseMat3s) -> NilClass
    def initialize_copy: (it: Cv::SparseMatIterator3s) -> NilClass
  end
end
