module Cv
  class SparseMatIterator1w
    def dereference: () -> Unsigned short
    def increment: () -> Cv::SparseMatIterator_≺unsigned short≻
              | (: Integer) -> Cv::SparseMatIterator_≺unsigned short≻
    def initialize: () -> void
               | (_m: Cv::SparseMat) -> void
               | (_m: Cv::SparseMat_≺unsigned short≻) -> void
    def initialize_copy: (it: Cv::SparseMatIterator_≺unsigned short≻) -> void
  end
end
