module Cv
  class SparseMatConstIterator2w
    def !=: (arg_0: Cv::SparseMatConstIterator_≺cv꞉꞉Vec≺unsigned short‚ 2≻≻) -> bool
    def initialize: () -> void
               | (_m: Cv::SparseMat_≺cv꞉꞉Vec≺unsigned short‚ 2≻≻) -> void
               | (_m: Cv::SparseMat) -> void
    def ==: (arg_0: Cv::SparseMatConstIterator_≺cv꞉꞉Vec≺unsigned short‚ 2≻≻) -> bool
    def dereference: () -> Cv::Vec≺unsigned short‚ 2≻
    def increment: () -> Cv::SparseMatConstIterator_≺cv꞉꞉Vec≺unsigned short‚ 2≻≻
              | (: Integer) -> Cv::SparseMatConstIterator_≺cv꞉꞉Vec≺unsigned short‚ 2≻≻
    def initialize_copy: (it: Cv::SparseMatConstIterator_≺cv꞉꞉Vec≺unsigned short‚ 2≻≻) -> void
  end
end
