module Cv
  class SparseMatConstIterator3i
    def !=: (arg_0: Cv::SparseMatConstIterator3i) -> TrueClass
    def initialize: () -> NilClass
               | (_m: Cv::SparseMat3i) -> NilClass
               | (_m: Cv::SparseMat) -> NilClass
    def ==: (arg_0: Cv::SparseMatConstIterator3i) -> TrueClass
    def dereference: () -> Cv::Vec3i
    def increment: () -> Cv::SparseMatConstIterator3i
              | (: Integer) -> Cv::SparseMatConstIterator3i
    def initialize_copy: (it: Cv::SparseMatConstIterator3i) -> NilClass
  end
end
