module Cv
  class SparseMatConstIterator2i
    def assign: (it: Cv::SparseMatConstIterator2i) -> Cv::SparseMatConstIterator2i
    def dereference: () -> Cv::Vec2i
    def increment: () -> Cv::SparseMatConstIterator2i
    def increment_post: (arg_0: Integer) -> Cv::SparseMatConstIterator2i
    def initialize: () -> NilClass
               | (_m: Cv::SparseMat) -> NilClass
               | (_m: Cv::SparseMat2i) -> NilClass
    def initialize_copy: (it: Cv::SparseMatConstIterator2i) -> NilClass
  end
end
