module Cv
  class SparseMatIterator6f
    def dereference: () -> Cv::Vec≺float‚ 6≻
    def increment: () -> Cv::SparseMatIterator_≺cv꞉꞉Vec≺float‚ 6≻≻
              | (: Integer) -> Cv::SparseMatIterator_≺cv꞉꞉Vec≺float‚ 6≻≻
    def initialize: () -> void
               | (_m: Cv::SparseMat) -> void
               | (_m: Cv::SparseMat_≺cv꞉꞉Vec≺float‚ 6≻≻) -> void
    def initialize_copy: (it: Cv::SparseMatIterator_≺cv꞉꞉Vec≺float‚ 6≻≻) -> void
  end
end
