module Cv
  class SparseMat2b
    def []: (arg_0: Rice::Pointer≺int≻) -> Cv::Vec2b
       | (arg_0: Integer) -> Cv::Vec2b
       | (arg_0: Integer, arg_1: Integer) -> Cv::Vec2b
       | (arg_0: Integer, arg_1: Integer, arg_2: Integer) -> Cv::Vec2b
    def []=: (arg_0: Integer, arg_1: Cv::Vec2b) -> Cv::Vec2b
        | (arg_0: Rice::Pointer≺int≻, arg_1: Cv::Vec2b) -> Cv::Vec2b
        | (arg_0: Integer, arg_1: Integer, arg_2: Cv::Vec2b) -> Cv::Vec2b
        | (arg_0: Integer, arg_1: Integer, arg_2: Integer, arg_3: Cv::Vec2b) -> Cv::Vec2b
    def initialize: () -> NilClass
               | (m: Cv::SparseMat) -> NilClass
               | (m: Cv::Mat) -> NilClass
               | (dims: Integer, _sizes: Rice::Pointer≺int≻) -> NilClass
    def begin: () -> Cv::SparseMatIterator2b
    def clone: () -> Cv::SparseMat2b
    def create: (dims: Integer, _sizes: Rice::Pointer≺int≻) -> NilClass
    def depth: () -> Integer
    def end: () -> Cv::SparseMatIterator2b
    def channels: () -> Integer
    def initialize_copy: (m: Cv::SparseMat2b) -> NilClass
    def type: () -> Integer
  end
end
