module Cv
  class SparseMat3s
    def []: (arg_0: Rice::Pointer≺int≻) -> Cv::Vec3s
       | (arg_0: Integer) -> Cv::Vec3s
       | (arg_0: Integer, arg_1: Integer) -> Cv::Vec3s
       | (arg_0: Integer, arg_1: Integer, arg_2: Integer) -> Cv::Vec3s
    def []=: (arg_0: Integer, arg_1: Cv::Vec3s) -> Cv::Vec3s
        | (arg_0: Rice::Pointer≺int≻, arg_1: Cv::Vec3s) -> Cv::Vec3s
        | (arg_0: Integer, arg_1: Integer, arg_2: Cv::Vec3s) -> Cv::Vec3s
        | (arg_0: Integer, arg_1: Integer, arg_2: Integer, arg_3: Cv::Vec3s) -> Cv::Vec3s
    def initialize: () -> NilClass
               | (m: Cv::SparseMat) -> NilClass
               | (m: Cv::Mat) -> NilClass
               | (dims: Integer, _sizes: Rice::Pointer≺int≻) -> NilClass
    def begin: () -> Cv::SparseMatIterator3s
    def clone: () -> Cv::SparseMat3s
    def create: (dims: Integer, _sizes: Rice::Pointer≺int≻) -> NilClass
    def depth: () -> Integer
    def end: () -> Cv::SparseMatIterator3s
    def channels: () -> Integer
    def initialize_copy: (m: Cv::SparseMat3s) -> NilClass
    def type: () -> Integer
  end
end
