module Cv
  class SparseMatConstIterator2f
    def assign: (it: Cv::SparseMatConstIterator2f) -> Cv::SparseMatConstIterator2f
    def dereference: () -> Cv::Vec2f
    def increment: () -> Cv::SparseMatConstIterator2f
    def increment_post: (arg_0: Integer) -> Cv::SparseMatConstIterator2f
    def initialize: () -> NilClass
               | (_m: Cv::SparseMat) -> NilClass
               | (_m: Cv::SparseMat2f) -> NilClass
    def initialize_copy: (it: Cv::SparseMatConstIterator2f) -> NilClass
  end
end
