module Cv
  class SparseMatConstIterator2s
    def !=: (arg_0: Cv::SparseMatConstIterator2s) -> TrueClass
    def initialize: () -> NilClass
               | (_m: Cv::SparseMat2s) -> NilClass
               | (_m: Cv::SparseMat) -> NilClass
    def ==: (arg_0: Cv::SparseMatConstIterator2s) -> TrueClass
    def dereference: () -> Cv::Vec2s
    def increment: () -> Cv::SparseMatConstIterator2s
              | (: Integer) -> Cv::SparseMatConstIterator2s
    def initialize_copy: (it: Cv::SparseMatConstIterator2s) -> NilClass
  end
end
