module Cv
  class SparseMatConstIterator2b
    def !=: (arg_0: Cv::SparseMatConstIterator2b) -> TrueClass
    def initialize: () -> NilClass
               | (_m: Cv::SparseMat2b) -> NilClass
               | (_m: Cv::SparseMat) -> NilClass
    def ==: (arg_0: Cv::SparseMatConstIterator2b) -> TrueClass
    def dereference: () -> Cv::Vec2b
    def increment: () -> Cv::SparseMatConstIterator2b
              | (: Integer) -> Cv::SparseMatConstIterator2b
    def initialize_copy: (it: Cv::SparseMatConstIterator2b) -> NilClass
  end
end
