module Cv
  class SparseMat2s
    def []: (arg_0: Rice::Pointer≺int≻) -> Cv::Vec2s
       | (arg_0: Integer) -> Cv::Vec2s
       | (idx: Rice::Pointer≺int≻, hashval: Rice::Pointer≺unsigned Int64≻) -> Cv::Vec2s
       | (i0: Integer, hashval: Rice::Pointer≺unsigned Int64≻) -> Cv::Vec2s
       | (arg_0: Integer, arg_1: Integer) -> Cv::Vec2s
       | (i0: Integer, i1: Integer, hashval: Rice::Pointer≺unsigned Int64≻) -> Cv::Vec2s
       | (arg_0: Integer, arg_1: Integer, arg_2: Integer) -> Cv::Vec2s
       | (i0: Integer, i1: Integer, i2: Integer, hashval: Rice::Pointer≺unsigned Int64≻) -> Cv::Vec2s
    def initialize: (m: Cv::SparseMat) -> NilClass
               | (m: Cv::Mat) -> NilClass
               | () -> NilClass
               | (dims: Integer, _sizes: Rice::Pointer≺int≻) -> NilClass
    def []=: (arg_0: Rice::Pointer≺int≻, arg_1: Cv::Vec2s) -> Cv::Vec2s
        | (arg_0: Integer, arg_1: Cv::Vec2s) -> Cv::Vec2s
        | (arg_0: Integer, arg_1: Integer, arg_2: Cv::Vec2s) -> Cv::Vec2s
        | (arg_0: Integer, arg_1: Integer, arg_2: Integer, arg_3: Cv::Vec2s) -> Cv::Vec2s
    def assign: (m: Cv::SparseMat2s) -> Cv::SparseMat2s
           | (m: Cv::SparseMat) -> Cv::SparseMat2s
           | (m: Cv::Mat) -> Cv::SparseMat2s
    def begin: () -> Cv::SparseMatIterator2s
    def clone: () -> Cv::SparseMat2s
    def create: (dims: Integer, _sizes: Rice::Pointer≺int≻) -> NilClass
    def depth: () -> Integer
    def end: () -> Cv::SparseMatIterator2s
    def channels: () -> Integer
    def initialize_copy: (m: Cv::SparseMat2s) -> NilClass
    def ref: (idx: Rice::Pointer≺int≻, hashval: Rice::Pointer≺unsigned Int64≻) -> Cv::Vec2s
        | (i0: Integer, hashval: Rice::Pointer≺unsigned Int64≻) -> Cv::Vec2s
        | (i0: Integer, i1: Integer, hashval: Rice::Pointer≺unsigned Int64≻) -> Cv::Vec2s
        | (i0: Integer, i1: Integer, i2: Integer, hashval: Rice::Pointer≺unsigned Int64≻) -> Cv::Vec2s
    def type: () -> Integer
  end
end
