module Cv
  class SparseMatIterator4s
    def dereference: () -> Cv::Vec4s
    def increment: () -> Cv::SparseMatIterator4s
              | (: Integer) -> Cv::SparseMatIterator4s
    def initialize: () -> NilClass
               | (_m: Cv::SparseMat) -> NilClass
               | (_m: Cv::SparseMat4s) -> NilClass
    def initialize_copy: (it: Cv::SparseMatIterator4s) -> NilClass
  end
end
