module Cv
  class SparseOpticalFlow
    def calc: (prev_img: Cv::debug_build_guard::InputArray, next_img: Cv::debug_build_guard::InputArray, prev_pts: Cv::debug_build_guard::InputArray, next_pts: Cv::debug_build_guard::InputOutputArray, status: Cv::debug_build_guard::OutputArray, err: Cv::debug_build_guard::OutputArray) -> void
  end
end
