module Cv
  class SparseMatIterator
    def increment: () -> Cv::SparseMatIterator
              | (: Integer) -> Cv::SparseMatIterator
    def initialize: () -> NilClass
               | (_m: Cv::SparseMat) -> NilClass
    def initialize_copy: (it: Cv::SparseMatIterator) -> NilClass
    def node: () -> Cv::SparseMat::Node
  end
end
