module Cv
  class SparseMatIterator3f
    def dereference: () -> Cv::Vec3f
    def increment: () -> Cv::SparseMatIterator3f
              | (: Integer) -> Cv::SparseMatIterator3f
    def initialize: () -> NilClass
               | (_m: Cv::SparseMat) -> NilClass
               | (_m: Cv::SparseMat3f) -> NilClass
    def initialize_copy: (it: Cv::SparseMatIterator3f) -> NilClass
  end
end
