module Cv
  class SparseMatConstIterator3w
    def !=: (arg_0: Cv::SparseMatConstIterator3w) -> TrueClass
    def initialize: () -> NilClass
               | (_m: Cv::SparseMat3w) -> NilClass
               | (_m: Cv::SparseMat) -> NilClass
    def ==: (arg_0: Cv::SparseMatConstIterator3w) -> TrueClass
    def dereference: () -> Cv::Vec3w
    def increment: () -> Cv::SparseMatConstIterator3w
              | (: Integer) -> Cv::SparseMatConstIterator3w
    def initialize_copy: (it: Cv::SparseMatConstIterator3w) -> NilClass
  end
end
