module Cv
  class SparseOpticalFlow
    def calc: (prev_img: Cv::InputArray, next_img: Cv::InputArray, prev_pts: Cv::InputArray, next_pts: Cv::InputOutputArray, status: Cv::OutputArray, err: Cv::OutputArray) -> NilClass
  end
end
