module Cv
  class SparseMatIterator
    def increment: () -> Cv::SparseMatIterator
              | (: Integer) -> Cv::SparseMatIterator
    def initialize: () -> void
               | (_m: Cv::SparseMat) -> void
    def initialize_copy: (it: Cv::SparseMatIterator) -> void
    def node: () -> Cv::SparseMat::Node
  end
end
