module Cv
  class SparseMatIterator3d
    def dereference: () -> Cv::Vec≺double‚ 3≻
    def increment: () -> Cv::SparseMatIterator_≺cv꞉꞉Vec≺double‚ 3≻≻
              | (: Integer) -> Cv::SparseMatIterator_≺cv꞉꞉Vec≺double‚ 3≻≻
    def initialize: () -> void
               | (_m: Cv::SparseMat) -> void
               | (_m: Cv::SparseMat_≺cv꞉꞉Vec≺double‚ 3≻≻) -> void
    def initialize_copy: (it: Cv::SparseMatIterator_≺cv꞉꞉Vec≺double‚ 3≻≻) -> void
  end
end
