module Cv
  class SparseMatConstIterator2f
    def !=: (arg_0: Cv::SparseMatConstIterator2f) -> TrueClass
    def initialize: () -> NilClass
               | (_m: Cv::SparseMat2f) -> NilClass
               | (_m: Cv::SparseMat) -> NilClass
    def ==: (arg_0: Cv::SparseMatConstIterator2f) -> TrueClass
    def dereference: () -> Cv::Vec2f
    def increment: () -> Cv::SparseMatConstIterator2f
              | (: Integer) -> Cv::SparseMatConstIterator2f
    def initialize_copy: (it: Cv::SparseMatConstIterator2f) -> NilClass
  end
end
