module Cv
  class SparseMatConstIterator3f
    def !=: (arg_0: Cv::SparseMatConstIterator3f) -> TrueClass
    def initialize: () -> NilClass
               | (_m: Cv::SparseMat3f) -> NilClass
               | (_m: Cv::SparseMat) -> NilClass
    def ==: (arg_0: Cv::SparseMatConstIterator3f) -> TrueClass
    def dereference: () -> Cv::Vec3f
    def increment: () -> Cv::SparseMatConstIterator3f
              | (: Integer) -> Cv::SparseMatConstIterator3f
    def initialize_copy: (it: Cv::SparseMatConstIterator3f) -> NilClass
  end
end
