module Cv
  class SparseMatIterator2f
    def dereference: () -> Cv::Vec2f
    def increment: () -> Cv::SparseMatIterator2f
              | (: Integer) -> Cv::SparseMatIterator2f
    def initialize: () -> NilClass
               | (_m: Cv::SparseMat) -> NilClass
               | (_m: Cv::SparseMat2f) -> NilClass
    def initialize_copy: (it: Cv::SparseMatIterator2f) -> NilClass
  end
end
