module Cv
  class SparseMatConstIterator1s
    def !=: (arg_0: Cv::SparseMatConstIterator_≺short≻) -> bool
    def initialize: () -> void
               | (_m: Cv::SparseMat_≺short≻) -> void
               | (_m: Cv::SparseMat) -> void
    def ==: (arg_0: Cv::SparseMatConstIterator_≺short≻) -> bool
    def dereference: () -> Short
    def increment: () -> Cv::SparseMatConstIterator_≺short≻
              | (: Integer) -> Cv::SparseMatConstIterator_≺short≻
    def initialize_copy: (it: Cv::SparseMatConstIterator_≺short≻) -> void
  end
end
