module Cv
  class SVD
    attr_accessor u: Cv::Mat
    attr_accessor vt: Cv::Mat
    attr_accessor w: Cv::Mat

    def back_subst: (rhs: Cv::InputArray, dst: Cv::OutputArray) -> NilClass
    def call: (src: Cv::InputArray, flags: Integer) -> Cv::SVD
    def initialize: () -> NilClass
               | (src: Cv::InputArray, flags: Integer) -> NilClass
  end
end
