module Cv
  class TonemapReinhard
    def get_color_adaptation: () -> Float
    def get_intensity: () -> Float
    def get_light_adaptation: () -> Float
    def set_color_adaptation: (color_adapt: Float) -> void
    def set_intensity: (intensity: Float) -> void
    def set_light_adaptation: (light_adapt: Float) -> void
  end
end
