module Cv
  class TonemapDrago
    def get_bias: () -> Float
    def get_saturation: () -> Float
    def set_bias: (bias: Float) -> NilClass
    def set_saturation: (saturation: Float) -> NilClass
  end
end
