module Cv
  class TonemapMantiuk
    def get_saturation: () -> Float
    def get_scale: () -> Float
    def set_saturation: (saturation: Float) -> NilClass
    def set_scale: (scale: Float) -> NilClass
  end
end
