module Cv
  class Tracker
    def init: (image: Cv::debug_build_guard::InputArray, bounding_box: Cv::Rect_≺int≻) -> void
    def update?: (image: Cv::debug_build_guard::InputArray, bounding_box: Cv::Rect_≺int≻) -> bool
  end
end
