module Cv
  class UMat
    attr_accessor allocator: Cv::MatAllocator
    attr_accessor cols: Integer
    attr_accessor dims: Integer
    attr_accessor flags: Integer
    attr_accessor offset: Integer
    attr_accessor rows: Integer
    attr_accessor size: Cv::MatSize
    attr_reader step: Cv::MatStep
    attr_accessor u: Cv::UMatData
    attr_accessor usage_flags: Cv::UMatUsageFlags

    def []: (roi: Cv::Rect2i) -> Cv::UMat
       | (ranges: Cv::Range) -> Cv::UMat
       | (ranges: Std::Vector≺cv꞉꞉Range≻) -> Cv::UMat
       | (row_range: Cv::Range, col_range: Cv::Range) -> Cv::UMat
    def initialize: (usage_flags: Cv::UMatUsageFlags) -> NilClass
               | (m: Cv::UMat, ranges: Cv::Range) -> NilClass
               | (m: Cv::UMat, ranges: Std::Vector≺cv꞉꞉Range≻) -> NilClass
               | (m: Cv::UMat, roi: Cv::Rect2i) -> NilClass
               | (size: Cv::Size2i, type: Integer, usage_flags: Cv::UMatUsageFlags) -> NilClass
               | (m: Cv::UMat, row_range: Cv::Range, col_range: Cv::Range) -> NilClass
               | (ndims: Integer, sizes: Rice::Pointer≺int≻, type: Integer, usage_flags: Cv::UMatUsageFlags) -> NilClass
               | (rows: Integer, cols: Integer, type: Integer, usage_flags: Cv::UMatUsageFlags) -> NilClass
               | (size: Cv::Size2i, type: Integer, s: Cv::Scalar, usage_flags: Cv::UMatUsageFlags) -> NilClass
               | (rows: Integer, cols: Integer, type: Integer, s: Cv::Scalar, usage_flags: Cv::UMatUsageFlags) -> NilClass
               | (ndims: Integer, sizes: Rice::Pointer≺int≻, type: Integer, s: Cv::Scalar, usage_flags: Cv::UMatUsageFlags) -> NilClass
    def addref: () -> NilClass
    def adjust_roi: (dtop: Integer, dbottom: Integer, dleft: Integer, dright: Integer) -> Cv::UMat
    def assign: (m: Cv::UMat) -> Cv::UMat
           | (s: Cv::Scalar) -> Cv::UMat
           | (m: Cv::UMat) -> Cv::UMat
    def assign_to: (m: Cv::UMat, type: Integer) -> NilClass
    def channels: () -> Integer
    def check_vector: (elem_channels: Integer, depth: Integer, require_continuous: TrueClass) -> Integer
    def clone: () -> Cv::UMat
    def col: (x: Integer) -> Cv::UMat
    def col_range: (r: Cv::Range) -> Cv::UMat
              | (startcol: Integer, endcol: Integer) -> Cv::UMat
    def continuous?: () -> TrueClass
    def convert_to: (m: Cv::OutputArray, rtype: Integer, alpha: Float, beta: Float) -> NilClass
    def copy_size: (m: Cv::UMat) -> NilClass
    def copy_to: (m: Cv::OutputArray) -> NilClass
            | (m: Cv::OutputArray, mask: Cv::InputArray) -> NilClass
    def create: (size: Cv::Size2i, type: Integer, usage_flags: Cv::UMatUsageFlags) -> NilClass
           | (sizes: Std::Vector≺int≻, type: Integer, usage_flags: Cv::UMatUsageFlags) -> NilClass
           | (ndims: Integer, sizes: Rice::Pointer≺int≻, type: Integer, usage_flags: Cv::UMatUsageFlags) -> NilClass
           | (rows: Integer, cols: Integer, type: Integer, usage_flags: Cv::UMatUsageFlags) -> NilClass
    def deallocate: () -> NilClass
    def depth: () -> Integer
    def diag: (d: Integer) -> Cv::UMat
    def dot: (m: Cv::InputArray) -> Float
    def elem_size: () -> Integer
    def elem_size1: () -> Integer
    def empty?: () -> TrueClass
    def get_mat: (flags: Cv::AccessFlag) -> Cv::Mat
    def handle: (access_flags: Cv::AccessFlag) -> Rice::Pointer≺void≻
    def initialize_copy: (m: Cv::UMat) -> NilClass
    def inspect: () -> String
    def inv: (method: Integer) -> Cv::UMat
    def locate_roi: (whole_size: Cv::Size2i, ofs: Cv::Point2i) -> NilClass
    def mul: (m: Cv::InputArray, scale: Float) -> Cv::UMat
    def ndoffset: (ofs: Rice::Pointer≺unsigned Int64≻) -> NilClass
    def release: () -> NilClass
    def reshape: (cn: Integer, rows: Integer) -> Cv::UMat
            | (cn: Integer, newndims: Integer, newsz: Rice::Pointer≺int≻) -> Cv::UMat
    def row: (y: Integer) -> Cv::UMat
    def row_range: (r: Cv::Range) -> Cv::UMat
              | (startrow: Integer, endrow: Integer) -> Cv::UMat
    def set_to: (value: Cv::InputArray, mask: Cv::InputArray) -> Cv::UMat
    def step1: (i: Integer) -> Integer
    def submatrix?: () -> TrueClass
    def t: () -> Cv::UMat
    def total: () -> Integer
    def type: () -> Integer
    def update_continuity_flag: () -> NilClass
  end
end
