module Cv
  class UsacParams
    attr_accessor confidence: Float
    attr_accessor final_polisher: Cv::PolishingMethod
    attr_accessor final_polisher_iterations: Integer
    attr_accessor is_parallel: TrueClass
    attr_accessor lo_iterations: Integer
    attr_accessor lo_method: Cv::LocalOptimMethod
    attr_accessor lo_sample_size: Integer
    attr_accessor max_iterations: Integer
    attr_accessor neighbors_search: Cv::NeighborSearchMethod
    attr_accessor random_generator_state: Integer
    attr_accessor sampler: Cv::SamplingMethod
    attr_accessor score: Cv::ScoreMethod
    attr_accessor threshold: Float

    def initialize: () -> NilClass
  end
end
