module Cv
  class Vec1d
    def []: (i: Integer) -> Double
       | (i: Integer) -> Double
    def initialize: () -> void
               | (v0: Float) -> void
               | (values: Rice::Buffer≺double const∗≻) -> void
               | (a: Cv::Matx≺double‚ 1‚ 1≻, b: Cv::Matx≺double‚ 1‚ 1≻, : Cv::MatxAddOp) -> void
               | (a: Cv::Matx≺double‚ 1‚ 1≻, b: Cv::Matx≺double‚ 1‚ 1≻, : Cv::MatxSubOp) -> void
    def []=: (arg_0: Integer, arg_1: Double) -> void
    def assign: (rhs: Cv::Vec≺double‚ 1≻) -> Cv::Vec≺double‚ 1≻
    def call: (i: Integer) -> Double
         | (i: Integer) -> Double
    def count: () -> Integer
    def initialize_copy: (v: Cv::Vec≺double‚ 1≻) -> void
    def inspect: () -> Std::String
    def mul: (v: Cv::Vec≺double‚ 1≻) -> Cv::Vec≺double‚ 1≻
    def to_a: () -> Integer
    def to_s: () -> Std::String
  end
end
