module Cv
  class Vec1b
    def []: (i: Integer) -> String
       | (i: Integer) -> String
       | (i: Integer) -> String
       | (i: Integer) -> String
    def initialize: () -> NilClass
               | (values: Rice::Pointer≺unsigned char≻) -> NilClass
               | (a: Cv::Matx11b, b: Cv::Matx11b, arg_2: Cv::MatxAddOp) -> NilClass
               | (a: Cv::Matx11b, b: Cv::Matx11b, arg_2: Cv::MatxSubOp) -> NilClass
               | (v0: String) -> NilClass
    def []=: (arg_0: Integer, arg_1: String) -> NilClass
    def assign: (rhs: Cv::Vec1b) -> Cv::Vec1b
    def initialize_copy: (v: Cv::Vec1b) -> NilClass
    def inspect: () -> String
    def mul: (v: Cv::Vec1b) -> Cv::Vec1b
    def to_a: () -> Integer
    def to_s: () -> String
  end
end
