module Cv
  class Vec1w
    def []: (i: Integer) -> Unsigned short
       | (i: Integer) -> Unsigned short
    def initialize: () -> void
               | (v0: Integer) -> void
               | (values: Rice::Buffer≺unsigned short const∗≻) -> void
               | (a: Cv::Matx≺unsigned short‚ 1‚ 1≻, b: Cv::Matx≺unsigned short‚ 1‚ 1≻, : Cv::MatxAddOp) -> void
               | (a: Cv::Matx≺unsigned short‚ 1‚ 1≻, b: Cv::Matx≺unsigned short‚ 1‚ 1≻, : Cv::MatxSubOp) -> void
    def []=: (arg_0: Integer, arg_1: Unsigned short) -> void
    def assign: (rhs: Cv::Vec≺unsigned short‚ 1≻) -> Cv::Vec≺unsigned short‚ 1≻
    def call: (i: Integer) -> Unsigned short
         | (i: Integer) -> Unsigned short
    def count: () -> Integer
    def initialize_copy: (v: Cv::Vec≺unsigned short‚ 1≻) -> void
    def inspect: () -> Std::String
    def mul: (v: Cv::Vec≺unsigned short‚ 1≻) -> Cv::Vec≺unsigned short‚ 1≻
    def to_a: () -> Integer
    def to_s: () -> Std::String
  end
end
