module Cv
  class Vec2f
    def []: (i: Integer) -> Float
       | (i: Integer) -> Float
       | (i: Integer) -> Float
       | (i: Integer) -> Float
    def []=: (arg_0: Integer, arg_1: Float) -> NilClass
    def assign: (rhs: Cv::Vec2f) -> Cv::Vec2f
    def initialize: () -> NilClass
               | (v0: Float) -> NilClass
               | (values: Rice::Pointer≺float≻) -> NilClass
               | (v0: Float, v1: Float) -> NilClass
               | (a: Cv::Matx21f, b: Cv::Matx21f, arg_2: Cv::MatxSubOp) -> NilClass
               | (a: Cv::Matx21f, b: Cv::Matx21f, arg_2: Cv::MatxAddOp) -> NilClass
    def conj: () -> Cv::Vec2f
    def initialize_copy: (v: Cv::Vec2f) -> NilClass
    def inspect: () -> String
    def mul: (v: Cv::Vec2f) -> Cv::Vec2f
    def to_a: () -> Integer
    def to_s: () -> String
  end
end
