module Cv
  class Vec2l
    def []: (i: Integer) -> Int64
       | (i: Integer) -> Int64
    def initialize: () -> void
               | (values: Rice::Buffer≺Int64 const∗≻) -> void
               | (v0: Integer, v1: Integer) -> void
               | (a: Cv::Matx≺Int64‚ 2‚ 1≻, b: Cv::Matx≺Int64‚ 2‚ 1≻, : Cv::MatxAddOp) -> void
               | (a: Cv::Matx≺Int64‚ 2‚ 1≻, b: Cv::Matx≺Int64‚ 2‚ 1≻, : Cv::MatxSubOp) -> void
    def []=: (arg_0: Integer, arg_1: Int64) -> void
    def assign: (rhs: Cv::Vec≺Int64‚ 2≻) -> Cv::Vec≺Int64‚ 2≻
    def call: (i: Integer) -> Int64
         | (i: Integer) -> Int64
    def count: () -> Integer
    def initialize_copy: (v: Cv::Vec≺Int64‚ 2≻) -> void
    def inspect: () -> Std::String
    def mul: (v: Cv::Vec≺Int64‚ 2≻) -> Cv::Vec≺Int64‚ 2≻
    def to_a: () -> Integer
    def to_s: () -> Std::String
  end
end
