module Cv
  class Vec2i
    def []: (i: Integer) -> Integer
       | (i: Integer) -> Integer
    def initialize: () -> NilClass
               | (values: Rice::Pointer≺int≻) -> NilClass
               | (v0: Integer, v1: Integer) -> NilClass
               | (a: Cv::Matx21i, b: Cv::Matx21i, op: Cv::MatxAddOp) -> NilClass
               | (a: Cv::Matx21i, b: Cv::Matx21i, op: Cv::MatxSubOp) -> NilClass
    def []=: (arg_0: Integer, arg_1: Integer) -> NilClass
    def assign: (rhs: Cv::Vec2i) -> Cv::Vec2i
    def call: (i: Integer) -> Integer
         | (i: Integer) -> Integer
    def count: () -> Integer
    def initialize_copy: (v: Cv::Vec2i) -> NilClass
    def inspect: () -> String
    def mul: (v: Cv::Vec2i) -> Cv::Vec2i
    def to_a: () -> Integer
    def to_s: () -> String
  end
end
