module Cv
  class Vec2s
    def []: (i: Integer) -> Integer
       | (i: Integer) -> Integer
       | (i: Integer) -> Integer
       | (i: Integer) -> Integer
    def []=: (arg_0: Integer, arg_1: Integer) -> NilClass
    def assign: (rhs: Cv::Vec2s) -> Cv::Vec2s
    def initialize: () -> NilClass
               | (v0: Integer) -> NilClass
               | (values: Rice::Pointer≺short≻) -> NilClass
               | (v0: Integer, v1: Integer) -> NilClass
               | (a: Cv::Matx21s, b: Cv::Matx21s, arg_2: Cv::MatxSubOp) -> NilClass
               | (a: Cv::Matx21s, b: Cv::Matx21s, arg_2: Cv::MatxAddOp) -> NilClass
    def initialize_copy: (v: Cv::Vec2s) -> NilClass
    def inspect: () -> String
    def mul: (v: Cv::Vec2s) -> Cv::Vec2s
    def to_a: () -> Integer
    def to_s: () -> String
  end
end
