module Cv
  class Vec3f
    def []: (i: Integer) -> Float
       | (i: Integer) -> Float
       | (i: Integer) -> Float
       | (i: Integer) -> Float
    def []=: (arg_0: Integer, arg_1: Float) -> NilClass
    def assign: (rhs: Cv::Vec3f) -> Cv::Vec3f
    def initialize: () -> NilClass
               | (v0: Float) -> NilClass
               | (values: Rice::Pointer≺float≻) -> NilClass
               | (v0: Float, v1: Float) -> NilClass
               | (a: Cv::Matx31f, b: Cv::Matx31f, arg_2: Cv::MatxSubOp) -> NilClass
               | (a: Cv::Matx31f, b: Cv::Matx31f, arg_2: Cv::MatxAddOp) -> NilClass
               | (v0: Float, v1: Float, v2: Float) -> NilClass
    def cross: (v: Cv::Vec3f) -> Cv::Vec3f
    def initialize_copy: (v: Cv::Vec3f) -> NilClass
    def inspect: () -> String
    def mul: (v: Cv::Vec3f) -> Cv::Vec3f
    def to_a: () -> Integer
    def to_s: () -> String
  end
end
