module Cv
  class Vec4d
    def []: (i: Integer) -> Float
       | (i: Integer) -> Float
    def initialize: () -> NilClass
               | (values: Rice::Pointer≺double≻) -> NilClass
               | (a: Cv::Matx41d, b: Cv::Matx41d, op: Cv::MatxSubOp) -> NilClass
               | (a: Cv::Matx41d, b: Cv::Matx41d, op: Cv::MatxAddOp) -> NilClass
               | (v0: Float, v1: Float, v2: Float, v3: Float) -> NilClass
    def []=: (arg_0: Integer, arg_1: Float) -> NilClass
    def assign: (rhs: Cv::Vec4d) -> Cv::Vec4d
    def call: (i: Integer) -> Float
         | (i: Integer) -> Float
    def conj: () -> Cv::Vec4d
    def count: () -> Integer
    def initialize_copy: (v: Cv::Vec4d) -> NilClass
    def inspect: () -> String
    def mul: (v: Cv::Vec4d) -> Cv::Vec4d
    def to_a: () -> Integer
    def to_s: () -> String
  end
end
