module Cv
  class Vec4b
    def []: (i: Integer) -> Unsigned char
       | (i: Integer) -> Unsigned char
    def initialize: () -> void
               | (values: Rice::Buffer≺unsigned char const∗≻) -> void
               | (a: Cv::Matx≺unsigned char‚ 4‚ 1≻, b: Cv::Matx≺unsigned char‚ 4‚ 1≻, : Cv::MatxSubOp) -> void
               | (a: Cv::Matx≺unsigned char‚ 4‚ 1≻, b: Cv::Matx≺unsigned char‚ 4‚ 1≻, : Cv::MatxAddOp) -> void
               | (v0: String, v1: String, v2: String, v3: String) -> void
    def []=: (arg_0: Integer, arg_1: Unsigned char) -> void
    def assign: (rhs: Cv::Vec≺unsigned char‚ 4≻) -> Cv::Vec≺unsigned char‚ 4≻
    def call: (i: Integer) -> Unsigned char
         | (i: Integer) -> Unsigned char
    def count: () -> Integer
    def initialize_copy: (v: Cv::Vec≺unsigned char‚ 4≻) -> void
    def inspect: () -> Std::String
    def mul: (v: Cv::Vec≺unsigned char‚ 4≻) -> Cv::Vec≺unsigned char‚ 4≻
    def to_a: () -> Integer
    def to_s: () -> Std::String
  end
end
