module Cv
  class Vec4i
    def []: (i: Integer) -> Integer
       | (i: Integer) -> Integer
    def initialize: () -> NilClass
               | (values: Rice::Pointer≺int≻) -> NilClass
               | (a: Cv::Matx41i, b: Cv::Matx41i, op: Cv::MatxSubOp) -> NilClass
               | (a: Cv::Matx41i, b: Cv::Matx41i, op: Cv::MatxAddOp) -> NilClass
               | (v0: Integer, v1: Integer, v2: Integer, v3: Integer) -> NilClass
    def []=: (arg_0: Integer, arg_1: Integer) -> NilClass
    def assign: (rhs: Cv::Vec4i) -> Cv::Vec4i
    def call: (i: Integer) -> Integer
         | (i: Integer) -> Integer
    def count: () -> Integer
    def initialize_copy: (v: Cv::Vec4i) -> NilClass
    def inspect: () -> String
    def mul: (v: Cv::Vec4i) -> Cv::Vec4i
    def to_a: () -> Integer
    def to_s: () -> String
  end
end
