module Cv
  class Vec4w
    def []: (i: Integer) -> Integer
       | (i: Integer) -> Integer
    def initialize: () -> NilClass
               | (values: Rice::Pointer≺unsigned short≻) -> NilClass
               | (a: Cv::Matx41w, b: Cv::Matx41w, op: Cv::MatxSubOp) -> NilClass
               | (a: Cv::Matx41w, b: Cv::Matx41w, op: Cv::MatxAddOp) -> NilClass
               | (v0: Integer, v1: Integer, v2: Integer, v3: Integer) -> NilClass
    def []=: (arg_0: Integer, arg_1: Integer) -> NilClass
    def assign: (rhs: Cv::Vec4w) -> Cv::Vec4w
    def call: (i: Integer) -> Integer
         | (i: Integer) -> Integer
    def count: () -> Integer
    def initialize_copy: (v: Cv::Vec4w) -> NilClass
    def inspect: () -> String
    def mul: (v: Cv::Vec4w) -> Cv::Vec4w
    def to_a: () -> Integer
    def to_s: () -> String
  end
end
