module Cv
  class Vec6i
    def []: (i: Integer) -> Integer
       | (i: Integer) -> Integer
       | (i: Integer) -> Integer
       | (i: Integer) -> Integer
    def initialize: () -> NilClass
               | (values: Rice::Pointer≺int≻) -> NilClass
               | (v0: Integer) -> NilClass
               | (v0: Integer, v1: Integer) -> NilClass
               | (a: Cv::Matx61i, b: Cv::Matx61i, arg_2: Cv::MatxAddOp) -> NilClass
               | (v0: Integer, v1: Integer, v2: Integer) -> NilClass
               | (a: Cv::Matx61i, b: Cv::Matx61i, arg_2: Cv::MatxSubOp) -> NilClass
               | (v0: Integer, v1: Integer, v2: Integer, v3: Integer) -> NilClass
               | (v0: Integer, v1: Integer, v2: Integer, v3: Integer, v4: Integer) -> NilClass
               | (v0: Integer, v1: Integer, v2: Integer, v3: Integer, v4: Integer, v5: Integer) -> NilClass
    def []=: (arg_0: Integer, arg_1: Integer) -> NilClass
    def assign: (rhs: Cv::Vec6i) -> Cv::Vec6i
    def initialize_copy: (v: Cv::Vec6i) -> NilClass
    def inspect: () -> String
    def mul: (v: Cv::Vec6i) -> Cv::Vec6i
    def to_a: () -> Integer
    def to_s: () -> String
  end
end
