module Cv
  class VideoWriter
    def <<: (image: Cv::UMat) -> Cv::VideoWriter
       | (image: Cv::Mat) -> Cv::VideoWriter
    def initialize: () -> NilClass
               | (filename: String, fourcc: Integer, fps: Float, frame_size: Cv::Size2i, is_color: TrueClass) -> NilClass
               | (filename: String, fourcc: Integer, fps: Float, frame_size: Cv::Size2i, params: Std::Vector≺int≻) -> NilClass
               | (filename: String, api_preference: Integer, fourcc: Integer, fps: Float, frame_size: Cv::Size2i, is_color: TrueClass) -> NilClass
               | (filename: String, api_preference: Integer, fourcc: Integer, fps: Float, frame_size: Cv::Size2i, params: Std::Vector≺int≻) -> NilClass
    def get: (prop_id: Integer) -> Float
    def get_backend_name: () -> String
    def open: (filename: String, fourcc: Integer, fps: Float, frame_size: Cv::Size2i, params: Std::Vector≺int≻) -> TrueClass
         | (filename: String, fourcc: Integer, fps: Float, frame_size: Cv::Size2i, is_color: TrueClass) -> TrueClass
         | (filename: String, api_preference: Integer, fourcc: Integer, fps: Float, frame_size: Cv::Size2i, params: Std::Vector≺int≻) -> TrueClass
         | (filename: String, api_preference: Integer, fourcc: Integer, fps: Float, frame_size: Cv::Size2i, is_color: TrueClass) -> TrueClass
    def opened?: () -> TrueClass
    def release: () -> NilClass
    def set: (prop_id: Integer, value: Float) -> TrueClass
    def write: (image: Cv::InputArray) -> NilClass
  end
end
