module Cv::TrackerMIL
  class Params
    attr_accessor feature_set_num_features: Integer
    attr_accessor sampler_init_in_radius: Float
    attr_accessor sampler_init_max_neg_num: Integer
    attr_accessor sampler_search_win_size: Float
    attr_accessor sampler_track_in_radius: Float
    attr_accessor sampler_track_max_neg_num: Integer
    attr_accessor sampler_track_max_pos_num: Integer

    def initialize: () -> NilClass
  end
end
