module Cv::Ogl
  class Arrays
    def bind: () -> void
    def initialize: () -> void
    def empty?: () -> bool
    def release: () -> void
    def reset_color_array: () -> void
    def reset_normal_array: () -> void
    def reset_tex_coord_array: () -> void
    def reset_vertex_array: () -> void
    def set_auto_release: (flag: bool) -> void
    def set_color_array: (color: Cv::debug_build_guard::InputArray) -> void
    def set_normal_array: (normal: Cv::debug_build_guard::InputArray) -> void
    def set_tex_coord_array: (tex_coord: Cv::debug_build_guard::InputArray) -> void
    def set_vertex_array: (vertex: Cv::debug_build_guard::InputArray) -> void
    def size: () -> Integer
  end
end
