module Cv::Detail::Tracking
  class TrackerSampler
    def add_tracker_sampler_algorithm?: (sampler: Cv::Ptr≺cv꞉꞉detail꞉꞉tracking꞉꞉TrackerSamplerAlgorithm≻) -> bool
    def get_samplers: () -> Std::Vector≺cv꞉꞉Ptr≺cv꞉꞉detail꞉꞉tracking꞉꞉TrackerSamplerAlgorithm≻≻
    def get_samples: () -> Std::Vector≺cv꞉꞉Mat≻
    def initialize: () -> void
    def sampling: (image: Cv::Mat, bounding_box: Cv::Rect_≺int≻) -> void
  end
end
