module Cv::Aruco
  class ArucoDetector
    def detect_markers: (image: Cv::debug_build_guard::InputArray, corners: Cv::debug_build_guard::OutputArray, ids: Cv::debug_build_guard::OutputArray, rejected_img_points: Cv::debug_build_guard::OutputArray) -> void
    def get_detector_parameters: () -> Cv::aruco::DetectorParameters
    def get_dictionary: () -> Cv::aruco::Dictionary
    def get_refine_parameters: () -> Cv::aruco::RefineParameters
    def initialize: (dictionary: Cv::aruco::Dictionary, detector_params: Cv::aruco::DetectorParameters, refine_params: Cv::aruco::RefineParameters) -> void
    def read: (fn: Cv::FileNode) -> void
    def refine_detected_markers: (image: Cv::debug_build_guard::InputArray, board: Cv::aruco::Board, detected_corners: Cv::debug_build_guard::InputOutputArray, detected_ids: Cv::debug_build_guard::InputOutputArray, rejected_corners: Cv::debug_build_guard::InputOutputArray, camera_matrix: Cv::debug_build_guard::InputArray, dist_coeffs: Cv::debug_build_guard::InputArray, recovered_idxs: Cv::debug_build_guard::OutputArray) -> void
    def set_detector_parameters: (detector_parameters: Cv::aruco::DetectorParameters) -> void
    def set_dictionary: (dictionary: Cv::aruco::Dictionary) -> void
    def set_refine_parameters: (refine_parameters: Cv::aruco::RefineParameters) -> void
    def write: (fs: Cv::FileStorage) -> void
          | (fs: Cv::FileStorage, name: Std::String) -> void
  end
end
