module Cv::Aruco
  class Board
    def generate_image: (out_size: Cv::Size_≺int≻, img: Cv::debug_build_guard::OutputArray, margin_size: Integer, border_bits: Integer) -> void
    def get_dictionary: () -> Cv::aruco::Dictionary
    def get_ids: () -> Std::Vector≺int≻
    def get_obj_points: () -> Std::Vector≺vector≺cv꞉꞉Point3_≺float≻≻≻
    def get_right_bottom_corner: () -> Cv::Point3_≺float≻
    def initialize: (obj_points: Cv::debug_build_guard::InputArray, dictionary: Cv::aruco::Dictionary, ids: Cv::debug_build_guard::InputArray) -> void
    def match_image_points: (detected_corners: Cv::debug_build_guard::InputArray, detected_ids: Cv::debug_build_guard::InputArray, obj_points: Cv::debug_build_guard::OutputArray, img_points: Cv::debug_build_guard::OutputArray) -> void
  end
end
