module Cv::Aruco
  class CharucoDetector
    def detect_board: (image: Cv::InputArray, charuco_corners: Cv::OutputArray, charuco_ids: Cv::OutputArray, marker_corners: Cv::InputOutputArray, marker_ids: Cv::InputOutputArray) -> NilClass
    def initialize: (board: Cv::Aruco::CharucoBoard, charuco_params: Cv::Aruco::CharucoParameters, detector_params: Cv::Aruco::DetectorParameters, refine_params: Cv::Aruco::RefineParameters) -> NilClass
    def detect_diamonds: (image: Cv::InputArray, diamond_corners: Cv::OutputArray, diamond_ids: Cv::OutputArray, marker_corners: Cv::InputOutputArray, marker_ids: Cv::InputOutputArray) -> NilClass
    def get_board: () -> Cv::Aruco::CharucoBoard
    def get_charuco_parameters: () -> Cv::Aruco::CharucoParameters
    def get_detector_parameters: () -> Cv::Aruco::DetectorParameters
    def get_refine_parameters: () -> Cv::Aruco::RefineParameters
    def set_board: (board: Cv::Aruco::CharucoBoard) -> NilClass
    def set_charuco_parameters: (charuco_parameters: Cv::Aruco::CharucoParameters) -> NilClass
    def set_detector_parameters: (detector_parameters: Cv::Aruco::DetectorParameters) -> NilClass
    def set_refine_parameters: (refine_parameters: Cv::Aruco::RefineParameters) -> NilClass
  end
end
