module Cv::Aruco
  class CharucoParameters
    attr_accessor camera_matrix: Cv::Mat
    attr_accessor dist_coeffs: Cv::Mat
    attr_accessor min_markers: Integer
    attr_accessor try_refine_markers: TrueClass

    def initialize: () -> NilClass
  end
end
