module Cv::Aruco
  class GridBoard
    def get_grid_size: () -> Cv::Size2i
    def get_marker_length: () -> Float
    def get_marker_separation: () -> Float
    def initialize: (size: Cv::Size2i, marker_length: Float, marker_separation: Float, dictionary: Cv::Aruco::Dictionary, ids: Cv::InputArray) -> NilClass
  end
end
