module Cv::Aruco
  class RefineParameters
    attr_accessor check_all_orders: bool
    attr_accessor error_correction_rate: Float
    attr_accessor min_rep_distance: Float

    def initialize: (min_rep_distance: Float, error_correction_rate: Float, check_all_orders: bool) -> void
    def read_refine_parameters?: (fn: Cv::FileNode) -> bool
    def write_refine_parameters?: (fs: Cv::FileStorage, name: Std::String) -> bool
  end
end
