module Cv::Utils::Nested
  class OriginalClassName
    def get_float_param: () -> Float
    def get_int_param: () -> Integer
    def initialize: (params: Cv::utils::nested::OriginalClassName::Params) -> void
  end
end
