module Cv::Ml
  class EM
    def get_clusters_number: () -> Integer
    def get_covariance_matrix_type: () -> Integer
    def get_covs: (covs: Std::Vector≺cv꞉꞉Mat≻) -> NilClass
    def get_means: () -> Cv::Mat
    def get_term_criteria: () -> Cv::TermCriteria
    def get_weights: () -> Cv::Mat
    def predict: (samples: Cv::InputArray, results: Cv::OutputArray, flags: Integer) -> Float
    def predict2: (sample: Cv::InputArray, probs: Cv::OutputArray) -> Cv::Vec2d
    def set_clusters_number: (val: Integer) -> NilClass
    def set_covariance_matrix_type: (val: Integer) -> NilClass
    def set_term_criteria: (val: Cv::TermCriteria) -> NilClass
    def train_e?: (samples: Cv::InputArray, means0: Cv::InputArray, covs0: Cv::InputArray, weights0: Cv::InputArray, log_likelihoods: Cv::OutputArray, labels: Cv::OutputArray, probs: Cv::OutputArray) -> TrueClass
    def train_em?: (samples: Cv::InputArray, log_likelihoods: Cv::OutputArray, labels: Cv::OutputArray, probs: Cv::OutputArray) -> TrueClass
    def train_m?: (samples: Cv::InputArray, probs0: Cv::InputArray, log_likelihoods: Cv::OutputArray, labels: Cv::OutputArray, probs: Cv::OutputArray) -> TrueClass
  end
end
