module Cv::Ml
  class LogisticRegression
    def get_iterations: () -> Integer
    def get_learning_rate: () -> Float
    def get_learnt_thetas: () -> Cv::Mat
    def get_mini_batch_size: () -> Integer
    def get_regularization: () -> Integer
    def get_term_criteria: () -> Cv::TermCriteria
    def get_train_method: () -> Integer
    def predict: (samples: Cv::InputArray, results: Cv::OutputArray, flags: Integer) -> Float
    def set_iterations: (val: Integer) -> NilClass
    def set_learning_rate: (val: Float) -> NilClass
    def set_mini_batch_size: (val: Integer) -> NilClass
    def set_regularization: (val: Integer) -> NilClass
    def set_term_criteria: (val: Cv::TermCriteria) -> NilClass
    def set_train_method: (val: Integer) -> NilClass
  end
end
