module Cv::Ml
  class NormalBayesClassifier
    def predict_prob: (inputs: Cv::debug_build_guard::InputArray, outputs: Cv::debug_build_guard::OutputArray, output_probs: Cv::debug_build_guard::OutputArray, flags: Integer) -> Float
  end
end
