module Cv::Ml
  class StatModel
    def calc_error: (data: Cv::Ptr≺cv꞉꞉ml꞉꞉TrainData≻, test: TrueClass, resp: Cv::OutputArray) -> Float
    def classifier?: () -> TrueClass
    def empty?: () -> TrueClass
    def get_var_count: () -> Integer
    def predict: (samples: Cv::InputArray, results: Cv::OutputArray, flags: Integer) -> Float
    def train: (train_data: Cv::Ptr≺cv꞉꞉ml꞉꞉TrainData≻, flags: Integer) -> TrueClass
          | (samples: Cv::InputArray, layout: Integer, responses: Cv::InputArray) -> TrueClass
    def trained?: () -> TrueClass
  end
end
