module Cv::Ml
  class SVM
    def get_c: () -> Float
    def get_class_weights: () -> Cv::Mat
    def get_coef0: () -> Float
    def get_decision_function: (i: Integer, alpha: Cv::OutputArray, svidx: Cv::OutputArray) -> Float
    def get_degree: () -> Float
    def get_gamma: () -> Float
    def get_kernel_type: () -> Integer
    def get_nu: () -> Float
    def get_p: () -> Float
    def get_support_vectors: () -> Cv::Mat
    def get_term_criteria: () -> Cv::TermCriteria
    def get_type: () -> Integer
    def get_uncompressed_support_vectors: () -> Cv::Mat
    def set_c: (val: Float) -> NilClass
    def set_class_weights: (val: Cv::Mat) -> NilClass
    def set_coef0: (val: Float) -> NilClass
    def set_custom_kernel: (_kernel: Cv::Ptr≺cv꞉꞉ml꞉꞉SVM꞉꞉Kernel≻) -> NilClass
    def set_degree: (val: Float) -> NilClass
    def set_gamma: (val: Float) -> NilClass
    def set_kernel: (kernel_type: Integer) -> NilClass
    def set_nu: (val: Float) -> NilClass
    def set_p: (val: Float) -> NilClass
    def set_term_criteria: (val: Cv::TermCriteria) -> NilClass
    def set_type: (val: Integer) -> NilClass
    def train_auto: (data: Cv::Ptr≺cv꞉꞉ml꞉꞉TrainData≻, k_fold: Integer, cgrid: Cv::Ml::ParamGrid, gamma_grid: Cv::Ml::ParamGrid, p_grid: Cv::Ml::ParamGrid, nu_grid: Cv::Ml::ParamGrid, coeff_grid: Cv::Ml::ParamGrid, degree_grid: Cv::Ml::ParamGrid, balanced: TrueClass) -> TrueClass
               | (samples: Cv::InputArray, layout: Integer, responses: Cv::InputArray, k_fold: Integer, cgrid: Cv::Ptr≺cv꞉꞉ml꞉꞉ParamGrid≻, gamma_grid: Cv::Ptr≺cv꞉꞉ml꞉꞉ParamGrid≻, p_grid: Cv::Ptr≺cv꞉꞉ml꞉꞉ParamGrid≻, nu_grid: Cv::Ptr≺cv꞉꞉ml꞉꞉ParamGrid≻, coeff_grid: Cv::Ptr≺cv꞉꞉ml꞉꞉ParamGrid≻, degree_grid: Cv::Ptr≺cv꞉꞉ml꞉꞉ParamGrid≻, balanced: TrueClass) -> TrueClass
  end
end
