module Std
  class Map≺string‚ cvflann꞉꞉any≻
    def []: (key: String) -> Cvflann::Any
    def []=: (key: String, value: Cvflann::Any) -> Cvflann::Any
    def delete: (key: String) -> Cvflann::Any
    def empty?: () -> TrueClass
    def include?: (key: String) -> TrueClass
    def initialize: () -> NilClass
    def clear: () -> NilClass
    def initialize_copy: (other: Std::Map≺string‚ cvflann꞉꞉any≻) -> NilClass
    def keys: () -> Std::Vector≺string≻
    def max_size: () -> Integer
    def size: () -> Integer
    def to_h: () -> Integer
    def to_s: () -> String
    def value?: (value: Cvflann::Any) -> TrueClass
    def values: () -> Std::Vector≺cvflann꞉꞉any≻
  end
end
