module Std
  class Pair≺cv꞉꞉UMat‚ unsigned char≻
    attr_accessor first: Cv::UMat
    attr_accessor second: String

    def initialize: () -> NilClass
               | (arg_0: Cv::UMat, arg_1: String) -> NilClass
    def initialize_copy: (arg_0: Std::Pair≺cv꞉꞉UMat‚ unsigned char≻) -> NilClass
    def to_s: () -> String
  end
end
