module Std
  class Pair≺int‚ float≻
    attr_accessor first: Integer
    attr_accessor second: Float

    def initialize: () -> NilClass
               | (x: Integer, y: Float) -> NilClass
    def initialize_copy: (other: Std::Pair≺int‚ float≻) -> NilClass
    def to_s: () -> String
  end
end
