module Std
  class Pair≺string const ‚ cvflann꞉꞉any≻
    attr_reader first: String
    attr_accessor second: Cvflann::Any

    def initialize: () -> NilClass
               | (x: String, y: Cvflann::Any) -> NilClass
    def initialize_copy: (other: Std::Pair≺string const ‚ cvflann꞉꞉any≻) -> NilClass
    def to_s: () -> String
  end
end
