module Std
  class Pair≺cv꞉꞉UMat‚ unsigned char≻
    attr_accessor first: Cv::UMat
    attr_accessor second: String

    def initialize: () -> NilClass
               | (x: Cv::UMat, y: String) -> NilClass
    def initialize_copy: (other: Std::Pair≺cv꞉꞉UMat‚ unsigned char≻) -> NilClass
    def to_s: () -> String
  end
end
