module Std
  class Pair≺cv꞉꞉Ptr≺cv꞉꞉detail꞉꞉tracking꞉꞉TrackerTargetState≻‚ float≻
    attr_accessor first: Cv::Ptr≺cv꞉꞉detail꞉꞉tracking꞉꞉TrackerTargetState≻
    attr_accessor second: Float

    def initialize: () -> NilClass
               | (x: Cv::Ptr≺cv꞉꞉detail꞉꞉tracking꞉꞉TrackerTargetState≻, y: Float) -> NilClass
    def initialize_copy: (other: Std::Pair≺cv꞉꞉Ptr≺cv꞉꞉detail꞉꞉tracking꞉꞉TrackerTargetState≻‚ float≻) -> NilClass
    def to_s: () -> String
  end
end
