module Std
  class Pair≺cv꞉꞉Rect_≺int≻‚ int≻
    attr_accessor first: Cv::Rect2i
    attr_accessor second: Integer

    def initialize: () -> NilClass
               | (x: Cv::Rect2i, y: Integer) -> NilClass
    def initialize_copy: (other: Std::Pair≺cv꞉꞉Rect_≺int≻‚ int≻) -> NilClass
    def to_s: () -> String
  end
end
