module Std
  class SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉ExpLayer≻
    def initialize: (value: Cv::Dnn::ExpLayer) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Dnn::ExpLayer
    def swap: (r: Std::SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉ExpLayer≻) -> NilClass
    def use_count: () -> Integer
  end
end
