module Std
  class SharedPtr≺cv꞉꞉utils꞉꞉nested꞉꞉OriginalClassName≻
    def initialize: (value: Cv::Utils::Nested::OriginalClassName) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Utils::Nested::OriginalClassName
    def swap: (r: Std::SharedPtr≺cv꞉꞉utils꞉꞉nested꞉꞉OriginalClassName≻) -> NilClass
    def use_count: () -> Integer
  end
end
