module Std
  class SharedPtr≺cv꞉꞉xfeatures2d꞉꞉PCTSignaturesSQFD≻
    def initialize: (value: Cv::Xfeatures2d::PCTSignaturesSQFD) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Xfeatures2d::PCTSignaturesSQFD
    def swap: (r: Std::SharedPtr≺cv꞉꞉xfeatures2d꞉꞉PCTSignaturesSQFD≻) -> NilClass
    def use_count: () -> Integer
  end
end
