module Std
  class SharedPtr≺cv꞉꞉FileStorage≻
    def initialize: (value: Cv::FileStorage) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::FileStorage
    def swap: (r: Std::SharedPtr≺cv꞉꞉FileStorage≻) -> NilClass
    def use_count: () -> Integer
  end
end
