module Std
  class SharedPtr≺cv꞉꞉detail꞉꞉tracking꞉꞉TrackerStateEstimator≻
    def initialize: (value: Cv::Detail::Tracking::TrackerStateEstimator) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Detail::Tracking::TrackerStateEstimator
    def swap: (r: Std::SharedPtr≺cv꞉꞉detail꞉꞉tracking꞉꞉TrackerStateEstimator≻) -> NilClass
    def use_count: () -> Integer
  end
end
