module Std
  class SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉AsinhLayer≻
    def initialize: (value: Cv::Dnn::AsinhLayer) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Dnn::AsinhLayer
    def swap: (r: Std::SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉AsinhLayer≻) -> NilClass
    def use_count: () -> Integer
  end
end
