module Std
  class SharedPtr≺cv꞉꞉xfeatures2d꞉꞉BEBLID≻
    def initialize: (value: Cv::Xfeatures2d::BEBLID) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Xfeatures2d::BEBLID
    def swap: (r: Std::SharedPtr≺cv꞉꞉xfeatures2d꞉꞉BEBLID≻) -> NilClass
    def use_count: () -> Integer
  end
end
