module Std
  class SharedPtr≺cv꞉꞉FaceRecognizerSF≻
    def initialize: (value: Cv::FaceRecognizerSF) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::FaceRecognizerSF
    def swap: (r: Std::SharedPtr≺cv꞉꞉FaceRecognizerSF≻) -> NilClass
    def use_count: () -> Integer
  end
end
