module Std
  class SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉ProposalLayer≻
    def initialize: (value: Cv::Dnn::ProposalLayer) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Dnn::ProposalLayer
    def swap: (r: Std::SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉ProposalLayer≻) -> NilClass
    def use_count: () -> Integer
  end
end
