module Std
  class SharedPtr≺cv꞉꞉AlignMTB≻
    def initialize: (value: Cv::AlignMTB) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::AlignMTB
    def swap: (arg_0: Std::SharedPtr≺cv꞉꞉AlignMTB≻) -> NilClass
    def use_count: () -> Integer
  end
end
