module Std
  class SharedPtr≺cv꞉꞉MSER≻
    def initialize: (value: Cv::MSER) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::MSER
    def swap: (r: Std::SharedPtr≺cv꞉꞉MSER≻) -> NilClass
    def use_count: () -> Integer
  end
end
