module Std
  class SharedPtr≺cv꞉꞉TrackerNano≻
    def initialize: (value: Cv::TrackerNano) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::TrackerNano
    def swap: (arg_0: Std::SharedPtr≺cv꞉꞉TrackerNano≻) -> NilClass
    def use_count: () -> Integer
  end
end
