module Std
  class SharedPtr≺cv꞉꞉ocl꞉꞉Context꞉꞉UserContext≻
    def initialize: (value: Cv::Ocl::Context::UserContext) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Ocl::Context::UserContext
    def swap: (r: Std::SharedPtr≺cv꞉꞉ocl꞉꞉Context꞉꞉UserContext≻) -> NilClass
    def use_count: () -> Integer
  end
end
