module Std
  class SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉SliceLayer≻
    def initialize: (value: Cv::Dnn::SliceLayer) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Dnn::SliceLayer
    def swap: (r: Std::SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉SliceLayer≻) -> NilClass
    def use_count: () -> Integer
  end
end
