module Std
  class SharedPtr≺cv꞉꞉detail꞉꞉RotationWarper≻
    def initialize: (value: Cv::Detail::RotationWarper) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Detail::RotationWarper
    def swap: (r: Std::SharedPtr≺cv꞉꞉detail꞉꞉RotationWarper≻) -> NilClass
    def use_count: () -> Integer
  end
end
