module Std
  class SharedPtr≺cv꞉꞉xfeatures2d꞉꞉FREAK≻
    def initialize: (value: Cv::Xfeatures2d::FREAK) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Xfeatures2d::FREAK
    def swap: (r: Std::SharedPtr≺cv꞉꞉xfeatures2d꞉꞉FREAK≻) -> NilClass
    def use_count: () -> Integer
  end
end
