module Std
  class SharedPtr≺cv꞉꞉stereo꞉꞉StereoBinarySGBM≻
    def initialize: (value: Cv::Stereo::StereoBinarySGBM) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Stereo::StereoBinarySGBM
    def swap: (r: Std::SharedPtr≺cv꞉꞉stereo꞉꞉StereoBinarySGBM≻) -> NilClass
    def use_count: () -> Integer
  end
end
