module Std
  class SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉InstanceNormLayer≻
    def initialize: (value: Cv::Dnn::InstanceNormLayer) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Dnn::InstanceNormLayer
    def swap: (r: Std::SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉InstanceNormLayer≻) -> NilClass
    def use_count: () -> Integer
  end
end
