module Std
  class SharedPtr≺cv꞉꞉WarperCreator≻
    def initialize: (value: Cv::WarperCreator) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::WarperCreator
    def swap: (r: Std::SharedPtr≺cv꞉꞉WarperCreator≻) -> NilClass
    def use_count: () -> Integer
  end
end
