module Std
  class SharedPtr≺cv꞉꞉LMSolver꞉꞉Callback≻
    def initialize: (value: Cv::LMSolver::Callback) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::LMSolver::Callback
    def swap: (r: Std::SharedPtr≺cv꞉꞉LMSolver꞉꞉Callback≻) -> NilClass
    def use_count: () -> Integer
  end
end
