module Std
  class SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉MishLayer≻
    def initialize: (value: Cv::Dnn::MishLayer) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Dnn::MishLayer
    def swap: (r: Std::SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉MishLayer≻) -> NilClass
    def use_count: () -> Integer
  end
end
