module Std
  class SharedPtr≺cv꞉꞉xfeatures2d꞉꞉HarrisLaplaceFeatureDetector≻
    def initialize: (value: Cv::Xfeatures2d::HarrisLaplaceFeatureDetector) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Xfeatures2d::HarrisLaplaceFeatureDetector
    def swap: (r: Std::SharedPtr≺cv꞉꞉xfeatures2d꞉꞉HarrisLaplaceFeatureDetector≻) -> NilClass
    def use_count: () -> Integer
  end
end
