module Std
  class SharedPtr≺cv꞉꞉xfeatures2d꞉꞉DAISY≻
    def initialize: (value: Cv::Xfeatures2d::DAISY) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Xfeatures2d::DAISY
    def swap: (r: Std::SharedPtr≺cv꞉꞉xfeatures2d꞉꞉DAISY≻) -> NilClass
    def use_count: () -> Integer
  end
end
