module Std
  class SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉InnerProductLayerInt8≻
    def initialize: (value: Cv::Dnn::InnerProductLayerInt8) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Dnn::InnerProductLayerInt8
    def swap: (arg_0: Std::SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉InnerProductLayerInt8≻) -> NilClass
    def use_count: () -> Integer
  end
end
