module Std
  class SharedPtr≺cv꞉꞉AgastFeatureDetector≻
    def initialize: (value: Cv::AgastFeatureDetector) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::AgastFeatureDetector
    def swap: (r: Std::SharedPtr≺cv꞉꞉AgastFeatureDetector≻) -> NilClass
    def use_count: () -> Integer
  end
end
