module Std
  class SharedPtr≺cv꞉꞉ml꞉꞉SVMSGD≻
    def initialize: (value: Cv::Ml::SVMSGD) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Ml::SVMSGD
    def swap: (r: Std::SharedPtr≺cv꞉꞉ml꞉꞉SVMSGD≻) -> NilClass
    def use_count: () -> Integer
  end
end
