module Std
  class SharedPtr≺cv꞉꞉detail꞉꞉tracking꞉꞉TrackerTargetState≻
    def initialize: (value: Cv::Detail::Tracking::TrackerTargetState) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Detail::Tracking::TrackerTargetState
    def swap: (r: Std::SharedPtr≺cv꞉꞉detail꞉꞉tracking꞉꞉TrackerTargetState≻) -> NilClass
    def use_count: () -> Integer
  end
end
