module Std
  class SharedPtr≺cv꞉꞉face꞉꞉PredictCollector≻
    def initialize: (value: Cv::Face::PredictCollector) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Face::PredictCollector
    def swap: (r: Std::SharedPtr≺cv꞉꞉face꞉꞉PredictCollector≻) -> NilClass
    def use_count: () -> Integer
  end
end
