module Std
  class SharedPtr≺cv꞉꞉ml꞉꞉SVM≻
    def initialize: (value: Cv::Ml::SVM) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Ml::SVM
    def swap: (arg_0: Std::SharedPtr≺cv꞉꞉ml꞉꞉SVM≻) -> NilClass
    def use_count: () -> Integer
  end
end
