module Std
  class SharedPtr≺cv꞉꞉GeneralizedHoughGuil≻
    def initialize: (value: Cv::GeneralizedHoughGuil) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::GeneralizedHoughGuil
    def swap: (r: Std::SharedPtr≺cv꞉꞉GeneralizedHoughGuil≻) -> NilClass
    def use_count: () -> Integer
  end
end
