module Std
  class SharedPtr≺cv꞉꞉ml꞉꞉ANNMLP≻
    def initialize: (value: Cv::Ml::ANN_MLP) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Ml::ANN_MLP
    def swap: (arg_0: Std::SharedPtr≺cv꞉꞉ml꞉꞉ANNMLP≻) -> NilClass
    def use_count: () -> Integer
  end
end
