module Std
  class SharedPtr≺cv꞉꞉xfeatures2d꞉꞉StarDetector≻
    def initialize: (value: Cv::Xfeatures2d::StarDetector) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Xfeatures2d::StarDetector
    def swap: (r: Std::SharedPtr≺cv꞉꞉xfeatures2d꞉꞉StarDetector≻) -> NilClass
    def use_count: () -> Integer
  end
end
