module Std
  class SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉SinhLayer≻
    def initialize: (value: Cv::Dnn::SinhLayer) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Dnn::SinhLayer
    def swap: (arg_0: Std::SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉SinhLayer≻) -> NilClass
    def use_count: () -> Integer
  end
end
