module Std
  class SharedPtr≺cv꞉꞉xfeatures2d꞉꞉BriefDescriptorExtractor≻
    def initialize: (value: Cv::Xfeatures2d::BriefDescriptorExtractor) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Xfeatures2d::BriefDescriptorExtractor
    def swap: (r: Std::SharedPtr≺cv꞉꞉xfeatures2d꞉꞉BriefDescriptorExtractor≻) -> NilClass
    def use_count: () -> Integer
  end
end
