module Std
  class SharedPtr≺cv꞉꞉DescriptorMatcher≻
    def initialize: (value: Cv::DescriptorMatcher) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::DescriptorMatcher
    def swap: (arg_0: Std::SharedPtr≺cv꞉꞉DescriptorMatcher≻) -> NilClass
    def use_count: () -> Integer
  end
end
