module Std
  class SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉ActivationLayerInt8≻
    def initialize: (value: Cv::Dnn::ActivationLayerInt8) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Dnn::ActivationLayerInt8
    def swap: (arg_0: Std::SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉ActivationLayerInt8≻) -> NilClass
    def use_count: () -> Integer
  end
end
