module Std
  class SharedPtr≺cv꞉꞉Feature2D≻
    def initialize: (value: Cv::Feature2D) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Feature2D
    def swap: (r: Std::SharedPtr≺cv꞉꞉Feature2D≻) -> NilClass
    def use_count: () -> Integer
  end
end
