module Std
  class SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉ScatterNDLayer≻
    def initialize: (value: Cv::Dnn::ScatterNDLayer) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Dnn::ScatterNDLayer
    def swap: (r: Std::SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉ScatterNDLayer≻) -> NilClass
    def use_count: () -> Integer
  end
end
