module Std
  class SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉LogLayer≻
    def initialize: (value: Cv::Dnn::LogLayer) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Dnn::LogLayer
    def swap: (r: Std::SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉LogLayer≻) -> NilClass
    def use_count: () -> Integer
  end
end
