module Std
  class SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉ReorgLayer≻
    def initialize: (value: Cv::Dnn::ReorgLayer) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Dnn::ReorgLayer
    def swap: (arg_0: Std::SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉ReorgLayer≻) -> NilClass
    def use_count: () -> Integer
  end
end
