module Std
  class SharedPtr≺cv꞉꞉MinProblemSolver꞉꞉Function≻
    def initialize: (value: Cv::MinProblemSolver::Function) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::MinProblemSolver::Function
    def swap: (r: Std::SharedPtr≺cv꞉꞉MinProblemSolver꞉꞉Function≻) -> NilClass
    def use_count: () -> Integer
  end
end
