module Std
  class SharedPtr≺cv꞉꞉bgsegm꞉꞉SyntheticSequenceGenerator≻
    def initialize: (value: Cv::Bgsegm::SyntheticSequenceGenerator) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Bgsegm::SyntheticSequenceGenerator
    def swap: (r: Std::SharedPtr≺cv꞉꞉bgsegm꞉꞉SyntheticSequenceGenerator≻) -> NilClass
    def use_count: () -> Integer
  end
end
