module Std
  class SharedPtr≺cv꞉꞉xfeatures2d꞉꞉TEBLID≻
    def initialize: (value: Cv::Xfeatures2d::TEBLID) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Xfeatures2d::TEBLID
    def swap: (r: Std::SharedPtr≺cv꞉꞉xfeatures2d꞉꞉TEBLID≻) -> NilClass
    def use_count: () -> Integer
  end
end
