module Std
  class SharedPtr≺cv꞉꞉AffineFeature≻
    def initialize: (value: Cv::AffineFeature) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::AffineFeature
    def swap: (r: Std::SharedPtr≺cv꞉꞉AffineFeature≻) -> NilClass
    def use_count: () -> Integer
  end
end
