module Std
  class SharedPtr≺cv꞉꞉BRISK≻
    def initialize: (value: Cv::BRISK) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::BRISK
    def swap: (arg_0: Std::SharedPtr≺cv꞉꞉BRISK≻) -> NilClass
    def use_count: () -> Integer
  end
end
