module Std
  class SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉ScaleLayer≻
    def initialize: (value: Cv::Dnn::ScaleLayer) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Dnn::ScaleLayer
    def swap: (arg_0: Std::SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉ScaleLayer≻) -> NilClass
    def use_count: () -> Integer
  end
end
