module Std
  class SharedPtr≺cv꞉꞉xfeatures2d꞉꞉BoostDesc≻
    def initialize: (value: Cv::Xfeatures2d::BoostDesc) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Xfeatures2d::BoostDesc
    def swap: (r: Std::SharedPtr≺cv꞉꞉xfeatures2d꞉꞉BoostDesc≻) -> NilClass
    def use_count: () -> Integer
  end
end
