module Std
  class SharedPtr≺cv꞉꞉BFMatcher≻
    def initialize: (value: Cv::BFMatcher) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::BFMatcher
    def swap: (arg_0: Std::SharedPtr≺cv꞉꞉BFMatcher≻) -> NilClass
    def use_count: () -> Integer
  end
end
