module Std
  class SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉RequantizeLayer≻
    def initialize: (value: Cv::Dnn::RequantizeLayer) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Dnn::RequantizeLayer
    def swap: (arg_0: Std::SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉RequantizeLayer≻) -> NilClass
    def use_count: () -> Integer
  end
end
