module Std
  class SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉NaryEltwiseLayer≻
    def initialize: (value: Cv::Dnn::NaryEltwiseLayer) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Dnn::NaryEltwiseLayer
    def swap: (r: Std::SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉NaryEltwiseLayer≻) -> NilClass
    def use_count: () -> Integer
  end
end
