module Std
  class SharedPtr≺cv꞉꞉Stitcher≻
    def initialize: (value: Cv::Stitcher) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Stitcher
    def swap: (r: Std::SharedPtr≺cv꞉꞉Stitcher≻) -> NilClass
    def use_count: () -> Integer
  end
end
