module Std
  class SharedPtr≺cv꞉꞉BaseCascadeClassifier꞉꞉MaskGenerator≻
    def initialize: (value: Cv::BaseCascadeClassifier::MaskGenerator) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::BaseCascadeClassifier::MaskGenerator
    def swap: (r: Std::SharedPtr≺cv꞉꞉BaseCascadeClassifier꞉꞉MaskGenerator≻) -> NilClass
    def use_count: () -> Integer
  end
end
