module Std
  class SharedPtr≺cv꞉꞉face꞉꞉LBPHFaceRecognizer≻
    def initialize: (value: Cv::Face::LBPHFaceRecognizer) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Face::LBPHFaceRecognizer
    def swap: (r: Std::SharedPtr≺cv꞉꞉face꞉꞉LBPHFaceRecognizer≻) -> NilClass
    def use_count: () -> Integer
  end
end
