module Std
  class SharedPtr≺cv꞉꞉SIFT≻
    def initialize: (value: Cv::SIFT) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::SIFT
    def swap: (arg_0: Std::SharedPtr≺cv꞉꞉SIFT≻) -> NilClass
    def use_count: () -> Integer
  end
end
