module Std
  class SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉AbsLayer≻
    def initialize: (value: Cv::Dnn::AbsLayer) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Dnn::AbsLayer
    def swap: (r: Std::SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉AbsLayer≻) -> NilClass
    def use_count: () -> Integer
  end
end
