module Std
  class SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉ErfLayer≻
    def initialize: (value: Cv::Dnn::ErfLayer) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Dnn::ErfLayer
    def swap: (r: Std::SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉ErfLayer≻) -> NilClass
    def use_count: () -> Integer
  end
end
