module Std
  class SharedPtr≺cv꞉꞉detail꞉꞉Estimator≻
    def initialize: (value: Cv::Detail::Estimator) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Detail::Estimator
    def swap: (r: Std::SharedPtr≺cv꞉꞉detail꞉꞉Estimator≻) -> NilClass
    def use_count: () -> Integer
  end
end
