module Std
  class SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉PowerLayer≻
    def initialize: (value: Cv::Dnn::PowerLayer) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Dnn::PowerLayer
    def swap: (r: Std::SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉PowerLayer≻) -> NilClass
    def use_count: () -> Integer
  end
end
