module Std
  class SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉ThresholdedReluLayer≻
    def initialize: (value: Cv::Dnn::ThresholdedReluLayer) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Dnn::ThresholdedReluLayer
    def swap: (arg_0: Std::SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉ThresholdedReluLayer≻) -> NilClass
    def use_count: () -> Integer
  end
end
