module Std
  class SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉HardSigmoidLayer≻
    def initialize: (value: Cv::Dnn::HardSigmoidLayer) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Dnn::HardSigmoidLayer
    def swap: (arg_0: Std::SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉HardSigmoidLayer≻) -> NilClass
    def use_count: () -> Integer
  end
end
