module Std
  class SharedPtr≺cv꞉꞉TrackerGOTURN≻
    def initialize: (value: Cv::TrackerGOTURN) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::TrackerGOTURN
    def swap: (arg_0: Std::SharedPtr≺cv꞉꞉TrackerGOTURN≻) -> NilClass
    def use_count: () -> Integer
  end
end
