module Std
  class SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉SinLayer≻
    def initialize: (value: Cv::Dnn::SinLayer) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Dnn::SinLayer
    def swap: (r: Std::SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉SinLayer≻) -> NilClass
    def use_count: () -> Integer
  end
end
