module Std
  class SharedPtr≺cv꞉꞉rapid꞉꞉OLSTracker≻
    def initialize: (value: Cv::Rapid::OLSTracker) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Rapid::OLSTracker
    def swap: (r: Std::SharedPtr≺cv꞉꞉rapid꞉꞉OLSTracker≻) -> NilClass
    def use_count: () -> Integer
  end
end
