module Std
  class SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉MatMulLayer≻
    def initialize: (value: Cv::Dnn::MatMulLayer) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Dnn::MatMulLayer
    def swap: (arg_0: Std::SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉MatMulLayer≻) -> NilClass
    def use_count: () -> Integer
  end
end
