module Std
  class SharedPtr≺cv꞉꞉xfeatures2d꞉꞉LUCID≻
    def initialize: (value: Cv::Xfeatures2d::LUCID) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Xfeatures2d::LUCID
    def swap: (r: Std::SharedPtr≺cv꞉꞉xfeatures2d꞉꞉LUCID≻) -> NilClass
    def use_count: () -> Integer
  end
end
