module Std
  class SharedPtr≺float≻
    def initialize: (value: Rice::Pointer≺float≻) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Rice::Pointer≺float≻
    def swap: (r: Std::SharedPtr≺float≻) -> NilClass
    def use_count: () -> Integer
  end
end
