module Std
  class SharedPtr≺cv꞉꞉detail꞉꞉Blender≻
    def initialize: (value: Cv::Detail::Blender) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Detail::Blender
    def swap: (r: Std::SharedPtr≺cv꞉꞉detail꞉꞉Blender≻) -> NilClass
    def use_count: () -> Integer
  end
end
