module Std
  class SharedPtr≺cv꞉꞉MergeRobertson≻
    def initialize: (value: Cv::MergeRobertson) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::MergeRobertson
    def swap: (r: Std::SharedPtr≺cv꞉꞉MergeRobertson≻) -> NilClass
    def use_count: () -> Integer
  end
end
