module Std
  class SharedPtr≺cv꞉꞉GFTTDetector≻
    def initialize: (value: Cv::GFTTDetector) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::GFTTDetector
    def swap: (r: Std::SharedPtr≺cv꞉꞉GFTTDetector≻) -> NilClass
    def use_count: () -> Integer
  end
end
