module Std
  class SharedPtr≺cv꞉꞉cuda꞉꞉GpuMat꞉꞉Allocator≻
    def initialize: (value: Cv::Cuda::GpuMat::Allocator) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Cuda::GpuMat::Allocator
    def swap: (arg_0: Std::SharedPtr≺cv꞉꞉cuda꞉꞉GpuMat꞉꞉Allocator≻) -> NilClass
    def use_count: () -> Integer
  end
end
