module Std
  class SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉ELULayer≻
    def initialize: (value: Cv::Dnn::ELULayer) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Dnn::ELULayer
    def swap: (r: Std::SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉ELULayer≻) -> NilClass
    def use_count: () -> Integer
  end
end
