module Std
  class SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉LSTMLayer≻
    def initialize: (value: Cv::Dnn::LSTMLayer) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Dnn::LSTMLayer
    def swap: (arg_0: Std::SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉LSTMLayer≻) -> NilClass
    def use_count: () -> Integer
  end
end
