module Std
  class SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉CumSumLayer≻
    def initialize: (value: Cv::Dnn::CumSumLayer) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Dnn::CumSumLayer
    def swap: (r: Std::SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉CumSumLayer≻) -> NilClass
    def use_count: () -> Integer
  end
end
