module Std
  class SharedPtr≺cv꞉꞉KAZE≻
    def initialize: (value: Cv::KAZE) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::KAZE
    def swap: (r: Std::SharedPtr≺cv꞉꞉KAZE≻) -> NilClass
    def use_count: () -> Integer
  end
end
