module Std
  class SharedPtr≺cv꞉꞉stereo꞉꞉StereoBinaryBM≻
    def initialize: (value: Cv::Stereo::StereoBinaryBM) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Stereo::StereoBinaryBM
    def swap: (r: Std::SharedPtr≺cv꞉꞉stereo꞉꞉StereoBinaryBM≻) -> NilClass
    def use_count: () -> Integer
  end
end
