module Std
  class SharedPtr≺cv꞉꞉DISOpticalFlow≻
    def initialize: (value: Cv::DISOpticalFlow) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::DISOpticalFlow
    def swap: (r: Std::SharedPtr≺cv꞉꞉DISOpticalFlow≻) -> NilClass
    def use_count: () -> Integer
  end
end
