module Std
  class SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉SpaceToDepthLayer≻
    def initialize: (value: Cv::Dnn::SpaceToDepthLayer) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Dnn::SpaceToDepthLayer
    def swap: (arg_0: Std::SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉SpaceToDepthLayer≻) -> NilClass
    def use_count: () -> Integer
  end
end
