module Std
  class SharedPtr≺cv꞉꞉ml꞉꞉KNearest≻
    def initialize: (value: Cv::Ml::KNearest) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Ml::KNearest
    def swap: (r: Std::SharedPtr≺cv꞉꞉ml꞉꞉KNearest≻) -> NilClass
    def use_count: () -> Integer
  end
end
