module Std
  class SharedPtr≺cv꞉꞉ml꞉꞉NormalBayesClassifier≻
    def initialize: (value: Cv::Ml::NormalBayesClassifier) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Ml::NormalBayesClassifier
    def swap: (r: Std::SharedPtr≺cv꞉꞉ml꞉꞉NormalBayesClassifier≻) -> NilClass
    def use_count: () -> Integer
  end
end
