module Std
  class SharedPtr≺cv꞉꞉FaceDetectorYN≻
    def initialize: (value: Cv::FaceDetectorYN) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::FaceDetectorYN
    def swap: (arg_0: Std::SharedPtr≺cv꞉꞉FaceDetectorYN≻) -> NilClass
    def use_count: () -> Integer
  end
end
