module Std
  class SharedPtr≺cv꞉꞉CalibrateRobertson≻
    def initialize: (value: Cv::CalibrateRobertson) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::CalibrateRobertson
    def swap: (r: Std::SharedPtr≺cv꞉꞉CalibrateRobertson≻) -> NilClass
    def use_count: () -> Integer
  end
end
