module Std
  class SharedPtr≺cv꞉꞉FlannBasedMatcher≻
    def initialize: (value: Cv::FlannBasedMatcher) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::FlannBasedMatcher
    def swap: (r: Std::SharedPtr≺cv꞉꞉FlannBasedMatcher≻) -> NilClass
    def use_count: () -> Integer
  end
end
