module Std
  class SharedPtr≺cv꞉꞉AKAZE≻
    def initialize: (value: Cv::AKAZE) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::AKAZE
    def swap: (r: Std::SharedPtr≺cv꞉꞉AKAZE≻) -> NilClass
    def use_count: () -> Integer
  end
end
