module Std
  class SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉GeluLayer≻
    def initialize: (value: Cv::Dnn::GeluLayer) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Dnn::GeluLayer
    def swap: (r: Std::SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉GeluLayer≻) -> NilClass
    def use_count: () -> Integer
  end
end
