module Std
  class SharedPtr≺cv꞉꞉xfeatures2d꞉꞉VGG≻
    def initialize: (value: Cv::Xfeatures2d::VGG) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Xfeatures2d::VGG
    def swap: (r: Std::SharedPtr≺cv꞉꞉xfeatures2d꞉꞉VGG≻) -> NilClass
    def use_count: () -> Integer
  end
end
