module Std
  class SharedPtr≺cv꞉꞉BaseCascadeClassifier≻
    def initialize: (value: Cv::BaseCascadeClassifier) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::BaseCascadeClassifier
    def swap: (r: Std::SharedPtr≺cv꞉꞉BaseCascadeClassifier≻) -> NilClass
    def use_count: () -> Integer
  end
end
