module Std
  class SharedPtr≺cv꞉꞉LMSolver≻
    def initialize: (value: Cv::LMSolver) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::LMSolver
    def swap: (r: Std::SharedPtr≺cv꞉꞉LMSolver≻) -> NilClass
    def use_count: () -> Integer
  end
end
