module Std
  class SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉SignLayer≻
    def initialize: (value: Cv::Dnn::SignLayer) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Dnn::SignLayer
    def swap: (arg_0: Std::SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉SignLayer≻) -> NilClass
    def use_count: () -> Integer
  end
end
