module Std
  class SharedPtr≺cv꞉꞉MergeMertens≻
    def initialize: (value: Cv::MergeMertens) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::MergeMertens
    def swap: (r: Std::SharedPtr≺cv꞉꞉MergeMertens≻) -> NilClass
    def use_count: () -> Integer
  end
end
