module Std
  class SharedPtr≺cv꞉꞉VariationalRefinement≻
    def initialize: (value: Cv::VariationalRefinement) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::VariationalRefinement
    def swap: (r: Std::SharedPtr≺cv꞉꞉VariationalRefinement≻) -> NilClass
    def use_count: () -> Integer
  end
end
