module Std
  class SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉AccumLayer≻
    def initialize: (value: Cv::Dnn::AccumLayer) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Dnn::AccumLayer
    def swap: (arg_0: Std::SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉AccumLayer≻) -> NilClass
    def use_count: () -> Integer
  end
end
