module Std
  class SharedPtr≺cv꞉꞉Formatted≻
    def initialize: (value: Cv::Formatted) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Formatted
    def swap: (r: Std::SharedPtr≺cv꞉꞉Formatted≻) -> NilClass
    def use_count: () -> Integer
  end
end
