module Std
  class SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉EltwiseLayer≻
    def initialize: (value: Cv::Dnn::EltwiseLayer) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Dnn::EltwiseLayer
    def swap: (arg_0: Std::SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉EltwiseLayer≻) -> NilClass
    def use_count: () -> Integer
  end
end
