module Std
  class SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉BatchNormLayerInt8≻
    def initialize: (value: Cv::Dnn::BatchNormLayerInt8) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Dnn::BatchNormLayerInt8
    def swap: (r: Std::SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉BatchNormLayerInt8≻) -> NilClass
    def use_count: () -> Integer
  end
end
