module Std
  class SharedPtr≺cv꞉꞉GeneralizedHoughBallard≻
    def initialize: (value: Cv::GeneralizedHoughBallard) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::GeneralizedHoughBallard
    def swap: (arg_0: Std::SharedPtr≺cv꞉꞉GeneralizedHoughBallard≻) -> NilClass
    def use_count: () -> Integer
  end
end
