module Std
  class SharedPtr≺cv꞉꞉xobjdetect꞉꞉WBDetector≻
    def initialize: (value: Cv::Xobjdetect::WBDetector) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Xobjdetect::WBDetector
    def swap: (r: Std::SharedPtr≺cv꞉꞉xobjdetect꞉꞉WBDetector≻) -> NilClass
    def use_count: () -> Integer
  end
end
