module Std
  class SharedPtr≺cv꞉꞉face꞉꞉FacemarkAAM≻
    def initialize: (value: Cv::Face::FacemarkAAM) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Face::FacemarkAAM
    def swap: (r: Std::SharedPtr≺cv꞉꞉face꞉꞉FacemarkAAM≻) -> NilClass
    def use_count: () -> Integer
  end
end
