module Std
  class SharedPtr≺void≻
    def empty?: () -> TrueClass
    def get: () -> Rice::Pointer≺void≻
    def swap: (r: Std::SharedPtr≺void≻) -> NilClass
    def use_count: () -> Integer
  end
end
