module Std
  class SharedPtr≺cv꞉꞉TonemapReinhard≻
    def initialize: (value: Cv::TonemapReinhard) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::TonemapReinhard
    def swap: (r: Std::SharedPtr≺cv꞉꞉TonemapReinhard≻) -> NilClass
    def use_count: () -> Integer
  end
end
