module Std
  class SharedPtr≺cv꞉꞉face꞉꞉FacemarkLBF≻
    def initialize: (value: Cv::Face::FacemarkLBF) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Face::FacemarkLBF
    def swap: (r: Std::SharedPtr≺cv꞉꞉face꞉꞉FacemarkLBF≻) -> NilClass
    def use_count: () -> Integer
  end
end
