module Std
  class SharedPtr≺cv꞉꞉FarnebackOpticalFlow≻
    def initialize: (value: Cv::FarnebackOpticalFlow) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::FarnebackOpticalFlow
    def swap: (arg_0: Std::SharedPtr≺cv꞉꞉FarnebackOpticalFlow≻) -> NilClass
    def use_count: () -> Integer
  end
end
