module Std
  class SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉RoundLayer≻
    def initialize: (value: Cv::Dnn::RoundLayer) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Dnn::RoundLayer
    def swap: (r: Std::SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉RoundLayer≻) -> NilClass
    def use_count: () -> Integer
  end
end
