module Std
  class SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉TileLayer≻
    def initialize: (value: Cv::Dnn::TileLayer) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Dnn::TileLayer
    def swap: (r: Std::SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉TileLayer≻) -> NilClass
    def use_count: () -> Integer
  end
end
