module Std
  class SharedPtr≺cv꞉꞉optflow꞉꞉DualTVL1OpticalFlow≻
    def initialize: (value: Cv::Optflow::DualTVL1OpticalFlow) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Optflow::DualTVL1OpticalFlow
    def swap: (r: Std::SharedPtr≺cv꞉꞉optflow꞉꞉DualTVL1OpticalFlow≻) -> NilClass
    def use_count: () -> Integer
  end
end
