module Std
  class SharedPtr≺cv꞉꞉flann꞉꞉IndexParams≻
    def initialize: (value: Cv::Flann::IndexParams) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Flann::IndexParams
    def swap: (r: Std::SharedPtr≺cv꞉꞉flann꞉꞉IndexParams≻) -> NilClass
    def use_count: () -> Integer
  end
end
