module Std
  class SharedPtr≺cv꞉꞉ml꞉꞉Boost≻
    def initialize: (value: Cv::Ml::Boost) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Ml::Boost
    def swap: (arg_0: Std::SharedPtr≺cv꞉꞉ml꞉꞉Boost≻) -> NilClass
    def use_count: () -> Integer
  end
end
