module Std
  class SharedPtr≺cv꞉꞉CLAHE≻
    def initialize: (value: Cv::CLAHE) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::CLAHE
    def swap: (r: Std::SharedPtr≺cv꞉꞉CLAHE≻) -> NilClass
    def use_count: () -> Integer
  end
end
