module Std
  class SharedPtr≺cv꞉꞉ml꞉꞉ParamGrid≻
    def initialize: (value: Cv::Ml::ParamGrid) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Ml::ParamGrid
    def swap: (r: Std::SharedPtr≺cv꞉꞉ml꞉꞉ParamGrid≻) -> NilClass
    def use_count: () -> Integer
  end
end
