module Std
  class SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉TopKLayer≻
    def initialize: (value: Cv::Dnn::TopKLayer) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Dnn::TopKLayer
    def swap: (arg_0: Std::SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉TopKLayer≻) -> NilClass
    def use_count: () -> Integer
  end
end
