module Std
  class SharedPtr≺cv꞉꞉ORB≻
    def initialize: (value: Cv::ORB) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::ORB
    def swap: (r: Std::SharedPtr≺cv꞉꞉ORB≻) -> NilClass
    def use_count: () -> Integer
  end
end
