module Std
  class SharedPtr≺cv꞉꞉SparsePyrLKOpticalFlow≻
    def initialize: (value: Cv::SparsePyrLKOpticalFlow) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::SparsePyrLKOpticalFlow
    def swap: (r: Std::SharedPtr≺cv꞉꞉SparsePyrLKOpticalFlow≻) -> NilClass
    def use_count: () -> Integer
  end
end
