module Std
  class SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉BNLLLayer≻
    def initialize: (value: Cv::Dnn::BNLLLayer) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Dnn::BNLLLayer
    def swap: (arg_0: Std::SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉BNLLLayer≻) -> NilClass
    def use_count: () -> Integer
  end
end
