module Std
  class SharedPtr≺cv꞉꞉LineSegmentDetector≻
    def initialize: (value: Cv::LineSegmentDetector) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::LineSegmentDetector
    def swap: (r: Std::SharedPtr≺cv꞉꞉LineSegmentDetector≻) -> NilClass
    def use_count: () -> Integer
  end
end
