module Std
  class SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉HardSwishLayer≻
    def initialize: (value: Cv::Dnn::HardSwishLayer) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Dnn::HardSwishLayer
    def swap: (arg_0: Std::SharedPtr≺cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉HardSwishLayer≻) -> NilClass
    def use_count: () -> Integer
  end
end
