module Std
  class SharedPtr≺cv꞉꞉detail꞉꞉FeaturesMatcher≻
    def initialize: (value: Cv::Detail::FeaturesMatcher) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::Detail::FeaturesMatcher
    def swap: (r: Std::SharedPtr≺cv꞉꞉detail꞉꞉FeaturesMatcher≻) -> NilClass
    def use_count: () -> Integer
  end
end
