module Std
  class SharedPtr≺cv꞉꞉TonemapMantiuk≻
    def initialize: (value: Cv::TonemapMantiuk) -> NilClass
    def empty?: () -> TrueClass
    def get: () -> Cv::TonemapMantiuk
    def swap: (arg_0: Std::SharedPtr≺cv꞉꞉TonemapMantiuk≻) -> NilClass
    def use_count: () -> Integer
  end
end
