module Std
  class Vector≺cv꞉꞉Ptr≺cv꞉꞉detail꞉꞉tracking꞉꞉TrackerFeature≻≻
    def initialize: () -> NilClass
               | (count: Integer) -> NilClass
               | (arg_0: Array) -> NilClass
               | (count: Integer, value: Cv::Ptr≺cv꞉꞉detail꞉꞉tracking꞉꞉TrackerFeature≻) -> NilClass
    def ==: (other: Std::Vector≺cv꞉꞉Ptr≺cv꞉꞉detail꞉꞉tracking꞉꞉TrackerFeature≻≻) -> TrueClass
    def []: (pos: Integer) -> Cv::Ptr≺cv꞉꞉detail꞉꞉tracking꞉꞉TrackerFeature≻
       | (start: Integer, length: Integer) -> Integer
    def []=: (pos: Integer, value: Cv::Ptr≺cv꞉꞉detail꞉꞉tracking꞉꞉TrackerFeature≻) -> NilClass
    def capacity: () -> Integer
    def data: () -> Rice::Pointer≺cv꞉꞉Ptr≺cv꞉꞉detail꞉꞉tracking꞉꞉TrackerFeature≻≻
    def delete: (value: Cv::Ptr≺cv꞉꞉detail꞉꞉tracking꞉꞉TrackerFeature≻) -> Cv::Ptr≺cv꞉꞉detail꞉꞉tracking꞉꞉TrackerFeature≻
    def delete_at: (pos: Integer) -> Cv::Ptr≺cv꞉꞉detail꞉꞉tracking꞉꞉TrackerFeature≻
    def empty?: () -> TrueClass
    def clear: () -> NilClass
    def first: () -> Cv::Ptr≺cv꞉꞉detail꞉꞉tracking꞉꞉TrackerFeature≻
    def include?: (value: Cv::Ptr≺cv꞉꞉detail꞉꞉tracking꞉꞉TrackerFeature≻) -> TrueClass
    def index: (value: Cv::Ptr≺cv꞉꞉detail꞉꞉tracking꞉꞉TrackerFeature≻) -> Integer
    def initialize_copy: (other: Std::Vector≺cv꞉꞉Ptr≺cv꞉꞉detail꞉꞉tracking꞉꞉TrackerFeature≻≻) -> NilClass
    def insert: (pos: Integer, value: Cv::Ptr≺cv꞉꞉detail꞉꞉tracking꞉꞉TrackerFeature≻) -> Std::Vector≺cv꞉꞉Ptr≺cv꞉꞉detail꞉꞉tracking꞉꞉TrackerFeature≻≻
    def last: () -> Cv::Ptr≺cv꞉꞉detail꞉꞉tracking꞉꞉TrackerFeature≻
    def max_size: () -> Integer
    def pop: () -> Cv::Ptr≺cv꞉꞉detail꞉꞉tracking꞉꞉TrackerFeature≻
    def push: (value: Cv::Ptr≺cv꞉꞉detail꞉꞉tracking꞉꞉TrackerFeature≻) -> Std::Vector≺cv꞉꞉Ptr≺cv꞉꞉detail꞉꞉tracking꞉꞉TrackerFeature≻≻
    def reserve: (new_cap: Integer) -> NilClass
    def resize: (count: Integer) -> NilClass
    def shrink_to_fit: () -> NilClass
    def size: () -> Integer
    def to_a: () -> Integer
    def to_s: () -> String
  end
end
