module Std
  class Vector≺enum cv꞉꞉flann꞉꞉FlannIndexType≻
    def initialize: () -> NilClass
               | (count: Integer) -> NilClass
               | (arg_0: Array) -> NilClass
               | (count: Integer, value: Cv::Flann::FlannIndexType) -> NilClass
    def ==: (other: Std::Vector≺enum cv꞉꞉flann꞉꞉FlannIndexType≻) -> TrueClass
    def []: (pos: Integer) -> Cv::Flann::FlannIndexType
       | (start: Integer, length: Integer) -> Integer
    def []=: (pos: Integer, value: Cv::Flann::FlannIndexType) -> NilClass
    def capacity: () -> Integer
    def data: () -> Rice::Pointer≺enum cv꞉꞉flann꞉꞉FlannIndexType≻
    def delete: (value: Cv::Flann::FlannIndexType) -> Cv::Flann::FlannIndexType
    def delete_at: (pos: Integer) -> Cv::Flann::FlannIndexType
    def empty?: () -> TrueClass
    def clear: () -> NilClass
    def first: () -> Cv::Flann::FlannIndexType
    def include?: (value: Cv::Flann::FlannIndexType) -> TrueClass
    def index: (value: Cv::Flann::FlannIndexType) -> Integer
    def initialize_copy: (other: Std::Vector≺enum cv꞉꞉flann꞉꞉FlannIndexType≻) -> NilClass
    def insert: (pos: Integer, value: Cv::Flann::FlannIndexType) -> Std::Vector≺enum cv꞉꞉flann꞉꞉FlannIndexType≻
    def last: () -> Cv::Flann::FlannIndexType
    def max_size: () -> Integer
    def pop: () -> Cv::Flann::FlannIndexType
    def push: (value: Cv::Flann::FlannIndexType) -> Std::Vector≺enum cv꞉꞉flann꞉꞉FlannIndexType≻
    def reserve: (new_cap: Integer) -> NilClass
    def resize: (count: Integer) -> NilClass
    def shrink_to_fit: () -> NilClass
    def size: () -> Integer
    def to_a: () -> Integer
    def to_s: () -> String
  end
end
