module Std
  class Vector≺cv꞉꞉Range≻
    def initialize: () -> NilClass
               | (count: Integer) -> NilClass
               | (arg_0: Array) -> NilClass
               | (count: Integer, value: Cv::Range) -> NilClass
    def ==: (other: Std::Vector≺cv꞉꞉Range≻) -> TrueClass
    def []: (pos: Integer) -> Cv::Range
       | (start: Integer, length: Integer) -> Integer
    def []=: (pos: Integer, value: Cv::Range) -> NilClass
    def capacity: () -> Integer
    def data: () -> Rice::Pointer≺cv꞉꞉Range≻
    def delete: (value: Cv::Range) -> Cv::Range
    def delete_at: (pos: Integer) -> Cv::Range
    def empty?: () -> TrueClass
    def clear: () -> NilClass
    def first: () -> Cv::Range
    def include?: (value: Cv::Range) -> TrueClass
    def index: (value: Cv::Range) -> Integer
    def initialize_copy: (other: Std::Vector≺cv꞉꞉Range≻) -> NilClass
    def insert: (pos: Integer, value: Cv::Range) -> Std::Vector≺cv꞉꞉Range≻
    def last: () -> Cv::Range
    def max_size: () -> Integer
    def pop: () -> Cv::Range
    def push: (value: Cv::Range) -> Std::Vector≺cv꞉꞉Range≻
    def reserve: (new_cap: Integer) -> NilClass
    def resize: (count: Integer) -> NilClass
    def shrink_to_fit: () -> NilClass
    def size: () -> Integer
    def to_a: () -> Integer
    def to_s: () -> String
  end
end
