module Std
  class Vector≺cvflann꞉꞉any≻
    def initialize: () -> NilClass
               | (count: Integer) -> NilClass
               | (arg_0: Array) -> NilClass
               | (count: Integer, value: Cvflann::Any) -> NilClass
    def []: (pos: Integer) -> Cvflann::Any
       | (start: Integer, length: Integer) -> Integer
    def []=: (pos: Integer, value: Cvflann::Any) -> NilClass
    def capacity: () -> Integer
    def clear: () -> NilClass
    def data: () -> Rice::Pointer≺cvflann꞉꞉any≻
    def delete_at: (pos: Integer) -> Cvflann::Any
    def empty?: () -> TrueClass
    def first: () -> Cvflann::Any
    def include?: (value: Cvflann::Any) -> TrueClass
    def index: (value: Cvflann::Any) -> Integer
    def delete: (value: Cvflann::Any) -> Cvflann::Any
    def initialize_copy: (other: Std::Vector≺cvflann꞉꞉any≻) -> NilClass
    def insert: (pos: Integer, value: Cvflann::Any) -> Std::Vector≺cvflann꞉꞉any≻
    def last: () -> Cvflann::Any
    def max_size: () -> Integer
    def pop: () -> Cvflann::Any
    def push: (value: Cvflann::Any) -> Std::Vector≺cvflann꞉꞉any≻
    def reserve: (new_cap: Integer) -> NilClass
    def resize: (count: Integer) -> NilClass
    def shrink_to_fit: () -> NilClass
    def size: () -> Integer
    def to_a: () -> Integer
    def to_s: () -> String
  end
end
