module Std
  class Vector≺cv꞉꞉VideoCapture≻
    def initialize: () -> NilClass
               | (arg_0: Integer) -> NilClass
               | (arg_0: Array) -> NilClass
               | (arg_0: Integer, arg_1: Cv::VideoCapture) -> NilClass
    def []: (arg_0: Integer) -> Cv::VideoCapture
       | (arg_0: Integer, arg_1: Integer) -> Integer
    def []=: (arg_0: Integer, arg_1: Cv::VideoCapture) -> NilClass
    def capacity: () -> Integer
    def clear: () -> NilClass
    def data: () -> Rice::Pointer≺cv꞉꞉VideoCapture≻
    def delete_at: (arg_0: Integer) -> Cv::VideoCapture
    def empty?: () -> TrueClass
    def first: () -> Cv::VideoCapture
    def include?: (arg_0: Cv::VideoCapture) -> TrueClass
    def index: (arg_0: Cv::VideoCapture) -> Integer
    def delete: (arg_0: Cv::VideoCapture) -> Cv::VideoCapture
    def initialize_copy: (arg_0: Std::Vector≺cv꞉꞉VideoCapture≻) -> NilClass
    def insert: (arg_0: Integer, arg_1: Cv::VideoCapture) -> Std::Vector≺cv꞉꞉VideoCapture≻
    def last: () -> Cv::VideoCapture
    def max_size: () -> Integer
    def pop: () -> Cv::VideoCapture
    def push: (arg_0: Cv::VideoCapture) -> Std::Vector≺cv꞉꞉VideoCapture≻
    def reserve: (arg_0: Integer) -> NilClass
    def resize: (arg_0: Integer) -> NilClass
    def shrink_to_fit: () -> NilClass
    def size: () -> Integer
    def to_a: () -> Integer
    def to_s: () -> String
  end
end
