module Std
  class Vector≺vector≺cv꞉꞉DMatch≻≻
    def initialize: () -> NilClass
               | (arg_0: Integer) -> NilClass
               | (arg_0: Array) -> NilClass
               | (arg_0: Integer, arg_1: Std::Vector≺cv꞉꞉DMatch≻) -> NilClass
    def []: (arg_0: Integer) -> Std::Vector≺cv꞉꞉DMatch≻
       | (arg_0: Integer, arg_1: Integer) -> Integer
    def []=: (arg_0: Integer, arg_1: Std::Vector≺cv꞉꞉DMatch≻) -> NilClass
    def capacity: () -> Integer
    def clear: () -> NilClass
    def data: () -> Rice::Pointer≺vector≺cv꞉꞉DMatch≻≻
    def delete_at: (arg_0: Integer) -> Std::Vector≺cv꞉꞉DMatch≻
    def empty?: () -> TrueClass
    def first: () -> Std::Vector≺cv꞉꞉DMatch≻
    def include?: (arg_0: Std::Vector≺cv꞉꞉DMatch≻) -> TrueClass
    def index: (arg_0: Std::Vector≺cv꞉꞉DMatch≻) -> Integer
    def delete: (arg_0: Std::Vector≺cv꞉꞉DMatch≻) -> Std::Vector≺cv꞉꞉DMatch≻
    def initialize_copy: (arg_0: Std::Vector≺vector≺cv꞉꞉DMatch≻≻) -> NilClass
    def insert: (arg_0: Integer, arg_1: Std::Vector≺cv꞉꞉DMatch≻) -> Std::Vector≺vector≺cv꞉꞉DMatch≻≻
    def last: () -> Std::Vector≺cv꞉꞉DMatch≻
    def max_size: () -> Integer
    def pop: () -> Std::Vector≺cv꞉꞉DMatch≻
    def push: (arg_0: Std::Vector≺cv꞉꞉DMatch≻) -> Std::Vector≺vector≺cv꞉꞉DMatch≻≻
    def reserve: (arg_0: Integer) -> NilClass
    def resize: (arg_0: Integer) -> NilClass
    def shrink_to_fit: () -> NilClass
    def size: () -> Integer
    def to_a: () -> Integer
    def to_s: () -> String
  end
end
