module Std
  class Vector≺Cv꞉꞉Point3d≻
    def initialize: () -> NilClass
               | (arg_0: Integer) -> NilClass
               | (arg_0: Array) -> NilClass
               | (arg_0: Integer, arg_1: Cv::Point3d) -> NilClass
    def ==: (arg_0: Std::Vector≺Cv꞉꞉Point3d≻) -> TrueClass
    def []: (arg_0: Integer) -> Cv::Point3d
       | (arg_0: Integer, arg_1: Integer) -> Integer
    def []=: (arg_0: Integer, arg_1: Cv::Point3d) -> NilClass
    def capacity: () -> Integer
    def data: () -> Rice::Pointer≺cv꞉꞉Point3_≺double≻≻
    def delete: (arg_0: Cv::Point3d) -> Cv::Point3d
    def delete_at: (arg_0: Integer) -> Cv::Point3d
    def empty?: () -> TrueClass
    def clear: () -> NilClass
    def first: () -> Cv::Point3d
    def include?: (arg_0: Cv::Point3d) -> TrueClass
    def index: (arg_0: Cv::Point3d) -> Integer
    def initialize_copy: (arg_0: Std::Vector≺Cv꞉꞉Point3d≻) -> NilClass
    def insert: (arg_0: Integer, arg_1: Cv::Point3d) -> Std::Vector≺Cv꞉꞉Point3d≻
    def last: () -> Cv::Point3d
    def max_size: () -> Integer
    def pop: () -> Cv::Point3d
    def push: (arg_0: Cv::Point3d) -> Std::Vector≺Cv꞉꞉Point3d≻
    def reserve: (arg_0: Integer) -> NilClass
    def resize: (arg_0: Integer) -> NilClass
    def shrink_to_fit: () -> NilClass
    def size: () -> Integer
    def to_a: () -> Integer
    def to_s: () -> String
  end
end
