module Std
  class Vector≺vector≺cv꞉꞉Point_≺float≻≻≻
    def initialize: () -> NilClass
               | (count: Integer) -> NilClass
               | (arg_0: Array) -> NilClass
               | (count: Integer, value: Std::Vector≺cv꞉꞉Point_≺float≻≻) -> NilClass
    def ==: (other: Std::Vector≺vector≺cv꞉꞉Point_≺float≻≻≻) -> TrueClass
    def []: (pos: Integer) -> Std::Vector≺cv꞉꞉Point_≺float≻≻
       | (start: Integer, length: Integer) -> Integer
    def []=: (pos: Integer, value: Std::Vector≺cv꞉꞉Point_≺float≻≻) -> NilClass
    def capacity: () -> Integer
    def data: () -> Rice::Pointer≺vector≺cv꞉꞉Point_≺float≻≻≻
    def delete: (value: Std::Vector≺cv꞉꞉Point_≺float≻≻) -> Std::Vector≺cv꞉꞉Point_≺float≻≻
    def delete_at: (pos: Integer) -> Std::Vector≺cv꞉꞉Point_≺float≻≻
    def empty?: () -> TrueClass
    def clear: () -> NilClass
    def first: () -> Std::Vector≺cv꞉꞉Point_≺float≻≻
    def include?: (value: Std::Vector≺cv꞉꞉Point_≺float≻≻) -> TrueClass
    def index: (value: Std::Vector≺cv꞉꞉Point_≺float≻≻) -> Integer
    def initialize_copy: (other: Std::Vector≺vector≺cv꞉꞉Point_≺float≻≻≻) -> NilClass
    def insert: (pos: Integer, value: Std::Vector≺cv꞉꞉Point_≺float≻≻) -> Std::Vector≺vector≺cv꞉꞉Point_≺float≻≻≻
    def last: () -> Std::Vector≺cv꞉꞉Point_≺float≻≻
    def max_size: () -> Integer
    def pop: () -> Std::Vector≺cv꞉꞉Point_≺float≻≻
    def push: (value: Std::Vector≺cv꞉꞉Point_≺float≻≻) -> Std::Vector≺vector≺cv꞉꞉Point_≺float≻≻≻
    def reserve: (new_cap: Integer) -> NilClass
    def resize: (count: Integer) -> NilClass
    def shrink_to_fit: () -> NilClass
    def size: () -> Integer
    def to_a: () -> Integer
    def to_s: () -> String
  end
end
