module Std
  class Vector≺char≻
    def initialize: () -> NilClass
               | (count: Integer) -> NilClass
               | (arg_0: Array) -> NilClass
               | (count: Integer, value: String) -> NilClass
    def ==: (other: Std::Vector≺char≻) -> TrueClass
    def []: (pos: Integer) -> String
       | (start: Integer, length: Integer) -> Integer
    def []=: (pos: Integer, value: String) -> NilClass
    def capacity: () -> Integer
    def data: () -> Rice::Pointer≺char≻
    def delete: (value: String) -> String
    def delete_at: (pos: Integer) -> String
    def empty?: () -> TrueClass
    def clear: () -> NilClass
    def first: () -> String
    def include?: (value: String) -> TrueClass
    def index: (value: String) -> Integer
    def initialize_copy: (other: Std::Vector≺char≻) -> NilClass
    def insert: (pos: Integer, value: String) -> Std::Vector≺char≻
    def last: () -> String
    def max_size: () -> Integer
    def pop: () -> String
    def push: (value: String) -> Std::Vector≺char≻
    def reserve: (new_cap: Integer) -> NilClass
    def resize: (count: Integer) -> NilClass
    def shrink_to_fit: () -> NilClass
    def size: () -> Integer
    def to_a: () -> Integer
    def to_s: () -> String
  end
end
