module Std
  class Vector≺enum cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉Target≻
    def initialize: () -> NilClass
               | (count: Integer) -> NilClass
               | (arg_0: Array) -> NilClass
               | (count: Integer, value: Cv::Dnn::Target) -> NilClass
    def ==: (other: Std::Vector≺enum cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉Target≻) -> TrueClass
    def []: (pos: Integer) -> Cv::Dnn::Target
       | (start: Integer, length: Integer) -> Integer
    def []=: (pos: Integer, value: Cv::Dnn::Target) -> NilClass
    def capacity: () -> Integer
    def data: () -> Rice::Pointer≺enum cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉Target≻
    def delete: (value: Cv::Dnn::Target) -> Cv::Dnn::Target
    def delete_at: (pos: Integer) -> Cv::Dnn::Target
    def empty?: () -> TrueClass
    def clear: () -> NilClass
    def first: () -> Cv::Dnn::Target
    def include?: (value: Cv::Dnn::Target) -> TrueClass
    def index: (value: Cv::Dnn::Target) -> Integer
    def initialize_copy: (other: Std::Vector≺enum cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉Target≻) -> NilClass
    def insert: (pos: Integer, value: Cv::Dnn::Target) -> Std::Vector≺enum cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉Target≻
    def last: () -> Cv::Dnn::Target
    def max_size: () -> Integer
    def pop: () -> Cv::Dnn::Target
    def push: (value: Cv::Dnn::Target) -> Std::Vector≺enum cv꞉꞉dnn꞉꞉dnn4V20241223꞉꞉Target≻
    def reserve: (new_cap: Integer) -> NilClass
    def resize: (count: Integer) -> NilClass
    def shrink_to_fit: () -> NilClass
    def size: () -> Integer
    def to_a: () -> Integer
    def to_s: () -> String
  end
end
