module Std
  class Vector≺short≻
    def initialize: () -> NilClass
               | (count: Integer) -> NilClass
               | (arg_0: Array) -> NilClass
               | (count: Integer, value: Integer) -> NilClass
    def ==: (other: Std::Vector≺short≻) -> TrueClass
    def []: (pos: Integer) -> Integer
       | (start: Integer, length: Integer) -> Integer
    def []=: (pos: Integer, value: Integer) -> NilClass
    def capacity: () -> Integer
    def data: () -> Rice::Pointer≺short≻
    def delete: (value: Integer) -> Integer
    def delete_at: (pos: Integer) -> Integer
    def empty?: () -> TrueClass
    def clear: () -> NilClass
    def first: () -> Integer
    def include?: (value: Integer) -> TrueClass
    def index: (value: Integer) -> Integer
    def initialize_copy: (other: Std::Vector≺short≻) -> NilClass
    def insert: (pos: Integer, value: Integer) -> Std::Vector≺short≻
    def last: () -> Integer
    def max_size: () -> Integer
    def pop: () -> Integer
    def push: (value: Integer) -> Std::Vector≺short≻
    def reserve: (new_cap: Integer) -> NilClass
    def resize: (count: Integer) -> NilClass
    def shrink_to_fit: () -> NilClass
    def size: () -> Integer
    def to_a: () -> Integer
    def to_s: () -> String
  end
end
