module Std
  class Vector≺vector≺cv꞉꞉Mat≻≻
    def initialize: () -> NilClass
               | (count: Integer) -> NilClass
               | (arg_0: Array) -> NilClass
               | (count: Integer, value: Std::Vector≺cv꞉꞉Mat≻) -> NilClass
    def []: (pos: Integer) -> Std::Vector≺cv꞉꞉Mat≻
       | (start: Integer, length: Integer) -> Integer
    def []=: (pos: Integer, value: Std::Vector≺cv꞉꞉Mat≻) -> NilClass
    def capacity: () -> Integer
    def clear: () -> NilClass
    def data: () -> Rice::Pointer≺vector≺cv꞉꞉Mat≻≻
    def delete_at: (pos: Integer) -> Std::Vector≺cv꞉꞉Mat≻
    def empty?: () -> TrueClass
    def first: () -> Std::Vector≺cv꞉꞉Mat≻
    def include?: (value: Std::Vector≺cv꞉꞉Mat≻) -> TrueClass
    def index: (value: Std::Vector≺cv꞉꞉Mat≻) -> Integer
    def delete: (value: Std::Vector≺cv꞉꞉Mat≻) -> Std::Vector≺cv꞉꞉Mat≻
    def initialize_copy: (other: Std::Vector≺vector≺cv꞉꞉Mat≻≻) -> NilClass
    def insert: (pos: Integer, value: Std::Vector≺cv꞉꞉Mat≻) -> Std::Vector≺vector≺cv꞉꞉Mat≻≻
    def last: () -> Std::Vector≺cv꞉꞉Mat≻
    def max_size: () -> Integer
    def pop: () -> Std::Vector≺cv꞉꞉Mat≻
    def push: (value: Std::Vector≺cv꞉꞉Mat≻) -> Std::Vector≺vector≺cv꞉꞉Mat≻≻
    def reserve: (new_cap: Integer) -> NilClass
    def resize: (count: Integer) -> NilClass
    def shrink_to_fit: () -> NilClass
    def size: () -> Integer
    def to_a: () -> Integer
    def to_s: () -> String
  end
end
