module Std
  class Vector≺bool≻
    def initialize: () -> NilClass
               | (arg_0: Array) -> NilClass
               | (count: Integer) -> NilClass
               | (count: Integer, value: TrueClass) -> NilClass
    def ==: (other: Std::Vector≺bool≻) -> TrueClass
    def []: (pos: Integer) -> TrueClass
       | (start: Integer, length: Integer) -> Integer
    def []=: (pos: Integer, value: TrueClass) -> NilClass
    def capacity: () -> Integer
    def clear: () -> NilClass
    def delete: (value: TrueClass) -> TrueClass
    def delete_at: (pos: Integer) -> TrueClass
    def empty?: () -> TrueClass
    def first: () -> TrueClass
    def include?: (value: TrueClass) -> TrueClass
    def index: (value: TrueClass) -> Integer
    def initialize_copy: (other: Std::Vector≺bool≻) -> NilClass
    def insert: (pos: Integer, value: TrueClass) -> Std::Vector≺bool≻
    def last: () -> TrueClass
    def max_size: () -> Integer
    def pop: () -> TrueClass
    def push: (value: TrueClass) -> Std::Vector≺bool≻
    def reserve: (new_cap: Integer) -> NilClass
    def resize: (count: Integer, value: TrueClass) -> NilClass
    def shrink_to_fit: () -> NilClass
    def size: () -> Integer
    def to_a: () -> Integer
    def to_s: () -> String
  end
end
