module Std
  class Vector≺cv꞉꞉Rect_≺double≻≻
    def initialize: () -> NilClass
               | (count: Integer) -> NilClass
               | (arg_0: Array) -> NilClass
               | (count: Integer, value: Cv::Rect2d) -> NilClass
    def ==: (other: Std::Vector≺cv꞉꞉Rect_≺double≻≻) -> TrueClass
    def []: (pos: Integer) -> Cv::Rect2d
       | (start: Integer, length: Integer) -> Integer
    def []=: (pos: Integer, value: Cv::Rect2d) -> NilClass
    def capacity: () -> Integer
    def data: () -> Rice::Pointer≺cv꞉꞉Rect_≺double≻≻
    def delete: (value: Cv::Rect2d) -> Cv::Rect2d
    def delete_at: (pos: Integer) -> Cv::Rect2d
    def empty?: () -> TrueClass
    def clear: () -> NilClass
    def first: () -> Cv::Rect2d
    def include?: (value: Cv::Rect2d) -> TrueClass
    def index: (value: Cv::Rect2d) -> Integer
    def initialize_copy: (other: Std::Vector≺cv꞉꞉Rect_≺double≻≻) -> NilClass
    def insert: (pos: Integer, value: Cv::Rect2d) -> Std::Vector≺cv꞉꞉Rect_≺double≻≻
    def last: () -> Cv::Rect2d
    def max_size: () -> Integer
    def pop: () -> Cv::Rect2d
    def push: (value: Cv::Rect2d) -> Std::Vector≺cv꞉꞉Rect_≺double≻≻
    def reserve: (new_cap: Integer) -> NilClass
    def resize: (count: Integer) -> NilClass
    def shrink_to_fit: () -> NilClass
    def size: () -> Integer
    def to_a: () -> Integer
    def to_s: () -> String
  end
end
