module Cv::TrackerDaSiamRPN
  class Params
    attr_accessor backend: Integer
    attr_accessor kernel_cls1: String
    attr_accessor kernel_r1: String
    attr_accessor model: String
    attr_accessor target: Integer

    def initialize: () -> NilClass
  end
end
