module Cv::TrackerNano
  class Params
    attr_accessor backbone: String
    attr_accessor backend: Integer
    attr_accessor neckhead: String
    attr_accessor target: Integer

    def initialize: () -> NilClass
  end
end
