module Cv::SimpleBlobDetector
  class Params
    attr_accessor blob_color: String
    attr_accessor collect_contours: TrueClass
    attr_accessor filter_by_area: TrueClass
    attr_accessor filter_by_circularity: TrueClass
    attr_accessor filter_by_color: TrueClass
    attr_accessor filter_by_convexity: TrueClass
    attr_accessor filter_by_inertia: TrueClass
    attr_accessor max_area: Float
    attr_accessor max_circularity: Float
    attr_accessor max_convexity: Float
    attr_accessor max_inertia_ratio: Float
    attr_accessor max_threshold: Float
    attr_accessor min_area: Float
    attr_accessor min_circularity: Float
    attr_accessor min_convexity: Float
    attr_accessor min_dist_between_blobs: Float
    attr_accessor min_inertia_ratio: Float
    attr_accessor min_repeatability: Integer
    attr_accessor min_threshold: Float
    attr_accessor threshold_step: Float

    def initialize: () -> NilClass
    def read: (fn: Cv::FileNode) -> NilClass
    def write: (fs: Cv::FileStorage) -> NilClass
  end
end
