module Cv::TrackerVit
  class Params
    attr_accessor backend: Integer
    attr_accessor meanvalue: Cv::Scalar_≺double≻
    attr_accessor net: Std::String
    attr_accessor stdvalue: Cv::Scalar_≺double≻
    attr_accessor target: Integer

    def initialize: () -> void
  end
end
