module Cv::TrackerVit
  class Params
    attr_accessor backend: Integer
    attr_accessor meanvalue: Cv::Scalar
    attr_accessor net: String
    attr_accessor stdvalue: Cv::Scalar
    attr_accessor target: Integer

    def initialize: () -> NilClass
  end
end
